import { BarChart3, Boxes, CalendarDays, Calculator, Home, LayoutGrid, LogOut, MoreHorizontal, Package, Palette, Plus, ReceiptText, Search, Settings as SettingsIcon, Users, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { useDialogA11y } from "@/hooks/use-dialog-a11y";
import { useConnectivity } from "@/hooks/use-connectivity";

export type NatView = "home" | "sales" | "customers" | "intelligence" | "calendar" | "inventory" | "portfolio" | "products" | "pricing" | "identity";
type Props={view:NatView;onView:(view:NatView)=>void;onSale:()=>void;onSearch:()=>void;onSettings:()=>void;onLogout:()=>void;children:ReactNode};
export function Brand(){return <div className="flex min-w-0 items-center gap-3"><div className="relative grid h-12 w-12 shrink-0 place-items-center rounded-full border-2 border-chocolate"><div aria-hidden="true" className="absolute inset-[4px] rounded-full border border-chocolate"/><span className="relative z-10 font-display text-[18px] leading-none">NAT</span></div><div className="min-w-0"><div className="truncate font-display text-xl leading-none">NAT Gestão</div><div className="mt-1 truncate text-[10px] font-bold uppercase tracking-[0.18em] text-caramel">Brownies • Brigadeiros</div></div></div>;}
function SideButton({icon,label,active,onClick}:{icon:ReactNode;label:string;active:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} className={`side-button ${active?"active":""}`}>{icon}<span>{label}</span></button>;}
const navItems:{view:NatView;label:string;mobileLabel?:string;icon:ReactNode;group:"operacao"|"base"|"analise"|"marca"}[]=[
  {view:"home",label:"Início",icon:<Home size={18}/>,group:"operacao"},{view:"sales",label:"Vendas e saídas",mobileLabel:"Vendas",icon:<ReceiptText size={18}/>,group:"operacao"},{view:"calendar",label:"Agenda",icon:<CalendarDays size={18}/>,group:"operacao"},{view:"inventory",label:"Estoque",icon:<Boxes size={18}/>,group:"operacao"},
  {view:"products",label:"Produtos e compras",mobileLabel:"Produtos",icon:<Package size={18}/>,group:"base"},{view:"portfolio",label:"Portfólio",icon:<LayoutGrid size={18}/>,group:"base"},{view:"pricing",label:"Preços",icon:<Calculator size={18}/>,group:"base"},
  {view:"customers",label:"Clientes",icon:<Users size={18}/>,group:"analise"},{view:"intelligence",label:"Análises",icon:<BarChart3 size={18}/>,group:"analise"},{view:"identity",label:"Identidade visual",mobileLabel:"Identidade",icon:<Palette size={18}/>,group:"marca"},
];
const mobilePrimary=navItems.filter((item)=>["home","sales","customers","intelligence"].includes(item.view));const mobileMore=navItems.filter((item)=>["calendar","inventory","products","portfolio","pricing","identity"].includes(item.view));
function MobileNav({view,onView,onSale}:{view:NatView;onView:(view:NatView)=>void;onSale:()=>void}){const[moreOpen,setMoreOpen]=useState(false);const closeMore=()=>setMoreOpen(false);const morePanelRef=useDialogA11y<HTMLDivElement>({open:moreOpen,onClose:closeMore});const moreActive=mobileMore.some((item)=>item.view===view);return <><nav aria-label="Navegação principal" className="fixed inset-x-0 bottom-0 z-30 border-t border-nat bg-white/95 px-[max(8px,env(safe-area-inset-left))] pb-[max(8px,env(safe-area-inset-bottom))] pt-2 backdrop-blur lg:hidden"><div className="mx-auto grid max-w-xl grid-cols-5 items-end">{mobilePrimary.map((item)=><button type="button" key={item.view} className={`mobile-nav-button min-w-0 ${view===item.view?"active":""}`} aria-current={view===item.view?"page":undefined} onClick={()=>onView(item.view)}>{item.icon}<span className="max-w-full truncate">{item.mobileLabel??item.label}</span></button>)}<button type="button" className={`mobile-nav-button min-w-0 ${moreActive?"active":""}`} aria-expanded={moreOpen} aria-controls="nat-mobile-more" onClick={()=>setMoreOpen(true)}><MoreHorizontal size={18}/><span>Mais</span></button></div></nav>{!moreOpen&&<button type="button" className="fixed z-40 grid h-12 w-12 place-items-center rounded-full bg-chocolate text-white shadow-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-chocolate lg:hidden" style={{right:"max(16px, env(safe-area-inset-right))",bottom:"calc(env(safe-area-inset-bottom) + 72px)"}} onClick={onSale} aria-label="Registrar venda ou saída"><Plus size={22}/></button>}{moreOpen&&<div className="fixed inset-0 z-50 flex items-end bg-[#35150A]/30 lg:hidden" onMouseDown={(event)=>{if(event.target===event.currentTarget)closeMore();}}><div id="nat-mobile-more" ref={morePanelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="nat-mobile-more-title" className="max-h-[100dvh] w-full overflow-y-auto overscroll-contain rounded-t-[28px] bg-cream p-5 pb-[max(24px,env(safe-area-inset-bottom))] pt-[max(20px,env(safe-area-inset-top))] shadow-2xl"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Navegação</p><h2 id="nat-mobile-more-title" className="font-display text-3xl">Mais opções</h2></div><button type="button" className="icon-button" onClick={closeMore} aria-label="Fechar menu"><X size={19}/></button></div><div className="mt-5 grid gap-2">{mobileMore.map((item)=><button type="button" key={item.view} className={`flex min-h-14 items-center gap-3 rounded-2xl border border-nat bg-white px-4 text-left font-bold ${view===item.view?"ring-2 ring-rose":""}`} aria-current={view===item.view?"page":undefined} onClick={()=>{closeMore();onView(item.view);}}>{item.icon}<span className="flex-1">{item.label}</span></button>)}</div></div></div>}</>;}
function ConnectivityBanner(){const state=useConnectivity();if(state==="online")return null;const text=state==="offline"?"Sem internet. Você pode consultar o que já está na tela, mas novas alterações não serão salvas até a conexão voltar.":"Conexão voltou. Reconectando com segurança…";return <div role="status" className="border-b border-nat bg-rose-soft px-4 py-2 text-center text-xs font-bold text-chocolate">{text}</div>;}
const groupTitle={operacao:"Operação",base:"Catálogo e custos",analise:"Relacionamento e análise",marca:"Marca"} as const;
export function AppShell({view,onView,onSale,onSearch,onSettings,onLogout,children}:Props){return <div className="min-h-screen min-h-[100dvh] bg-cream text-chocolate"><header className="sticky top-0 z-30 border-b border-nat bg-cream/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3 sm:px-6"><Brand/><div className="flex shrink-0 items-center gap-1"><button type="button" className="icon-button" onClick={onSearch} aria-label="Buscar na NAT"><Search size={20}/></button><button type="button" className="icon-button" onClick={onSettings} aria-label="Configurações"><SettingsIcon size={20}/></button><button type="button" className="icon-button" onClick={onLogout} aria-label="Sair"><LogOut size={19}/></button></div></div></header><ConnectivityBanner/><div className="mx-auto flex max-w-6xl gap-8 px-4 pb-28 pt-6 sm:px-6 lg:pb-12"><aside className="hidden w-56 shrink-0 lg:block"><nav aria-label="Navegação principal" className="sticky top-24 space-y-5">{(["operacao","base","analise","marca"] as const).map((group)=><div key={group}><p className="mb-2 px-3 text-[10px] font-black uppercase tracking-[0.18em] text-caramel">{groupTitle[group]}</p><div className="space-y-1">{navItems.filter((item)=>item.group===group).map((item)=><SideButton key={item.view} icon={item.icon} label={item.label} active={view===item.view} onClick={()=>onView(item.view)}/>)}</div></div>)}</nav></aside><main className="min-w-0 flex-1">{children}</main></div><MobileNav view={view} onView={onView} onSale={onSale}/></div>;}
