import { Phone, Plus, ShieldCheck, Trash2, Users, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { activeSaleLines, customerInsights, customerOverview, customerPaymentProfile, id, isStreetCustomer, money, paymentPromiseLabel, saleValue, type Customer, type NatState } from "@/domain/nat";
import { eraseCustomerPrivacy, loadLatestCustomerConsent, type ConsentInfo } from "@/data/customer-privacy-repository";
import { useDialogA11y } from "@/hooks/use-dialog-a11y";
import { useSubmitGuard } from "@/hooks/use-submit-guard";
import { ConfirmDialog } from "./Feedback";

function payerTone(status:string){return status==="critical"?"bg-red-100 text-red-800":status==="overdue"?"bg-amber-100 text-amber-800":status==="good"?"bg-green-100 text-green-800":"bg-soft text-caramel";}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-soft p-3"><p className="text-xs font-bold uppercase tracking-[0.08em] text-caramel">{label}</p><p className="mt-1 font-bold">{value}</p></div>;}

export function CustomersView({state,onSave}:{state:NatState;onSave:(customer:Customer)=>void}){
  const[editing,setEditing]=useState<Customer|null>(null);const[creating,setCreating]=useState(false);const insights=useMemo(()=>customerInsights(state),[state]);const overview=useMemo(()=>customerOverview(state),[state]);const sorted=[...insights].sort((a,b)=>b.rfmTotal-a.rfmTotal||b.totalSpent-a.totalSpent||a.customer.name.localeCompare(b.customer.name,"pt-BR"));
  return <section className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Relacionamento</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Fichas de clientes</h1><p className="mt-2 max-w-2xl text-base leading-6 text-caramel">Cada ficha reúne contato, histórico de compras e comportamento de pagamento. Clientes de rua podem ficar sem telefone; os demais precisam de contato ao salvar a ficha.</p></div><button type="button" className="primary-button" onClick={()=>{setEditing(null);setCreating(true);}}><Plus size={18}/> Nova ficha</button></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Mini label="Clientes ativos" value={String(overview.activeCustomers)}/><Mini label="Voltaram a comprar" value={String(overview.recurrent)}/><Mini label="Média por compra" value={money(overview.averageTicket)}/><Mini label="Atraso crítico" value={String((state.customers??[]).filter((c)=>c.creditStatus==="critical").length)}/></div>
  <div className="nat-card"><div className="flex items-center gap-2"><Users size={19}/><h2 className="section-title">Fichas cadastradas</h2></div><div className="mt-4 space-y-3">{sorted.map((row)=>{const payer=customerPaymentProfile(state,row.customer.id);return <button key={row.customer.id} type="button" onClick={()=>{setEditing(row.customer);setCreating(true);}} className="w-full rounded-2xl border border-[#956454] p-4 text-left"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="font-bold">{row.customer.name}</p><p className="mt-1 flex items-center gap-1 text-sm text-caramel"><Phone size={13}/>{row.customer.phone??(isStreetCustomer(row.customer)?"Cliente de rua · contato dispensado":"Telefone pendente")}</p><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${payerTone(payer.status)}`}>{payer.label}</span></div><div className="text-right"><p className="font-bold">{money(row.totalSpent)}</p><p className="text-sm text-caramel">{row.orders} compra(s)</p>{payer.pendingAmount>0&&<p className="mt-1 text-sm font-bold text-amber-800">A receber {money(payer.pendingAmount)}</p>}</div></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Mini label="Última compra" value={row.lastPurchase?new Intl.DateTimeFormat("pt-BR").format(new Date(row.lastPurchase)):"—"}/><Mini label="Produto favorito" value={row.favoriteProduct??"—"}/><Mini label="Advertências" value={String(payer.warningHistory)}/></div></button>;})}{!sorted.length&&<div className="rounded-2xl border border-dashed border-[#956454] p-7 text-center"><p className="font-bold">Nenhuma ficha cadastrada.</p><button type="button" className="primary-button mt-4" onClick={()=>setCreating(true)}><Plus size={16}/> Cadastrar primeiro cliente</button></div>}</div></div>
  <details className="nat-card"><summary className="flex cursor-pointer list-none items-center gap-2 font-bold"><ShieldCheck size={19}/>Privacidade dos clientes</summary><p className="mt-4 text-sm leading-6 text-caramel">Nome e telefone são usados para atender o cliente, acompanhar compras e cobranças. Promoções continuam dependendo de autorização. Uma ficha com pagamento pendente não pode ser apagada até a quitação ou cancelamento.</p></details>
  {creating&&<CustomerEditor state={state} value={editing} onClose={()=>setCreating(false)} onSave={(customer)=>{onSave(customer);setCreating(false);}}/>}</section>;
}

function CustomerEditor({state,value,onClose,onSave}:{state:NatState;value:Customer|null;onClose:()=>void;onSave:(customer:Customer)=>void}){
  const[draftId]=useState(()=>value?.id??id("customer"));const[name,setName]=useState(value?.name??"");const[phone,setPhone]=useState(value?.phone??"");const[instagram,setInstagram]=useState(value?.instagram??"");const[source,setSource]=useState(value?.source??"");const[notes,setNotes]=useState(value?.notes??"");const[consent,setConsent]=useState(value?.marketingConsent??false);const[error,setError]=useState("");const[errorTarget,setErrorTarget]=useState("");const[privacyBusy,setPrivacyBusy]=useState(false);const[consentInfo,setConsentInfo]=useState<ConsentInfo|null>(null);const[eraseOpen,setEraseOpen]=useState(false);const[eraseText,setEraseText]=useState("");const{submitting,begin,reset}=useSubmitGuard();const busy=submitting||privacyBusy;const safeClose=()=>{if(!busy)onClose();};const panelRef=useDialogA11y<HTMLDivElement>({onClose:safeClose});const errorRef=useRef<HTMLParagraphElement>(null);
  const draftCustomer:Customer={id:draftId,name,phone:phone||null,instagram:instagram||null,source:source||null,notes:notes||null,marketingConsent:consent,active:value?.active??true,creditStatus:value?.creditStatus??"normal",createdAt:value?.createdAt??new Date().toISOString(),updatedAt:new Date().toISOString()};
  const payer=value?customerPaymentProfile(state,value.id):null;const history=value?state.sales.filter((sale)=>sale.customerId===value.id&&(sale.transactionType??"sale")==="sale").sort((a,b)=>+new Date(b.soldAt)-+new Date(a.soldAt)):[];
  useEffect(()=>{let cancelled=false;async function load(){if(!value)return;try{const result=await loadLatestCustomerConsent(value.id);if(!cancelled)setConsentInfo(result);}catch{if(!cancelled)setConsentInfo(null);}}void load();return()=>{cancelled=true;};},[value]);
  const fail=(message:string,target="")=>{setError(message);setErrorTarget(target);window.requestAnimationFrame(()=>{if(target)document.getElementById(target)?.focus();else errorRef.current?.focus();});};
  const invalid=(fieldId:string)=>errorTarget===fieldId||undefined;const described=(fieldId:string)=>errorTarget===fieldId?"customer-error":undefined;
  function submit(e:React.FormEvent){e.preventDefault();setError("");setErrorTarget("");if(!name.trim())return fail("Informe o nome do cliente.","customer-name");if(!isStreetCustomer(draftCustomer)&&!phone.trim())return fail("Informe o telefone. Apenas clientes de rua podem ficar sem contato.","customer-phone");const digits=notes.replace(/\D/g,"");if(/\d{3}\.\d{3}\.\d{3}-\d{2}|\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}/.test(notes)||digits.length===11||digits.length===14)return fail("Retire CPF ou CNPJ das observações.","customer-notes");if(!begin())return;try{onSave({...draftCustomer,name:name.trim(),phone:phone.trim()||null,instagram:instagram.trim()||null,source:source.trim()||null,notes:notes.trim()||null,updatedAt:new Date().toISOString()});}catch(cause){reset();fail(cause instanceof Error?cause.message:"Não foi possível salvar o cliente. Revise os dados e tente novamente.");}}
  async function erase(){if(!value||privacyBusy||eraseText!=="EXCLUIR")return;setPrivacyBusy(true);setError("");setErrorTarget("");try{await eraseCustomerPrivacy(value.id,"Solicitação registrada pela ficha do cliente");window.location.reload();}catch(cause){fail(cause instanceof Error?cause.message:"Não foi possível excluir os dados pessoais.");setPrivacyBusy(false);setEraseOpen(false);}}
  return <><div className="fixed inset-0 z-50 flex justify-end bg-[#35150A]/35" onMouseDown={(e)=>{if(e.target===e.currentTarget)safeClose();}}><div ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="customer-editor-title" className="h-full w-full max-w-xl overflow-y-auto bg-[#FFF9F6] p-5 sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Ficha de cliente</p><h2 id="customer-editor-title" className="font-display text-4xl">{value?value.name:"Novo cliente"}</h2></div><button className="icon-button" type="button" onClick={safeClose} disabled={busy} aria-label="Fechar"><X size={19}/></button></div>
  {value&&payer&&<div className="mt-5 rounded-2xl bg-soft p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wider text-caramel">Comportamento de pagamento</p><p className="mt-1 font-bold">{payer.label}</p></div>{payer.pendingAmount>0&&<p className="font-bold text-amber-800">A receber {money(payer.pendingAmount)}</p>}</div><p className="mt-2 text-sm text-caramel">{payer.creditSales} compra(s) com pagamento combinado · {payer.warningHistory} advertência(s) de atraso.</p></div>}
  <form className="mt-6 space-y-4" onSubmit={submit} noValidate><fieldset disabled={busy} className="contents"><div><label htmlFor="customer-name" className="field-label">Nome</label><input id="customer-name" className="nat-input" value={name} onChange={(e)=>setName(e.target.value)} maxLength={160} aria-invalid={invalid("customer-name")} aria-describedby={described("customer-name")}/></div><div><label htmlFor="customer-phone" className="field-label">Telefone</label><input id="customer-phone" className="nat-input" value={phone} onChange={(e)=>setPhone(e.target.value)} maxLength={40} placeholder="Ex.: (11) 99999-9999" aria-invalid={invalid("customer-phone")} aria-describedby={errorTarget==="customer-phone"?"customer-error customer-phone-help":"customer-phone-help"}/><p id="customer-phone-help" className="field-help">Obrigatório, exceto quando a origem for Rua.</p></div><div className="grid gap-3 sm:grid-cols-2"><div><label htmlFor="customer-source" className="field-label">Origem</label><input id="customer-source" className="nat-input" value={source} onChange={(e)=>setSource(e.target.value)} placeholder="Ex.: WhatsApp, Vizinha, Rua" maxLength={120}/></div><div><label className="field-label" htmlFor="customer-instagram">Instagram</label><input id="customer-instagram" className="nat-input" value={instagram} onChange={(e)=>setInstagram(e.target.value)} maxLength={80}/></div></div><div><label htmlFor="customer-notes" className="field-label">Observações</label><textarea id="customer-notes" className="nat-input min-h-20" value={notes} onChange={(e)=>setNotes(e.target.value)} maxLength={500} aria-invalid={invalid("customer-notes")} aria-describedby={described("customer-notes")}/></div><label className="flex gap-3 rounded-2xl bg-soft p-4"><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)} className="mt-1 h-5 w-5"/><span><strong>Autoriza novidades e promoções</strong><span className="block text-sm text-caramel">Marque somente se o cliente autorizou contato comercial.</span>{consentInfo&&<span className="mt-1 block text-sm text-caramel">Última autorização registrada em {new Intl.DateTimeFormat("pt-BR").format(new Date(consentInfo.occurred_at))}</span>}</span></label></fieldset>{error&&<p id="customer-error" ref={errorRef} tabIndex={-1} role="alert" className="a11y-error">{error}</p>}<button className="primary-button w-full justify-center" type="submit" disabled={busy}>{submitting?"Salvando cliente...":"Salvar ficha"}</button></form>
  {value&&<div className="mt-7 border-t border-nat pt-5"><h3 className="font-bold">Histórico de compras</h3><div className="mt-3 space-y-2">{history.map((sale)=><div key={sale.id} className="rounded-2xl bg-soft p-3"><div className="flex justify-between gap-3"><div><p className="font-bold">{activeSaleLines(sale).map((line)=>`${line.quantity}× ${line.productName}`).join(" · ")}</p><p className="text-sm text-caramel">{new Intl.DateTimeFormat("pt-BR").format(new Date(sale.soldAt))}{sale.paymentStatus==="pending"?` · pendente · ${paymentPromiseLabel(sale)??"sem promessa"}`:" · pago"}</p></div><p className="font-bold">{money(saleValue(sale))}</p></div></div>)}{!history.length&&<p className="text-sm text-caramel">Nenhuma compra vinculada a esta ficha.</p>}</div><button type="button" className="mt-5 flex min-h-11 items-center gap-2 text-sm font-bold text-red-700" disabled={busy} onClick={()=>{setEraseText("");setEraseOpen(true);}}><Trash2 size={16}/> Excluir dados pessoais</button></div>}</div></div>
  {eraseOpen&&value&&<ConfirmDialog title={`Excluir dados pessoais de ${value.name}?`} text="Pagamentos pendentes precisam ser quitados ou cancelados primeiro. As vendas quitadas permanecem no histórico financeiro sem identificar o cliente." confirmLabel="Excluir dados pessoais" danger busy={privacyBusy} onClose={()=>setEraseOpen(false)} onConfirm={()=>void erase()}><label className="field-label" htmlFor="privacy-confirm">Digite EXCLUIR para confirmar</label><input id="privacy-confirm" className="nat-input mt-1" value={eraseText} onChange={(e)=>setEraseText(e.target.value.toUpperCase())}/></ConfirmDialog>}</>;
}
