import { X } from "lucide-react";
import { useId, useState } from "react";
import { id, type SporadicExpense } from "@/domain/nat";
import { useDialogA11y } from "@/hooks/use-dialog-a11y";
import { useSubmitGuard } from "@/hooks/use-submit-guard";

export function ExpenseEditorSheet({value,presetName,onClose,onSave}:{value?:SporadicExpense;presetName?:string;onClose:()=>void;onSave:(expense:SporadicExpense)=>void}){
  const titleId=useId();const[draftId]=useState(()=>value?.id??id("expense"));const[name,setName]=useState(value?.name??presetName??"");const[amount,setAmount]=useState(String(value?.amount??""));const[date,setDate]=useState(value?.spentAt.slice(0,10)??new Date().toISOString().slice(0,10));const[error,setError]=useState("");const{submitting,begin,reset}=useSubmitGuard();const safeClose=()=>{if(!submitting)onClose();};const panelRef=useDialogA11y<HTMLDivElement>({onClose:safeClose});const numericAmount=Number(amount.replace(",","."));
  function submit(e:React.FormEvent){e.preventDefault();setError("");if(!name.trim())return setError("Informe o nome do gasto.");if(!Number.isFinite(numericAmount)||numericAmount<0)return setError("Informe um valor válido.");if(!date)return setError("Informe a data do gasto.");if(!begin())return;try{onSave({id:draftId,name:name.trim(),amount:numericAmount,spentAt:date});}catch(cause){reset();setError(cause instanceof Error?cause.message:"Não foi possível salvar o gasto.");}}
  return <div className="fixed inset-0 z-50 flex justify-end bg-[#35150A]/35 backdrop-blur-[2px]" onMouseDown={(event)=>{if(event.target===event.currentTarget)safeClose();}}><div ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} className="h-full w-full max-w-xl overflow-y-auto bg-[#FFF9F6] p-5 pb-[max(24px,env(safe-area-inset-bottom))] pt-[max(20px,env(safe-area-inset-top))] shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Produtos e compras</p><h2 id={titleId} className="mt-2 font-display text-4xl">{value?"Editar gasto":"Registrar gasto extra"}</h2><p className="mt-2 text-sm leading-6 text-caramel">Use para compras pontuais que reduzem o resultado do mês, mas não viram estoque.</p></div><button type="button" className="icon-button" onClick={safeClose} disabled={submitting} aria-label="Fechar"><X size={20}/></button></div><form className="mt-7 space-y-5" onSubmit={submit}><fieldset disabled={submitting} className="contents"><div><label className="field-label" htmlFor="expense-name">O que foi pago?</label><input id="expense-name" className="nat-input" value={name} onChange={(e)=>setName(e.target.value)} required maxLength={160}/></div><div><label className="field-label" htmlFor="expense-amount">Valor pago</label><input id="expense-amount" className="nat-input" inputMode="decimal" value={amount} onChange={(e)=>setAmount(e.target.value)} required/></div><div><label className="field-label" htmlFor="expense-date">Data</label><input id="expense-date" type="date" className="nat-input" value={date} onChange={(e)=>setDate(e.target.value)} required/></div></fieldset>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="primary-button w-full justify-center" type="submit" disabled={submitting}>{submitting?"Salvando gasto...":"Salvar gasto"}</button></form></div></div>;
}
