import { BarChart3, CalendarDays, DatabaseBackup, Download, Package, Plus, ReceiptText, Search, Settings2, ShoppingBasket, SlidersHorizontal, Users } from "lucide-react";
import { useEffect, useState } from "react";
import type { CalendarEvent } from "@/domain/calendar";
import { inventoryQuantity, type InventorySnapshot } from "@/domain/inventory";
import { businessInsights, todaySalesSummary } from "@/domain/insights";
import { money, type NatState, type Sale } from "@/domain/nat";
import { exportNatBackup, exportNatCsv } from "@/lib/export-data";
import { downloadDiagnostics } from "@/lib/telemetry";

function todayKey(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;}
function ActionButton({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button type="button" className="secondary-button min-h-12 justify-center" onClick={onClick}>{children}</button>;}
function ChecklistItem({done,title,text,onClick}:{done:boolean;title:string;text:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="flex min-h-16 w-full items-start gap-3 rounded-2xl border border-white/15 bg-white/5 p-4 text-left transition hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"><span className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-black ${done?"bg-rose text-chocolate":"bg-white/10 text-white"}`}>{done?"✓":""}</span><span><strong className="block">{title}</strong><span className="mt-1 block text-sm text-white/70">{text}</span></span></button>;}
function formatPercent(value:number|null){if(value==null||!Number.isFinite(value))return "Sem comparação ainda";const signal=value>0?"+":"";return `${signal}${new Intl.NumberFormat("pt-BR",{maximumFractionDigits:1}).format(value)}% vs. 7 dias anteriores`;}
type Prefs={reports:boolean;data:boolean;recent:boolean};const defaultPrefs:Prefs={reports:true,data:false,recent:true};

export function HomeOperations({state,events,inventory,onSale,onRepeatSale,onSearch,onSupplies,onProducts,onPricing,onCalendar,onInventory,onCustomers}:{state:NatState;events:CalendarEvent[];inventory:InventorySnapshot;onSale:()=>void;onRepeatSale:(sale:Sale)=>void;onSearch:()=>void;onSupplies:()=>void;onProducts:()=>void;onPricing:()=>void;onCalendar:()=>void;onInventory:()=>void;onCustomers:()=>void}){
  const[prefs,setPrefs]=useState<Prefs>(defaultPrefs);const[customizing,setCustomizing]=useState(false);useEffect(()=>{try{const raw=localStorage.getItem("nat-home-preferences-v1");if(raw)setPrefs({...defaultPrefs,...JSON.parse(raw)});}catch{/* preferência local opcional */}},[]);const changePref=(key:keyof Prefs)=>setPrefs((current)=>{const next={...current,[key]:!current[key]};try{localStorage.setItem("nat-home-preferences-v1",JSON.stringify(next));}catch{/* sem armazenamento local */}return next;});
  const activeSales=state.sales.filter((sale)=>sale.status!=="cancelled"&&(sale.transactionType??"sale")==="sale");const onboarding=[{done:state.supplies.length>0,title:"1. Registre uma compra",text:"Informe o que comprou, quanto veio e quanto pagou.",action:onSupplies},{done:state.products.some((product)=>product.recipe.length>0),title:"2. Monte uma receita",text:"Escolha ingredientes e rendimento do lote.",action:onProducts},{done:state.products.some((product)=>product.sellingPrice>0),title:"3. Confira o preço",text:"Veja custo e preço recomendado antes de vender.",action:onPricing},{done:activeSales.length>0,title:"4. Registre a primeira venda",text:"A NAT passa a acompanhar receita e resultado.",action:onSale}];const completed=onboarding.filter((item)=>item.done).length;const today=todaySalesSummary(state);const todayEvents=events.filter((event)=>event.eventDate===todayKey()&&event.status!=="cancelled");const pendingEvents=todayEvents.filter((event)=>event.status==="planned");const lowStock=inventory.items.filter((item)=>item.tracked&&item.lowStock);const insights=businessInsights(state);const lastSale=activeSales[0]??null;const lastCustomer=(state.customers??[])[0]??null;const productWithoutPrice=state.products.find((product)=>product.recipe.length>0&&product.sellingPrice<=0)??null;
  return <div className="space-y-5">{completed<onboarding.length&&<section className="rounded-[28px] bg-chocolate p-5 text-white sm:p-7" aria-labelledby="onboarding-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-rose">Comece por aqui</p><h2 id="onboarding-title" className="mt-2 font-display text-3xl">Configuração guiada</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/70">A NAT indica o próximo passo sem exigir conhecimento de dashboards ou automações.</p></div><span className="shrink-0 rounded-full bg-white/10 px-3 py-1 text-sm font-bold">{completed}/4</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{onboarding.map((item)=><ChecklistItem key={item.title} {...item} onClick={item.action}/>)}</div></section>}
  <section className="nat-card" aria-labelledby="today-title"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Central do dia</p><h2 id="today-title" className="section-title">O que precisa de atenção</h2><p className="mt-1 text-sm text-caramel">Ações primeiro; números depois.</p></div><div className="flex flex-wrap gap-2"><button type="button" className="secondary-button justify-center" onClick={onSearch}><Search size={17}/> Buscar</button><button type="button" className="primary-button justify-center" onClick={onSale}><Plus size={18}/> Registrar venda</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-soft p-4"><ReceiptText size={18}/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-caramel">Vendas hoje</p><p className="mt-1 font-display text-3xl">{money(today.revenue)}</p><p className="text-xs text-caramel">{today.sales.length} pedidos • {today.units} unidades</p></div><div className="rounded-2xl bg-soft p-4"><BarChart3 size={18}/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-caramel">Resultado de hoje</p><p className="mt-1 font-display text-3xl">{money(today.contribution)}</p><p className="text-xs text-caramel">antes de custos fixos e gastos do mês</p></div><button type="button" onClick={onCalendar} className="rounded-2xl bg-soft p-4 text-left"><CalendarDays size={18}/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-caramel">Agenda</p><p className="mt-1 font-display text-3xl">{pendingEvents.length}</p><p className="text-xs text-caramel">{pendingEvents.length?`${pendingEvents.length} compromisso(s) para resolver hoje`:"nenhuma pendência hoje"}</p></button><button type="button" onClick={onInventory} className={`rounded-2xl p-4 text-left ${lowStock.length?"bg-rose-soft":"bg-soft"}`}><Package size={18}/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-caramel">Compras necessárias</p><p className="mt-1 font-display text-3xl">{lowStock.length}</p><p className="text-xs text-caramel">{lowStock.length?"itens com estoque baixo":"estoque sem alertas"}</p></button></div>
  {(pendingEvents.length>0||lowStock.length>0||productWithoutPrice)&&<div className="mt-4 grid gap-3 lg:grid-cols-3">{pendingEvents.length>0&&<button type="button" onClick={onCalendar} className="rounded-2xl border border-nat p-4 text-left"><p className="font-bold">Resolver agenda</p><p className="mt-1 text-sm text-caramel">{pendingEvents[0].title}{pendingEvents.length>1?` e mais ${pendingEvents.length-1}`:""}</p><span className="mt-3 inline-block text-xs font-black underline">Abrir agenda</span></button>}{lowStock.length>0&&<button type="button" onClick={onSupplies} className="rounded-2xl border border-nat p-4 text-left"><p className="font-bold">Registrar compra</p><p className="mt-1 text-sm text-caramel">{lowStock.slice(0,2).map((item)=>`${item.name} (${inventoryQuantity(item.currentQuantity,item.baseUnit)})`).join(" · ")}</p><span className="mt-3 inline-block text-xs font-black underline">Ir para compras</span></button>}{productWithoutPrice&&<button type="button" onClick={onPricing} className="rounded-2xl border border-nat p-4 text-left"><p className="font-bold">Definir preço</p><p className="mt-1 text-sm text-caramel">{productWithoutPrice.name} já tem receita, mas ainda está sem preço.</p><span className="mt-3 inline-block text-xs font-black underline">Conferir preços</span></button>}</div>}
  <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><ActionButton onClick={onSupplies}><ShoppingBasket size={17}/> Nova compra</ActionButton><ActionButton onClick={onProducts}><Package size={17}/> Produtos</ActionButton><ActionButton onClick={onPricing}><Settings2 size={17}/> Preços</ActionButton><ActionButton onClick={onCalendar}><CalendarDays size={17}/> Agenda</ActionButton></div></section>
  {prefs.recent&&<section className="nat-card"><div className="flex items-center justify-between gap-3"><div><p className="eyebrow">Atalhos</p><h2 className="section-title">Continuar de onde parou</h2></div><button type="button" className="text-xs font-bold text-caramel underline" onClick={()=>setCustomizing(true)}>Personalizar</button></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{lastSale?<button type="button" className="secondary-button justify-start" onClick={()=>onRepeatSale(lastSale)}><ReceiptText size={17}/> Repetir última venda</button>:<button type="button" className="secondary-button justify-start" onClick={onSale}><ReceiptText size={17}/> Primeira venda</button>}<button type="button" className="secondary-button justify-start" onClick={onSupplies}><ShoppingBasket size={17}/> Repetir/registrar compra</button><button type="button" className="secondary-button justify-start" onClick={onCustomers}><Users size={17}/> {lastCustomer?`Ver clientes · ${lastCustomer.name}`:"Cadastrar cliente"}</button></div></section>}
  {prefs.reports&&<section className="nat-card" aria-labelledby="insights-title"><div className="flex items-start gap-3"><BarChart3 className="mt-1 shrink-0" size={20}/><div><p className="eyebrow">Relatórios úteis</p><h2 id="insights-title" className="section-title">Desempenho com base confiável</h2><p className="mt-1 text-sm text-caramel">A NAT só destaca padrões depois de pelo menos 10 vendas distribuídas por 7 dias.</p></div></div>{!insights.readiness.ready?<div className="mt-5 rounded-2xl bg-soft p-4"><p className="font-bold">Ainda estamos formando uma base confiável.</p><p className="mt-2 text-sm text-caramel">{insights.readiness.missingSales>0?`Faltam ${insights.readiness.missingSales} venda(s). `:""}{insights.readiness.missingDays>0?`Faltam ${insights.readiness.missingDays} dia(s) de histórico.`:""}</p></div>:<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-soft p-4"><p className="text-xs font-bold uppercase tracking-wider text-caramel">Ticket médio</p><p className="mt-2 font-display text-3xl">{money(insights.averageTicket)}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-xs font-bold uppercase tracking-wider text-caramel">Mais vendido</p><p className="mt-2 font-bold">{insights.topProduct?.name??"—"}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-xs font-bold uppercase tracking-wider text-caramel">Últimos 7 dias</p><p className="mt-2 font-display text-3xl">{money(insights.currentRevenue)}</p><p className="text-xs text-caramel">{formatPercent(insights.weeklyChangePercent)}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-xs font-bold uppercase tracking-wider text-caramel">Melhor dia</p><p className="mt-2 font-display text-3xl">{insights.bestDay?money(insights.bestDay.revenue):"—"}</p></div></div>}</section>}
  {prefs.data&&<section className="nat-card" aria-labelledby="backup-title"><div className="flex items-start gap-3"><DatabaseBackup className="mt-1 shrink-0" size={20}/><div><p className="eyebrow">Seus dados</p><h2 id="backup-title" className="section-title">Exportação e diagnóstico</h2><p className="mt-1 text-sm text-caramel">Ferramentas de backup ficam disponíveis sem ocupar espaço no dia a dia.</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-3"><ActionButton onClick={()=>exportNatCsv(state)}><Download size={17}/> CSV / Excel</ActionButton><ActionButton onClick={()=>exportNatBackup(state)}><DatabaseBackup size={17}/> Backup completo</ActionButton><ActionButton onClick={downloadDiagnostics}><Download size={17}/> Diagnóstico técnico</ActionButton></div></section>}
  {!prefs.data&&<button type="button" className="mx-auto flex items-center gap-2 text-xs font-bold text-caramel underline" onClick={()=>setCustomizing(true)}><SlidersHorizontal size={14}/> Personalizar início</button>}
  {customizing&&<div className="fixed inset-0 z-[55] flex items-end justify-center bg-[#35150A]/35 sm:items-center sm:p-6" onMouseDown={(event)=>{if(event.target===event.currentTarget)setCustomizing(false);}}><div className="w-full rounded-t-[28px] bg-[#FFF9F6] p-5 sm:max-w-md sm:rounded-[28px]"><p className="eyebrow">Seu início</p><h2 className="font-display text-3xl">O que quer ver na Home?</h2><div className="mt-5 space-y-2">{([['recent','Atalhos recentes'],['reports','Relatórios'],['data','Exportação e diagnóstico']] as [keyof Prefs,string][]).map(([key,label])=><label key={key} className="flex items-center justify-between rounded-2xl border border-nat p-4 font-bold"><span>{label}</span><input type="checkbox" checked={prefs[key]} onChange={()=>changePref(key)} className="h-5 w-5"/></label>)}</div><button type="button" className="primary-button mt-5 w-full justify-center" onClick={()=>setCustomizing(false)}>Concluir</button></div></div>}</div>;
}
