import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Boxes, PackageSearch, TrendingDown, TrendingUp, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { averageSecondPurchaseDays, channelAnalytics, cohortAnalytics, customerInsights, customerOverview, dashboardNumbers, money, percent, productPairs, productProfitability, promotionAnalytics, saleChannelLabel, supplyUnitCost, type NatState, type Unit } from "@/domain/nat";
import type { InventorySnapshot } from "@/domain/inventory";
import { Metric } from "./Views";

type PurchaseRow={supply_id:string;package_quantity:number|string;package_unit:Unit;package_price:number|string;purchased_at:string;created_at:string};
type PurchaseInsight={supplyId:string;name:string;lastDate:string;currentUnitCost:number;previousUnitCost:number|null;variation:number|null;totalSpent:number;purchases:number};
function baseQty(q:number,u:Unit){if(u==="kg")return q*1000;if(u==="l")return q*1000;return q;}
function purchaseUnitCost(row:PurchaseRow){const q=baseQty(Number(row.package_quantity),row.package_unit);return q>0?Number(row.package_price)/q:0;}
function producible(state:NatState,inventory:InventorySnapshot){
  return state.products.filter((p)=>p.available!==false&&p.recipe.length>0).map((product)=>{
    const missing:string[]=[];let maxBatches=Number.POSITIVE_INFINITY;
    for(const item of product.recipe){const supply=state.supplies.find((s)=>s.id===item.supplyId);if(!supply||supply.category==="packaging")continue;const tracked=inventory.items.find((x)=>x.kind==="supply"&&x.itemId===item.supplyId&&x.tracked);if(!tracked){missing.push(supply?.name??"Insumo");continue;}let required=baseQty(item.quantity,item.unit);if(supply.category==="ingredient")required*=1+Math.max(0,product.lossPercent)/100;if(required>0)maxBatches=Math.min(maxBatches,tracked.currentQuantity/required);}
    if(missing.length)return{name:product.name,units:null,missing};if(!Number.isFinite(maxBatches))return{name:product.name,units:null,missing:["Configure os insumos de produção"]};return{name:product.name,units:Math.max(0,Math.floor(maxBatches*product.batchYield)),missing:[]};
  });
}
export function IntelligenceView({state,inventory,businessId}:{state:NatState;inventory:InventorySnapshot;businessId:string|null}){
  const [purchases,setPurchases]=useState<PurchaseInsight[]>([]);const [purchaseError,setPurchaseError]=useState<string|null>(null);
  useEffect(()=>{let active=true;(async()=>{if(!businessId)return;const result=await supabase.from("supply_purchases").select("supply_id,package_quantity,package_unit,package_price,purchased_at,created_at").eq("business_id",businessId).order("purchased_at",{ascending:false}).order("created_at",{ascending:false});if(!active)return;if(result.error){setPurchaseError(result.error.message);return;}const rows=(result.data??[]) as PurchaseRow[];const map=new Map<string,PurchaseRow[]>();for(const row of rows){const list=map.get(row.supply_id)??[];list.push(row);map.set(row.supply_id,list);}setPurchases([...map.entries()].map(([supplyId,list])=>{const supply=state.supplies.find((s)=>s.id===supplyId);const current=purchaseUnitCost(list[0]);const previous=list[1]?purchaseUnitCost(list[1]):null;return{supplyId,name:supply?.name??"Insumo",lastDate:list[0].purchased_at,currentUnitCost:current,previousUnitCost:previous,variation:previous&&previous>0?(current-previous)/previous*100:null,totalSpent:list.reduce((sum,x)=>sum+Number(x.package_price),0),purchases:list.length};}).sort((a,b)=>Math.abs(b.variation??0)-Math.abs(a.variation??0)));})();return()=>{active=false};},[businessId,state.supplies]);
  const numbers=useMemo(()=>dashboardNumbers(state),[state]);const products=useMemo(()=>productProfitability(state),[state]);const customers=useMemo(()=>customerInsights(state),[state]);const overview=useMemo(()=>customerOverview(state),[state]);const channels=useMemo(()=>channelAnalytics(state),[state]);const pairs=useMemo(()=>productPairs(state),[state]);const cohorts=useMemo(()=>cohortAnalytics(state),[state]);const second=useMemo(()=>averageSecondPurchaseDays(state),[state]);const promos=useMemo(()=>promotionAnalytics(state),[state]);const production=useMemo(()=>producible(state,inventory),[state,inventory]);
  const bestRevenue=[...products].sort((a,b)=>b.revenue-a.revenue)[0];const bestContribution=[...products].sort((a,b)=>b.contribution-a.contribution)[0];const mostSold=[...products].sort((a,b)=>b.units-a.units)[0];const lowestMargin=[...products].sort((a,b)=>a.marginPercent-b.marginPercent)[0];const paidCustomers=customers.filter((c)=>c.orders>0);const baseSmall=numbers.sales.length<10;
  return <section className="space-y-6"><div><p className="eyebrow">Decisões com os dados da NAT</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Inteligência</h1><p className="mt-2 max-w-3xl text-caramel">Uma leitura simples do que vende, do que dá resultado, de quem recompra e do que precisa de atenção. Sem IA e sem inventar conclusões quando a base ainda é pequena.</p>{baseSmall&&<div className="mt-4 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><span><strong>Base pequena:</strong> use os indicadores como sinais iniciais, não como tendência consolidada.</span></div>}</div>

  <div className="nat-card"><div className="flex items-center gap-3"><BarChart3 size={20}/><div><p className="eyebrow">Saúde do negócio</p><h2 className="section-title">O mês em uma leitura</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Receita" value={money(numbers.revenue)} hint="vendas pagas"/><Metric label="Contribuição" value={money(numbers.contribution)} hint="após custos variáveis"/><Metric label="Margem média" value={percent(numbers.revenue?numbers.contribution/numbers.revenue*100:0)} hint="sobre a receita"/><Metric label="Pedidos" value={String(numbers.sales.length)} hint="vendas concluídas"/><Metric label="Ticket médio" value={money(numbers.sales.length?numbers.revenue/numbers.sales.length:0)} hint="por pedido"/></div></div>

  <div className="grid gap-6 lg:grid-cols-2"><div className="nat-card"><h2 className="section-title">Produtos</h2><p className="mt-1 text-sm text-caramel">Rentabilidade baseada nos snapshots congelados das vendas.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Maior receita" value={bestRevenue?.name??"—"} hint={bestRevenue?money(bestRevenue.revenue):"sem vendas"}/><Metric label="Maior contribuição" value={bestContribution?.name??"—"} hint={bestContribution?money(bestContribution.contribution):"sem vendas"}/><Metric label="Mais vendido" value={mostSold?.name??"—"} hint={mostSold?`${mostSold.units} un`:"sem vendas"}/><Metric label="Margem mais baixa" value={lowestMargin?.name??"—"} hint={lowestMargin?percent(lowestMargin.marginPercent):"sem vendas"}/></div><div className="mt-5 space-y-2">{products.slice(0,8).map((p)=><div key={p.productId} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{p.name}</strong><span className="font-bold">{money(p.contribution)}</span></div><p className="mt-1 text-xs text-caramel">{p.units} un · receita {money(p.revenue)} · custo {money(p.productCost)} · entrega {money(p.allocatedDelivery)} · margem {percent(p.marginPercent)}</p></div>)}</div></div>

  <div className="nat-card"><div className="flex items-center gap-3"><Users size={20}/><h2 className="section-title">Clientes</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Com compra paga" value={String(paidCustomers.length)} hint={`${overview.recurrent} recorrentes`}/><Metric label="Taxa de recompra" value={percent(overview.repurchaseRate)} hint={`${overview.inactive} em risco/inativos`}/></div><div className="mt-5 space-y-2">{[...paidCustomers].sort((a,b)=>b.contribution-a.contribution).slice(0,8).map((c)=><div key={c.customer.id} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{c.customer.name}</strong><span className="rounded-full bg-soft px-2 py-1 text-xs font-bold">{c.segment}</span></div><p className="mt-1 text-xs text-caramel">{c.orders} pedido(s) · {money(c.totalSpent)} · contribuição {money(c.contribution)} · favorito: {c.favoriteProduct??"—"}</p></div>)}</div></div></div>

  <div className="grid gap-6 lg:grid-cols-2"><div className="nat-card"><h2 className="section-title">Canais e origens</h2><div className="mt-4 space-y-2">{channels.length?channels.map((row)=><div key={row.channel} className="flex items-center justify-between gap-4 rounded-2xl bg-soft p-3"><div><strong>{saleChannelLabel[row.channel]}</strong><p className="text-xs text-caramel">{row.orders} pedido(s) · ticket {money(row.ticket)}</p></div><span className="font-bold">{money(row.revenue)}</span></div>):<p className="text-sm text-caramel">Ainda não há canal informado nas vendas.</p>}</div><h3 className="mt-6 font-bold">Origem dos clientes</h3><div className="mt-3 space-y-2">{overview.sourceBreakdown.map((row)=><div key={row.source} className="flex items-center justify-between rounded-xl border border-nat p-3"><span>{row.source}</span><span className="text-sm font-bold">{row.customers} cliente(s) · {money(row.revenue)}</span></div>)}</div></div>
  <div className="nat-card"><h2 className="section-title">Recompra e mix</h2><p className="mt-2 text-sm text-caramel">{second.days===null?"Ainda não há segunda compra identificada.":`Tempo médio até a 2ª compra: ${second.days.toFixed(1)} dia(s)${second.baseSmall?" · base pequena":""}.`}</p><div className="mt-4 space-y-2">{cohorts.map((c)=><div key={c.cohort} className="rounded-xl bg-soft p-3"><strong>{c.cohort}</strong><p className="text-xs text-caramel">{c.customers} cliente(s) · {percent(c.repurchaseRate)} recompraram</p></div>)}</div><h3 className="mt-6 font-bold">Produtos comprados juntos</h3><div className="mt-3 space-y-2">{pairs.length?pairs.slice(0,6).map((p)=><div key={`${p.a}-${p.b}`} className="rounded-xl border border-nat p-3"><strong>{p.a} + {p.b}</strong><p className="text-xs text-caramel">{p.count} pedidos juntos</p></div>):<p className="text-sm text-caramel">Dados insuficientes: a combinação precisa aparecer em pelo menos 2 pedidos.</p>}</div></div></div>

  <div className="grid gap-6 lg:grid-cols-2"><div className="nat-card"><div className="flex items-center gap-3"><Boxes size={20}/><h2 className="section-title">Quanto ainda dá para produzir?</h2></div><p className="mt-1 text-sm text-caramel">Só calculamos quando todos os insumos de produção necessários estão com estoque controlado.</p><div className="mt-4 space-y-2">{production.map((row)=><div key={row.name} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{row.name}</strong><span className="font-bold">{row.units===null?"Não calculável":`${row.units} un`}</span></div>{row.missing.length>0&&<p className="mt-1 text-xs text-caramel">Falta controlar: {row.missing.join(", ")}</p>}</div>)}</div></div>
  <div className="nat-card"><div className="flex items-center gap-3"><PackageSearch size={20}/><h2 className="section-title">Compras e variação de preço</h2></div>{purchaseError&&<p className="mt-3 text-sm text-red-700">Não foi possível carregar compras: {purchaseError}</p>}<div className="mt-4 space-y-2">{purchases.slice(0,10).map((row)=><div key={row.supplyId} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{row.name}</strong>{row.variation===null?<span className="text-xs text-caramel">1ª referência</span>:<span className={`flex items-center gap-1 text-xs font-bold ${row.variation>0?"text-red-700":"text-emerald-700"}`}>{row.variation>0?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {percent(Math.abs(row.variation))}</span>}</div><p className="mt-1 text-xs text-caramel">{row.purchases} compra(s) · total {money(row.totalSpent)} · custo-base atual {money(row.currentUnitCost)}/unidade-base</p></div>)}</div></div></div>

  <div className="nat-card"><h2 className="section-title">Promoções</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Pedidos com desconto" value={String(promos.discountedOrders)} hint="comparados ao preço atual de tabela"/><Metric label="Desconto concedido" value={money(promos.discountValue)} hint="diferença total"/><Metric label="Contribuição dessas vendas" value={money(promos.contribution)} hint="resultado variável"/></div><p className="mt-3 text-xs text-caramel">O histórico de custo e contribuição usa snapshots congelados. O valor de “desconto concedido” compara com a tabela atual e serve como referência comercial.</p></div>
  </section>;
}
