import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, PackageSearch, TrendingDown, TrendingUp, Users } from "lucide-react";
import { dashboardNumbers, money, percent, saleChannelLabel, type NatState } from "@/domain/nat";
import type { InventorySnapshot } from "@/domain/inventory";
import { loadSupplyPurchaseInsights, type PurchaseInsight } from "@/data/intelligence-repository";
import { loadBusinessIntelligenceSnapshot, type BiDrilldownDimension, type BiProduct, type BusinessIntelligenceSnapshot } from "@/data/business-intelligence-repository";
import { Metric } from "./Views";
import { IntelligenceDrilldownDialog } from "./IntelligenceDrilldownDialog";

type DrilldownRequest={dimension:BiDrilldownDimension;key:string|null;title:string};
function DetailButton({onClick}:{onClick:()=>void}){return <button type="button" className="text-button text-xs" onClick={onClick}>Ver composição</button>;}
function ProductFact({label,product,value,hint,onOpen}:{label:string;product:BiProduct|undefined;value:string;hint:string;onOpen?:()=>void}){return <div className="rounded-2xl border border-nat p-4"><p className="text-xs font-bold uppercase tracking-wider text-caramel">{label}</p><p className="mt-2 text-lg font-bold">{product?.name??"Ainda sem vendas"}</p><p className="mt-1 text-sm text-caramel">{product?value:hint}</p>{product&&onOpen&&<div className="mt-2"><DetailButton onClick={onOpen}/></div>}</div>;}
function stockLabel(row:PurchaseInsight){if(!row.baseUnit)return "estoque não controlado";const digits=row.baseUnit==="unit"?0:1;return `${new Intl.NumberFormat("pt-BR",{maximumFractionDigits:digits}).format(row.stockQuantity)} ${row.baseUnit==="unit"?"un":row.baseUnit} em estoque`;}
function dateLabel(value:string){if(!value)return "—";return new Intl.DateTimeFormat("pt-BR").format(new Date(`${value}T12:00:00`));}

export function IntelligenceView({state,inventory,businessId}:{state:NatState;inventory:InventorySnapshot;businessId:string|null}){
  const[purchases,setPurchases]=useState<PurchaseInsight[]>([]);const[purchaseError,setPurchaseError]=useState<string|null>(null);
  const[bi,setBi]=useState<BusinessIntelligenceSnapshot|null>(null);const[biError,setBiError]=useState<string|null>(null);const[drilldown,setDrilldown]=useState<DrilldownRequest|null>(null);
  const portfolioSignature=useMemo(()=>state.products.map((product)=>`${product.id}:${product.name}:${product.available}`).sort().join("|"),[state.products]);
  useEffect(()=>{let active=true;if(!businessId){setPurchases([]);setPurchaseError(null);return()=>{active=false};}setPurchaseError(null);void loadSupplyPurchaseInsights(businessId).then((values)=>{if(active)setPurchases(values);}).catch((error)=>{if(active)setPurchaseError(error instanceof Error?error.message:"Não foi possível carregar compras.");});return()=>{active=false};},[businessId,state.supplies.length,inventory.movements.length]);
  useEffect(()=>{let active=true;if(!businessId){setBi(null);setBiError(null);return()=>{active=false};}setBiError(null);void loadBusinessIntelligenceSnapshot(businessId,{refresh:true}).then((snapshot)=>{if(active)setBi(snapshot);}).catch((error)=>{if(active)setBiError(error instanceof Error?error.message:"Não foi possível carregar a inteligência completa.");});return()=>{active=false};},[businessId,state.sales.length,portfolioSignature]);
  const numbers=useMemo(()=>dashboardNumbers(state),[state]);
  const products=(bi?.products??[]).filter((item)=>item.units>0||item.billed>0);const channels=bi?.channels??[];const origins=bi?.origins??[];const pairs=bi?.pairs??[];const second=bi?.secondPurchase??{sample:0,days:null,baseSmall:true};const promos=bi?.promotions??{discountedOrders:0,discountValue:0,contribution:0,investedCost:0,roiPercent:null};const readiness=bi?.readiness??{ready:false,salesCount:0,distinctSalesDays:0,minimumSales:10,minimumDays:7,missingSales:10,missingDays:7};
  const trusted=readiness.ready;const bestBilled=[...products].sort((a,b)=>b.billed-a.billed)[0];const bestContribution=[...products].sort((a,b)=>b.contribution-a.contribution)[0];const mostSold=[...products].sort((a,b)=>b.units-a.units)[0];const lowestMargin=[...products].sort((a,b)=>a.marginPercent-b.marginPercent)[0];const overview=bi?.overview;const inactiveRate=overview?.customersWithOrders?overview.inactive/overview.customersWithOrders*100:0;
  const open=(dimension:BiDrilldownDimension,key:string|null,title:string)=>setDrilldown({dimension,key,title});
  if(!bi&&!biError)return <div className="nat-card" role="status">Organizando seus indicadores...</div>;
  return <section className="space-y-6">
    <div><p className="eyebrow">Decisões com os dados da NAT</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Inteligência</h1><p className="mt-2 max-w-3xl text-caramel">Aqui você reúne vendas, clientes, produtos e compras para entender onde o negócio está indo bem e onde vale olhar com mais cuidado.</p>{biError&&<div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{biError}</div>}{!trusted&&!biError&&<div className="mt-4 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900" data-testid="bi-patterns-locked"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><span><strong>A NAT ainda está conhecendo o ritmo das vendas.</strong> Os números já podem ser acompanhados normalmente; com mais dias de histórico, comparações de comportamento ficam mais seguras.</span></div>}</div>

    <div className="nat-card"><div className="flex items-center gap-3"><BarChart3 size={20}/><div><p className="eyebrow">Saúde do negócio</p><h2 className="section-title">O mês em uma leitura</h2></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Metric label="Faturamento" value={money(numbers.billed)} hint={`${numbers.orderCount} pedidos · ticket médio ${money(numbers.orderCount?numbers.billed/numbers.orderCount:0)}`}/><Metric label="Recebido" value={money(numbers.receivedCash)} hint={`${numbers.paidOrders} pedidos pagos`}/><Metric label="A receber" value={money(numbers.receivables)} hint={`${numbers.pendingOrders} pedidos pendentes`}/><Metric label="Resultado das vendas" value={money(numbers.contribution)} hint={`margem média ${percent(numbers.billed?numbers.contribution/numbers.billed*100:0)}`}/></div><div className="mt-6 border-t border-nat pt-5"><h3 className="font-bold">Promoções</h3><p className="mt-1 text-sm text-caramel">Veja quanto os descontos movimentaram e quanto sobrou depois dos custos.</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Pedidos com desconto" value={String(promos.discountedOrders)} hint="vendas com preço reduzido"/><Metric label="Desconto concedido" value={money(promos.discountValue)} hint="valor que deixou de entrar"/><Metric label="Resultado das promoções" value={money(promos.contribution)} hint="o que sobrou após os custos"/><Metric label="ROI das promoções" value={promos.roiPercent==null?"—":percent(promos.roiPercent)} hint="retorno sobre o custo dessas vendas"/></div>{businessId&&promos.discountedOrders>0&&<div className="mt-3"><DetailButton onClick={()=>open("promotion","all","Promoções")}/></div>}</div></div>

    <div className="nat-card"><h2 className="section-title">Produtos</h2><p className="mt-1 text-sm text-caramel">Os destaques abaixo acompanham o Portfólio atual e são alimentados pelas vendas registradas.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><ProductFact label="Maior faturamento" product={bestBilled} value={money(bestBilled?.billed??0)} hint="Quando houver vendas, o destaque aparece aqui." onOpen={bestBilled&&businessId?()=>open("product",bestBilled.productId,`Produto · ${bestBilled.name}`):undefined}/><ProductFact label="Maior contribuição" product={bestContribution} value={money(bestContribution?.contribution??0)} hint="Quando houver vendas, o destaque aparece aqui." onOpen={bestContribution&&businessId?()=>open("product",bestContribution.productId,`Produto · ${bestContribution.name}`):undefined}/><ProductFact label="Mais vendido" product={mostSold} value={`${mostSold?.units??0} un`} hint="Quando houver vendas, o destaque aparece aqui." onOpen={mostSold&&businessId?()=>open("product",mostSold.productId,`Produto · ${mostSold.name}`):undefined}/><ProductFact label="Margem mais baixa" product={lowestMargin} value={percent(lowestMargin?.marginPercent??0)} hint="Quando houver vendas, o destaque aparece aqui." onOpen={lowestMargin&&businessId?()=>open("product",lowestMargin.productId,`Produto · ${lowestMargin.name}`):undefined}/></div></div>

    <div className="nat-card"><div className="flex items-center gap-3"><Users size={20}/><h2 className="section-title">Clientes</h2></div><p className="mt-1 text-sm text-caramel">Um resumo da relação com quem já comprou, sem repetir a lista de clientes desta área.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Total de clientes" value={String(overview?.customersWithOrders??0)} hint="com pelo menos uma compra"/><Metric label="Recompra" value={percent(overview?.repurchaseRate??0)} hint={`${overview?.recurrent??0} clientes compraram novamente`}/><Metric label="Não compraram mais" value={percent(inactiveRate)} hint={`${overview?.inactive??0} sem compra há 30+ dias`}/></div><div className="mt-6 rounded-2xl bg-soft p-4"><h3 className="font-bold">Recompra e mix</h3>{trusted?<><p className="mt-2 text-sm text-caramel">{second.days===null?"Ainda não há uma segunda compra para comparar.":`Em média, a segunda compra acontece em ${second.days.toFixed(1)} dia(s).`}</p><div className="mt-3 flex flex-wrap gap-2">{pairs.length?pairs.slice(0,4).map((pair)=><span key={`${pair.a}-${pair.b}`} className="rounded-full bg-white px-3 py-2 text-xs font-bold">{pair.a} + {pair.b} · {pair.count}x</span>):<span className="text-sm text-caramel">Ainda não há combinações repetidas de produtos.</span>}</div></>:<p className="mt-2 text-sm text-caramel">As recompras já estão sendo registradas. Conforme o histórico cresce, a NAT passa a comparar frequência e combinações de produtos com mais segurança.</p>}</div></div>

    <div className="nat-card"><h2 className="section-title">Canais e origens</h2><p className="mt-1 text-sm text-caramel">Tudo vem das vendas registradas: por onde o pedido chegou e de onde vieram os clientes.</p><h3 className="mt-5 font-bold">Canais de venda</h3><div className="mt-3 space-y-2">{channels.length?channels.map((row)=><div key={row.channel} className="rounded-2xl bg-soft p-3"><div className="flex items-center justify-between gap-4"><div><strong>{saleChannelLabel[row.channel]}</strong><p className="text-xs text-caramel">{row.orders} pedido(s) · ticket {money(row.ticket)} · recebido {money(row.received)}</p></div><span className="font-bold">{money(row.billed)}</span></div>{businessId&&<DetailButton onClick={()=>open("channel",row.channel,`Canal · ${saleChannelLabel[row.channel]}`)}/>}</div>):<p className="text-sm text-caramel">Ainda não há canal informado nas vendas.</p>}</div><h3 className="mt-6 font-bold">Origem dos clientes</h3><div className="mt-3 space-y-2">{origins.length?origins.map((row)=><div key={row.source} className="rounded-xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><span>{row.source}</span><span className="text-sm font-bold">{row.customers} cliente(s) · {money(row.billed)}</span></div><p className="mt-1 text-xs text-caramel">{row.orders} pedido(s) · {row.recurring} recompra(s) · resultado {money(row.contribution)}</p>{businessId&&<DetailButton onClick={()=>open("origin",row.source,`Origem · ${row.source}`)}/>}</div>):<p className="text-sm text-caramel">Ainda não há origem informada nos clientes com venda.</p>}</div></div>

    <div className="nat-card"><div className="flex items-center gap-3"><PackageSearch size={20}/><div><p className="eyebrow">Compras e estoque</p><h2 className="section-title">Compras e variação de preço</h2></div></div><p className="mt-2 text-sm text-caramel">Acompanhe como o preço muda e abra cada item para ver as marcas já compradas e o saldo que ainda existe no estoque.</p>{purchaseError&&<p className="mt-3 text-sm text-red-700" role="alert">{purchaseError}</p>}<div className="mt-4 space-y-3">{purchases.length?purchases.map((row)=><details key={row.groupId} className="rounded-2xl border border-nat p-4"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{row.name}</strong><p className="mt-1 text-xs text-caramel">{row.purchases} compra(s) · total gasto {money(row.totalSpent)} · {stockLabel(row)}</p></div>{row.variation===null?<span className="rounded-full bg-soft px-3 py-1 text-xs font-bold text-caramel">1ª referência</span>:<span className={`flex items-center gap-1 rounded-full bg-soft px-3 py-1 text-xs font-bold ${row.variation>0?"text-red-700":"text-emerald-700"}`}>{row.variation>0?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {percent(Math.abs(row.variation))}</span>}</div></summary><div className="mt-4 grid gap-3 md:grid-cols-2">{row.brands.map((brand)=><div key={brand.supplyId} className="rounded-xl bg-soft p-3"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{brand.name}</strong>{brand.current&&<span className="rounded-full bg-white px-2 py-1 text-[11px] font-bold">Marca atual</span>}</div><p className="mt-2 text-xs leading-5 text-caramel">{brand.purchases} compra(s) · última em {dateLabel(brand.lastDate)} · último pacote {money(brand.lastPackagePrice)}</p><p className="mt-1 text-xs text-caramel">Total gasto {money(brand.totalSpent)}{brand.stockQuantity==null?" · estoque não controlado":` · saldo ${new Intl.NumberFormat("pt-BR",{maximumFractionDigits:1}).format(brand.stockQuantity)} ${brand.baseUnit==="unit"?"un":brand.baseUnit??""}`}</p></div>)}</div></details>):<p className="rounded-2xl border border-dashed border-nat p-4 text-sm text-caramel">Ainda não há compras registradas para comparar.</p>}</div></div>

    {drilldown&&businessId&&<IntelligenceDrilldownDialog businessId={businessId} dimension={drilldown.dimension} metricKey={drilldown.key} title={drilldown.title} onClose={()=>setDrilldown(null)}/>} 
  </section>;
}