import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Boxes, PackageSearch, TrendingDown, TrendingUp, Users } from "lucide-react";
import { dashboardNumbers, money, percent, saleChannelLabel, type NatState, type Unit } from "@/domain/nat";
import type { InventorySnapshot } from "@/domain/inventory";
import { loadSupplyPurchaseInsights, type PurchaseInsight } from "@/data/intelligence-repository";
import { loadBusinessIntelligenceSnapshot, type BusinessIntelligenceSnapshot } from "@/data/business-intelligence-repository";
import { Metric } from "./Views";

function baseQty(q:number,u:Unit){if(u==="kg")return q*1000;if(u==="l")return q*1000;return q;}
function producible(state:NatState,inventory:InventorySnapshot){
  return state.products.filter((p)=>p.available!==false&&p.recipe.length>0).map((product)=>{
    const missing:string[]=[];let maxBatches=Number.POSITIVE_INFINITY;
    for(const item of product.recipe){const supply=state.supplies.find((s)=>s.id===item.supplyId);if(!supply||supply.category==="packaging")continue;const tracked=inventory.items.find((x)=>x.kind==="supply"&&x.itemId===item.supplyId&&x.tracked);if(!tracked){missing.push(supply?.name??"Insumo");continue;}let required=baseQty(item.quantity,item.unit);if(supply.category==="ingredient")required*=1+Math.max(0,product.lossPercent)/100;if(required>0)maxBatches=Math.min(maxBatches,tracked.currentQuantity/required);}
    if(missing.length)return{name:product.name,units:null,missing};if(!Number.isFinite(maxBatches))return{name:product.name,units:null,missing:["Configure os insumos de produção"]};return{name:product.name,units:Math.max(0,Math.floor(maxBatches*product.batchYield)),missing:[]};
  });
}

export function IntelligenceView({state,inventory,businessId}:{state:NatState;inventory:InventorySnapshot;businessId:string|null}){
  const [purchases,setPurchases]=useState<PurchaseInsight[]>([]);const [purchaseError,setPurchaseError]=useState<string|null>(null);
  const [bi,setBi]=useState<BusinessIntelligenceSnapshot|null>(null);const [biError,setBiError]=useState<string|null>(null);
  useEffect(()=>{let active=true;if(!businessId){setPurchases([]);setPurchaseError(null);return()=>{active=false};}setPurchaseError(null);void loadSupplyPurchaseInsights(businessId,state.supplies).then((rows)=>{if(active)setPurchases(rows);}).catch((error)=>{if(active)setPurchaseError(error instanceof Error?error.message:"Não foi possível carregar compras.");});return()=>{active=false};},[businessId,state.supplies]);
  useEffect(()=>{let active=true;if(!businessId){setBi(null);setBiError(null);return()=>{active=false};}setBiError(null);void loadBusinessIntelligenceSnapshot(businessId).then((snapshot)=>{if(active)setBi(snapshot);}).catch((error)=>{if(active)setBiError(error instanceof Error?error.message:"Não foi possível carregar a inteligência completa.");});return()=>{active=false};},[businessId,state.sales.length]);
  const numbers=useMemo(()=>dashboardNumbers(state),[state]);const production=useMemo(()=>producible(state,inventory),[state,inventory]);
  const products=bi?.products??[];const customers=bi?.customers??[];const channels=bi?.channels??[];const pairs=bi?.pairs??[];const cohorts=bi?.cohorts??[];const second=bi?.secondPurchase??{sample:0,days:null,baseSmall:true};const promos=bi?.promotions??{discountedOrders:0,discountValue:0,contribution:0};const readiness=bi?.readiness??{ready:false,salesCount:0,distinctSalesDays:0,minimumSales:10,minimumDays:7,missingSales:10,missingDays:7};
  const bestBilled=[...products].sort((a,b)=>b.billed-a.billed)[0];const bestContribution=[...products].sort((a,b)=>b.contribution-a.contribution)[0];const mostSold=[...products].sort((a,b)=>b.units-a.units)[0];const lowestMargin=[...products].sort((a,b)=>a.marginPercent-b.marginPercent)[0];const baseSmall=!readiness.ready;
  const sources=useMemo(()=>{const map=new Map<string,{source:string;customers:number;billed:number;orders:number;recurring:number}>();for(const row of customers){const source=row.source?.trim()||"Não informado";const current=map.get(source)??{source,customers:0,billed:0,orders:0,recurring:0};current.customers+=1;current.billed+=row.billed;current.orders+=row.orders;if(row.recurring)current.recurring+=1;map.set(source,current);}return[...map.values()].sort((a,b)=>b.billed-a.billed);},[customers]);
  if(!bi&&!biError)return <div className="nat-card" role="status">Carregando indicadores completos do histórico...</div>;
  return <section className="space-y-6"><div><p className="eyebrow">Decisões com os dados da NAT</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Inteligência</h1><p className="mt-2 max-w-3xl text-caramel">Indicadores vitalícios são calculados pelo Lovable Cloud sobre todo o histórico, independentemente do recorte recente carregado no navegador.</p>{biError&&<div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{biError}</div>}{baseSmall&&!biError&&<div className="mt-4 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><span><strong>Base pequena:</strong> use os indicadores como sinais iniciais. A liberação exige pelo menos {readiness.minimumSales} vendas em {readiness.minimumDays} dias distintos.</span></div>}</div>

  <div className="nat-card"><div className="flex items-center gap-3"><BarChart3 size={20}/><div><p className="eyebrow">Saúde do negócio</p><h2 className="section-title">O mês em uma leitura</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Faturamento" value={money(numbers.billed)} hint={`${numbers.orderCount} pedidos concluídos`}/><Metric label="Recebido" value={money(numbers.receivedCash)} hint={`${numbers.paidOrders} pagos`}/><Metric label="A receber" value={money(numbers.receivables)} hint={`${numbers.pendingOrders} pendentes`}/><Metric label="Contribuição" value={money(numbers.contribution)} hint="após custos variáveis"/><Metric label="Margem média" value={percent(numbers.billed?numbers.contribution/numbers.billed*100:0)} hint="sobre o faturamento"/><Metric label="Ticket médio" value={money(numbers.orderCount?numbers.billed/numbers.orderCount:0)} hint="faturamento por pedido"/></div></div>

  <div className="grid gap-6 lg:grid-cols-2"><div className="nat-card"><h2 className="section-title">Produtos</h2><p className="mt-1 text-sm text-caramel">Rentabilidade baseada nos snapshots congelados de todo o histórico.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Maior faturamento" value={bestBilled?.name??"—"} hint={bestBilled?money(bestBilled.billed):"sem vendas"}/><Metric label="Maior contribuição" value={bestContribution?.name??"—"} hint={bestContribution?money(bestContribution.contribution):"sem vendas"}/><Metric label="Mais vendido" value={mostSold?.name??"—"} hint={mostSold?`${mostSold.units} un`:"sem vendas"}/><Metric label="Margem mais baixa" value={lowestMargin?.name??"—"} hint={lowestMargin?percent(lowestMargin.marginPercent):"sem vendas"}/></div><div className="mt-5 space-y-2">{products.slice(0,8).map((p)=><div key={p.productId} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{p.name}</strong><span className="font-bold">{money(p.contribution)}</span></div><p className="mt-1 text-xs text-caramel">{p.units} un · faturamento {money(p.billed)} · custo {money(p.productCost)} · entrega {money(p.allocatedDelivery)} · margem {percent(p.marginPercent)}</p></div>)}</div></div>

  <div className="nat-card"><div className="flex items-center gap-3"><Users size={20}/><h2 className="section-title">Clientes</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Com compra" value={String(bi?.overview.customersWithOrders??0)} hint={`${bi?.overview.recurrent??0} recorrentes`}/><Metric label="Taxa de recompra" value={percent(bi?.overview.repurchaseRate??0)} hint={`${bi?.overview.inactive??0} em risco/inativos`}/></div><div className="mt-5 space-y-2">{[...customers].sort((a,b)=>b.contribution-a.contribution).slice(0,8).map((c)=><div key={c.customerId} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{c.name}</strong><span className="rounded-full bg-soft px-2 py-1 text-xs font-bold">{c.segment}</span></div><p className="mt-1 text-xs text-caramel">{c.orders} pedido(s) · faturamento {money(c.billed)} · contribuição {money(c.contribution)} · favorito: {c.favoriteProduct??"—"}</p></div>)}</div></div></div>

  <div className="grid gap-6 lg:grid-cols-2"><div className="nat-card"><h2 className="section-title">Canais e origens</h2><div className="mt-4 space-y-2">{channels.length?channels.map((row)=><div key={row.channel} className="flex items-center justify-between gap-4 rounded-2xl bg-soft p-3"><div><strong>{saleChannelLabel[row.channel]}</strong><p className="text-xs text-caramel">{row.orders} pedido(s) · ticket {money(row.ticket)} · recebido {money(row.received)}</p></div><span className="font-bold">{money(row.billed)}</span></div>):<p className="text-sm text-caramel">Ainda não há canal informado nas vendas.</p>}</div><h3 className="mt-6 font-bold">Origem dos clientes</h3><div className="mt-3 space-y-2">{sources.map((row)=><div key={row.source} className="flex items-center justify-between rounded-xl border border-nat p-3"><span>{row.source}</span><span className="text-sm font-bold">{row.customers} cliente(s) · {money(row.billed)}</span></div>)}</div></div>
  <div className="nat-card"><h2 className="section-title">Recompra e mix</h2><p className="mt-2 text-sm text-caramel">{second.days===null?"Ainda não há segunda compra identificada.":`Tempo médio até a 2ª compra: ${second.days.toFixed(1)} dia(s)${second.baseSmall?" · base pequena":""}.`}</p><div className="mt-4 space-y-2">{cohorts.map((c)=><div key={c.cohort} className="rounded-xl bg-soft p-3"><strong>{c.cohort}</strong><p className="text-xs text-caramel">{c.customers} cliente(s) · {percent(c.repurchaseRate)} recompraram</p></div>)}</div><h3 className="mt-6 font-bold">Produtos comprados juntos</h3><div className="mt-3 space-y-2">{pairs.length?pairs.slice(0,6).map((p)=><div key={`${p.a}-${p.b}`} className="rounded-xl border border-nat p-3"><strong>{p.a} + {p.b}</strong><p className="text-xs text-caramel">{p.count} pedidos juntos</p></div>):<p className="text-sm text-caramel">Dados insuficientes: a combinação precisa aparecer em pelo menos 2 pedidos.</p>}</div></div></div>

  <div className="grid gap-6 lg:grid-cols-2"><div className="nat-card"><div className="flex items-center gap-3"><Boxes size={20}/><h2 className="section-title">Quanto ainda dá para produzir?</h2></div><p className="mt-1 text-sm text-caramel">Só calculamos quando todos os insumos de produção necessários estão com estoque controlado.</p><div className="mt-4 space-y-2">{production.map((row)=><div key={row.name} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{row.name}</strong><span className="font-bold">{row.units===null?"Não calculável":`${row.units} un`}</span></div>{row.missing.length>0&&<p className="mt-1 text-xs text-caramel">Falta controlar: {row.missing.join(", ")}</p>}</div>)}</div></div>
  <div className="nat-card"><div className="flex items-center gap-3"><PackageSearch size={20}/><h2 className="section-title">Compras e variação de preço</h2></div>{purchaseError&&<p className="mt-3 text-sm text-red-700">{purchaseError}</p>}<div className="mt-4 space-y-2">{purchases.slice(0,10).map((row)=><div key={row.supplyId} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{row.name}</strong>{row.variation===null?<span className="text-xs text-caramel">1ª referência</span>:<span className={`flex items-center gap-1 text-xs font-bold ${row.variation>0?"text-red-700":"text-emerald-700"}`}>{row.variation>0?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {percent(Math.abs(row.variation))}</span>}</div><p className="mt-1 text-xs text-caramel">{row.purchases} compra(s) · total {money(row.totalSpent)} · custo-base atual {money(row.currentUnitCost)}/unidade-base</p></div>)}</div></div></div>

  <div className="nat-card"><h2 className="section-title">Promoções</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Pedidos com desconto" value={String(promos.discountedOrders)} hint="contra o preço congelado na venda"/><Metric label="Desconto concedido" value={money(promos.discountValue)} hint="diferença histórica preservada"/><Metric label="Contribuição dessas vendas" value={money(promos.contribution)} hint="resultado variável"/></div><p className="mt-3 text-xs text-caramel">O preço de tabela, o custo e a contribuição ficam congelados como snapshots. Alterar o preço de um produto hoje não reescreve o histórico de promoções.</p></div>
  </section>;
}
