import { useEffect, useState } from "react";
import { AlertTriangle, Boxes, TrendingDown, Users } from "lucide-react";
import { money, type NatState } from "@/domain/nat";
import type { InventorySnapshot } from "@/domain/inventory";
import { loadBusinessIntelligenceSnapshot, type BusinessIntelligenceSnapshot } from "@/data/business-intelligence-repository";
import { IntelligenceView } from "./IntelligenceView";
import { RoiOverview } from "./RoiOverview";

export function IntelligenceWorkbench({state,inventory,businessId}:{state:NatState;inventory:InventorySnapshot;businessId:string|null}){
  const[bi,setBi]=useState<BusinessIntelligenceSnapshot|null>(null);
  useEffect(()=>{let active=true;if(!businessId){setBi(null);return()=>{active=false};}void loadBusinessIntelligenceSnapshot(businessId,{refresh:true}).then((value)=>{if(active)setBi(value);}).catch(()=>{if(active)setBi(null);});return()=>{active=false};},[businessId,state.sales.length,state.products.length]);
  const readiness=bi?.readiness;const trusted=readiness?.ready===true;const lowest=[...(bi?.products??[])].filter((item)=>item.units>0).sort((a,b)=>a.marginPercent-b.marginPercent)[0];const lowStock=inventory.items.filter((item)=>item.tracked&&item.lowStock);
  const remaining=readiness?[readiness.missingSales>0?`${readiness.missingSales} venda(s)`:null,readiness.missingDays>0?`${readiness.missingDays} dia(s) diferente(s)`:null].filter(Boolean).join(" e "):"";
  return <section className="space-y-5">
    <div><p className="eyebrow">Análises</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">O que merece atenção</h1><p className="mt-2 max-w-3xl text-caramel">Um resumo simples do que vale acompanhar agora. A NAT já mostra o que está acontecendo e, conforme o histórico cresce, passa a reconhecer padrões com mais segurança.</p></div>
    {readiness&&!readiness.ready&&<div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900" data-testid="bi-small-base"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><span><strong>A NAT ainda está conhecendo o ritmo das vendas.</strong> Você já pode acompanhar os números normalmente{remaining?`; com mais ${remaining}, as comparações de comportamento ficam mais confiáveis.`:"; as comparações de comportamento serão liberadas assim que houver histórico suficiente."}</span></div>}
    {lowStock.length>0&&<div className="nat-card"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-rose-soft"><Boxes size={18}/></span><div className="min-w-0 flex-1"><h2 className="text-lg font-bold">{lowStock.length} {lowStock.length===1?"item precisa":"itens precisam"} de reposição</h2><p className="mt-1 text-sm leading-6 text-caramel">Estes itens chegaram ao estoque mínimo. Vale conferir antes das próximas produções.</p><div className="mt-3 flex flex-wrap gap-2">{lowStock.slice(0,8).map((item)=><span key={`${item.kind}-${item.itemId}`} className="rounded-full bg-soft px-3 py-2 text-xs font-bold">{item.name}</span>)}{lowStock.length>8&&<span className="rounded-full bg-soft px-3 py-2 text-xs font-bold">+{lowStock.length-8} itens</span>}</div></div></div></div>}
    {trusted&&(bi?.overview.inactive||lowest)&&<div className="grid gap-3 md:grid-cols-2">{bi?.overview.inactive?<article className="nat-card"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-rose-soft"><Users size={18}/></span><div><h2 className="font-bold">Clientes que não voltaram recentemente</h2><p className="mt-1 text-sm leading-6 text-caramel">{bi.overview.inactive} cliente(s) estão há 30 dias ou mais sem uma nova compra.</p></div></div></article>:null}{lowest?<article className="nat-card"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-rose-soft"><TrendingDown size={18}/></span><div><h2 className="font-bold">{lowest.name} merece atenção na margem</h2><p className="mt-1 text-sm leading-6 text-caramel">Até agora, é o produto com menor margem. Resultado acumulado: {money(lowest.contribution)}.</p></div></div></article>:null}</div>}
    {!lowStock.length&&!trusted&&<div className="nat-card"><p className="font-bold">Nada urgente por aqui.</p><p className="mt-1 text-sm text-caramel">Continue registrando vendas e estoque; a NAT organiza os sinais importantes conforme eles aparecem.</p></div>}
    <RoiOverview snapshot={bi}/>
    <details className="nat-card"><summary className="cursor-pointer font-bold">Ver todos os indicadores</summary><div className="mt-6 border-t border-nat pt-6"><IntelligenceView state={state} inventory={inventory} businessId={businessId}/></div></details>
  </section>;
}
