import { useEffect, useState } from "react";
import { AlertTriangle, Boxes, TrendingDown, Users } from "lucide-react";
import { money, type NatState } from "@/domain/nat";
import type { InventorySnapshot } from "@/domain/inventory";
import { loadBusinessIntelligenceSnapshot, type BusinessIntelligenceSnapshot } from "@/data/business-intelligence-repository";
import { HelpTip } from "./Feedback";
import { IntelligenceView } from "./IntelligenceView";
import { RoiOverview } from "./RoiOverview";

export function IntelligenceWorkbench({state,inventory,businessId}:{state:NatState;inventory:InventorySnapshot;businessId:string|null}){
  const[bi,setBi]=useState<BusinessIntelligenceSnapshot|null>(null);
  useEffect(()=>{let active=true;if(!businessId){setBi(null);return()=>{active=false};}void loadBusinessIntelligenceSnapshot(businessId).then((value)=>{if(active)setBi(value);}).catch(()=>{if(active)setBi(null);});return()=>{active=false};},[businessId,state.sales.length]);
  const readiness=bi?.readiness;const trusted=readiness?.ready===true;const lowest=[...(bi?.products??[])].filter((item)=>item.units>0).sort((a,b)=>a.marginPercent-b.marginPercent)[0];const lowStock=inventory.items.filter((item)=>item.tracked&&item.lowStock);
  const alerts=[
    lowStock.length?{icon:<Boxes size={18}/>,title:`${lowStock.length} item(ns) com estoque baixo`,text:`Priorize ${lowStock.slice(0,2).map((item)=>item.name).join(" e ")}.`}:null,
    trusted&&bi?.overview.inactive?{icon:<Users size={18}/>,title:`${bi.overview.inactive} cliente(s) sem comprar há 30+ dias`,text:"A base mínima foi atingida; abra os indicadores para revisar exatamente quais clientes compõem este alerta."}:null,
    trusted&&lowest?{icon:<TrendingDown size={18}/>,title:`${lowest.name} tem a margem mais baixa`,text:`Resultado variável: ${money(lowest.contribution)}. A base mínima foi atingida; valide a composição antes de agir.`}:null,
  ].filter(Boolean) as {icon:React.ReactNode;title:string;text:string}[];
  return <section className="space-y-5"><div><p className="eyebrow">Análises</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">O que merece atenção</h1><p className="mt-2 max-w-3xl text-caramel">Fatos operacionais aparecem sempre. Recomendações de clientes, margem e comportamento só são liberadas quando a amostra mínima é atingida.</p></div>{readiness&&!readiness.ready&&<div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900" data-testid="bi-small-base"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><span><strong>Padrões ainda bloqueados:</strong> faltam {readiness.missingSales} venda(s) e {readiness.missingDays} dia(s) distinto(s) para atingir {readiness.minimumSales} vendas em {readiness.minimumDays} dias. Até lá, a NAT mostra fatos observados, mas não recomenda decisão comercial.</span></div>}<div className="grid gap-3 lg:grid-cols-3">{alerts.length?alerts.map((item)=><article key={item.title} className="nat-card"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-rose-soft">{item.icon}</span><div><h2 className="font-bold">{item.title}</h2><p className="mt-1 text-sm leading-6 text-caramel">{item.text}</p></div></div></article>):<div className="nat-card lg:col-span-3"><p className="font-bold">Nenhuma recomendação liberada agora.</p><p className="mt-1 text-sm text-caramel">Estoque baixo continua aparecendo como fato operacional; padrões comerciais só entram aqui depois da amostra mínima.</p></div>}</div><RoiOverview snapshot={bi}/><details className="nat-card"><summary className="cursor-pointer font-bold">Ver todos os indicadores <HelpTip label="O que aparece nos indicadores completos">Fatos de produtos, clientes, canais, compras e promoções continuam visíveis. Padrões e recomendações respeitam a suficiência da amostra e possuem composição auditável.</HelpTip></summary><div className="mt-6 border-t border-nat pt-6"><IntelligenceView state={state} inventory={inventory} businessId={businessId}/></div></details></section>;
}
