import { AlertTriangle, Boxes, TrendingDown, Users } from "lucide-react";
import { customerOverview, money, productProfitability, type NatState } from "@/domain/nat";
import { businessInsights } from "@/domain/insights";
import type { InventorySnapshot } from "@/domain/inventory";
import { HelpTip } from "./Feedback";
import { IntelligenceView } from "./IntelligenceView";

export function IntelligenceWorkbench({state,inventory,businessId}:{state:NatState;inventory:InventorySnapshot;businessId:string|null}){
  const readiness=businessInsights(state).readiness;const overview=customerOverview(state);const products=productProfitability(state);const lowest=[...products].filter((item)=>item.units>0).sort((a,b)=>a.marginPercent-b.marginPercent)[0];const lowStock=inventory.items.filter((item)=>item.tracked&&item.lowStock);
  const alerts=[
    lowStock.length?{icon:<Boxes size={18}/>,title:`${lowStock.length} item(ns) com estoque baixo`,text:`Priorize ${lowStock.slice(0,2).map((item)=>item.name).join(" e ")}.`}:null,
    overview.inactive?{icon:<Users size={18}/>,title:`${overview.inactive} cliente(s) sem comprar há 30+ dias`,text:"Vale revisar relacionamento antes de investir em novas campanhas."}:null,
    lowest?{icon:<TrendingDown size={18}/>,title:`${lowest.name} tem a margem mais baixa`,text:`Resultado variável: ${money(lowest.contribution)}. Revise custo e preço se isso fugir do esperado.`}:null,
  ].filter(Boolean) as {icon:React.ReactNode;title:string;text:string}[];
  return <section className="space-y-5"><div><p className="eyebrow">Análises</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">O que merece atenção</h1><p className="mt-2 max-w-3xl text-caramel">Primeiro mostramos decisões práticas. Os indicadores completos continuam disponíveis abaixo, sem ocupar a tela principal.</p></div>{!readiness.ready&&<div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><span><strong>Base ainda pequena:</strong> use estes sinais como apoio inicial. A NAT espera pelo menos {readiness.minimumSales} vendas em {readiness.minimumDays} dias antes de tratar padrões como mais confiáveis.</span></div>}<div className="grid gap-3 lg:grid-cols-3">{alerts.length?alerts.map((item)=><article key={item.title} className="nat-card"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-rose-soft">{item.icon}</span><div><h2 className="font-bold">{item.title}</h2><p className="mt-1 text-sm leading-6 text-caramel">{item.text}</p></div></div></article>):<div className="nat-card lg:col-span-3"><p className="font-bold">Nenhum alerta relevante agora.</p><p className="mt-1 text-sm text-caramel">Continue registrando vendas, compras e clientes; a NAT destaca mudanças quando houver base suficiente.</p></div>}</div><details className="nat-card"><summary className="cursor-pointer font-bold">Ver todos os indicadores <HelpTip label="O que aparece nos indicadores completos">Produtos, clientes, canais, recompra, capacidade de produção, compras e promoções. Os cálculos são determinísticos e não usam IA.</HelpTip></summary><div className="mt-6 border-t border-nat pt-6"><IntelligenceView state={state} inventory={inventory} businessId={businessId}/></div></details></section>;
}
