import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { loadBusinessIntelligenceDrilldown, type BiDrilldownDimension, type BusinessIntelligenceDrilldown } from "@/data/business-intelligence-repository";
import { money } from "@/domain/nat";
import { useDialogA11y } from "@/hooks/use-dialog-a11y";

const moneyKeys=new Set(["billed","received","contribution","investedCost","listValue","discount"]);
const labels:Record<string,string>={orders:"Pedidos",units:"Unidades",billed:"Faturamento",received:"Recebido",contribution:"Contribuição",investedCost:"Investimento",customers:"Clientes",recurring:"Recorrentes",repurchased:"Recompraram",listValue:"Preço de tabela",discount:"Desconto",firstPurchase:"Primeira compra",lastPurchase:"Última compra"};
function valueText(key:string,value:unknown){if(value==null)return "—";if(moneyKeys.has(key))return money(Number(value));if(key.toLowerCase().includes("purchase")||key==="soldAt")return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short"}).format(new Date(String(value)));if(typeof value==="boolean")return value?"Sim":"Não";return String(value);}
function rowTitle(dimension:BiDrilldownDimension,row:Record<string,unknown>){if(dimension==="product")return String(row.customerName??row.productName??"Venda");if(dimension==="origin"||dimension==="cohort")return String(row.customerName??"Cliente");if(dimension==="promotion")return String(row.customerName??"Venda com desconto");return String(row.customerName??"Venda");}
function rowMeta(row:Record<string,unknown>){const parts:string[]=[];if(row.soldAt)parts.push(new Intl.DateTimeFormat("pt-BR").format(new Date(String(row.soldAt))));if(row.quantity!=null)parts.push(`${row.quantity} un`);if(row.orders!=null)parts.push(`${row.orders} pedido(s)`);if(row.billed!=null)parts.push(`faturamento ${money(Number(row.billed))}`);if(row.discount!=null)parts.push(`desconto ${money(Number(row.discount))}`);if(row.contribution!=null)parts.push(`contribuição ${money(Number(row.contribution))}`);if(row.recurring!=null)parts.push(row.recurring?"recorrente":"1 compra");if(row.repurchased!=null)parts.push(row.repurchased?"recomprou":"não recomprou");return parts.join(" · ");}

export function IntelligenceDrilldownDialog({businessId,dimension,metricKey,title,onClose}:{businessId:string;dimension:BiDrilldownDimension;metricKey:string|null;title:string;onClose:()=>void}){
  const[data,setData]=useState<BusinessIntelligenceDrilldown|null>(null);const[error,setError]=useState<string|null>(null);const panelRef=useDialogA11y<HTMLDivElement>({onClose});
  useEffect(()=>{let active=true;setData(null);setError(null);void loadBusinessIntelligenceDrilldown(businessId,dimension,metricKey).then((value)=>{if(active)setData(value);}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:"Não foi possível carregar a composição.");});return()=>{active=false};},[businessId,dimension,metricKey]);
  const totals=Object.entries(data?.totals??{}).filter(([,value])=>value!=null);
  return <div className="fixed inset-0 z-50 flex justify-end bg-[#35150A]/35" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><div ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="bi-drilldown-title" className="h-full w-full max-w-2xl overflow-y-auto bg-[#FFF9F6] p-5 sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Composição auditável</p><h2 id="bi-drilldown-title" className="font-display text-4xl">{title}</h2><p className="mt-2 text-sm text-caramel">Fonte: Lovable Cloud · fuso {data?.timezone??"America/Sao_Paulo"}</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar"><X size={19}/></button></div>{error&&<p className="mt-5 a11y-error" role="alert">{error}</p>}{!data&&!error&&<p className="mt-6 text-sm text-caramel" role="status">Carregando composição...</p>}{data&&<><div className="mt-6 grid gap-2 sm:grid-cols-2">{totals.map(([key,value])=><div key={key} className="rounded-2xl bg-soft p-3"><p className="text-xs font-bold uppercase tracking-wider text-caramel">{labels[key]??key}</p><p className="mt-1 font-bold">{valueText(key,value)}</p></div>)}</div><div className="mt-6"><h3 className="font-bold">Registros que formam o número</h3><div className="mt-3 space-y-2">{data.rows.map((row,index)=><div key={String(row.saleId??row.customerId??index)} className="rounded-2xl border border-nat p-3"><p className="font-bold">{rowTitle(dimension,row)}</p><p className="mt-1 text-xs text-caramel">{rowMeta(row)||"Registro incluído na composição"}</p></div>)}{data.rows.length===0&&<p className="rounded-2xl border border-dashed border-nat p-4 text-sm text-caramel">Nenhum registro compõe este indicador.</p>}</div></div></>}</div></div>;
}
