import { FlaskConical, LockKeyhole, PackageCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { recordBrigadeiroFinishedProduction, recordBrigadeiroMassProduction } from "@/data/inventory-repository";
import { inventoryQuantity, type InventorySnapshot } from "@/domain/inventory";
import type { NatState } from "@/domain/nat";
import { businessDate } from "@/lib/business-time";

type Props={businessId:string|null;state:NatState;inventory:InventorySnapshot};
type MassKey="traditional"|"milk"|"beijinho"|"bicho_pe";
const masses:Array<{key:MassKey;name:string;stockName:string;available:boolean;detail:string}>=[
  {key:"traditional",name:"Massa tradicional",stockName:"Massa • Tradicional",available:true,detail:"Leite condensado + creme de leite + 46 g de chocolate 50% · rende 800 g"},
  {key:"milk",name:"Massa de leite em pó",stockName:"Massa • Leite em pó",available:true,detail:"Leite condensado + creme de leite + 46 g de Ninho · rende 800 g"},
  {key:"beijinho",name:"Massa de beijinho",stockName:"Massa • Beijinho",available:false,detail:"Leite condensado + creme de leite + 46 g de coco ralado"},
  {key:"bicho_pe",name:"Massa de bicho de pé",stockName:"Massa • Bicho de pé",available:false,detail:"Leite condensado + creme de leite + 46 g de Nesquik"},
];
const brigadeiros=[
  {key:"brigadeiro-tradicional",label:"Tradicional",detail:"20 g massa tradicional + 6 g granulado Dori"},
  {key:"brigadeiro-prestigio",label:"Prestígio",detail:"12 g tradicional + 8 g leite em pó + 6 g coco"},
  {key:"brigadeiro-dois-amores",label:"2 Amores",detail:"10 g tradicional + 10 g leite em pó"},
  {key:"surpresa-uva",label:"Surpresa de Uva",detail:"20 g leite em pó + 3 g uva + 6 g Ninho"},
  {key:"brigadeiro-oreo",label:"Oreo",detail:"10 g leite em pó + 10 g Oreo + 6 g Ninho + 1,5 g mini Oreo"},
  {key:"brigadeiro-ninho",label:"Ninho",detail:"20 g leite em pó + 6 g Ninho"},
];
function qty(value:string){const n=Number(value);return Number.isInteger(n)&&n>0?n:0;}

export function ProductionFlowCard({businessId,state,inventory}:Props){
  const[date,setDate]=useState(businessDate());const[amounts,setAmounts]=useState<Record<string,string>>({});const[busy,setBusy]=useState("");const[message,setMessage]=useState<{tone:"ok"|"error";text:string}|null>(null);
  const stock=useMemo(()=>new Map(inventory.items.map((item)=>[item.name,item])),[inventory.items]);
  const productByKey=useMemo(()=>new Map(state.products.map((product)=>[product.portfolioKey??"",product])),[state.products]);
  const producedAt=()=>`${date}T12:00:00-03:00`;
  async function mass(key:MassKey){if(!businessId)return;const batches=qty(amounts[`mass:${key}`]??"");if(!batches){setMessage({tone:"error",text:"Informe quantas receitas de massa foram feitas."});return;}setBusy(`mass:${key}`);setMessage(null);try{await recordBrigadeiroMassProduction({businessId,massKey:key,batches,producedAt:producedAt()});setAmounts((current)=>({...current,[`mass:${key}`]:""}));setMessage({tone:"ok",text:`Massa registrada: ${batches} receita(s), ${batches*800} g adicionados ao estoque.`});window.dispatchEvent(new Event("nat:inventory-changed"));}catch(cause){setMessage({tone:"error",text:cause instanceof Error?cause.message:"Não foi possível registrar a massa."});}finally{setBusy("");}}
  async function finished(key:string){if(!businessId)return;const product=productByKey.get(key);const units=qty(amounts[`product:${key}`]??"");if(!product){setMessage({tone:"error",text:"Este sabor ainda não está configurado no Lovable Cloud."});return;}if(!units){setMessage({tone:"error",text:"Informe quantos brigadeiros foram feitos."});return;}setBusy(`product:${key}`);setMessage(null);try{await recordBrigadeiroFinishedProduction({businessId,productId:product.id,units,producedAt:producedAt()});setAmounts((current)=>({...current,[`product:${key}`]:""}));setMessage({tone:"ok",text:`${units} brigadeiro(s) ${product.name.replace("Brigadeiro • ","")} adicionados ao estoque.`});window.dispatchEvent(new Event("nat:inventory-changed"));}catch(cause){setMessage({tone:"error",text:cause instanceof Error?cause.message:"Não foi possível registrar os brigadeiros."});}finally{setBusy("");}}
  return <section id="production-flow" className="nat-card scroll-mt-24" aria-labelledby="production-flow-title">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Produção do dia</p><h2 id="production-flow-title" className="section-title">Da massa ao brigadeiro pronto</h2><p className="mt-1 max-w-2xl text-sm text-caramel">Registre na ordem em que a produção acontece. A NAT baixa os ingredientes da massa primeiro; depois, ao enrolar cada sabor, baixa somente a massa usada e os confeitos.</p></div><div><label htmlFor="production-day" className="field-label">Data da produção</label><input id="production-day" type="date" className="nat-input min-w-40" value={date} onChange={(e)=>setDate(e.target.value)}/></div></div>
    {message&&<p role="status" className={`mt-4 rounded-2xl p-3 text-sm font-bold ${message.tone==="ok"?"bg-green-50 text-green-800":"bg-red-50 text-red-800"}`}>{message.text}</p>}
    <div className="mt-6"><div className="flex items-center gap-2"><FlaskConical size={19}/><div><h3 className="font-bold">1. Massas</h3><p className="text-sm text-caramel">Cada receita pronta entra como 800 g de massa.</p></div></div><div className="mt-3 grid gap-3 md:grid-cols-2">{masses.map((item)=>{const balance=stock.get(item.stockName);const key=`mass:${item.key}`;return <article key={item.key} className={`rounded-2xl border border-nat p-4 ${item.available?"bg-white":"bg-soft opacity-60"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{item.name}</p><p className="mt-1 text-xs leading-5 text-caramel">{item.detail}</p><p className="mt-2 text-sm font-bold">Em estoque: {balance?inventoryQuantity(balance.currentQuantity,balance.baseUnit):"0 g"}</p></div>{!item.available&&<span className="flex shrink-0 items-center gap-1 rounded-full bg-white px-2 py-1 text-[10px] font-black uppercase tracking-wider"><LockKeyhole size={11}/> A liberar</span>}</div>{item.available&&<div className="mt-4 flex gap-2"><input className="nat-input min-w-0" inputMode="numeric" aria-label={`Receitas de ${item.name}`} placeholder="Quantas receitas?" value={amounts[key]??""} onChange={(e)=>setAmounts((current)=>({...current,[key]:e.target.value}))}/><button type="button" className="primary-button shrink-0 justify-center" disabled={Boolean(busy)||!date} onClick={()=>void mass(item.key)}>{busy===key?"Registrando...":"Registrar"}</button></div>}</article>;})}</div></div>
    <div className="mt-7"><div className="flex items-center gap-2"><PackageCheck size={19}/><div><h3 className="font-bold">2. Brigadeiros prontos</h3><p className="text-sm text-caramel">Informe quantas unidades foram enroladas de cada sabor.</p></div></div><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{brigadeiros.map((item)=>{const product=productByKey.get(item.key);const key=`product:${item.key}`;const balance=product?inventory.items.find((stockItem)=>stockItem.kind==="product"&&stockItem.itemId===product.id):null;return <article key={item.key} className="rounded-2xl border border-nat bg-white p-4"><p className="font-bold">{item.label}</p><p className="mt-1 min-h-10 text-xs leading-5 text-caramel">{item.detail}</p><p className="mt-2 text-sm font-bold">Prontos: {balance?inventoryQuantity(balance.currentQuantity,balance.baseUnit):"0 un"}</p><div className="mt-4 flex gap-2"><input className="nat-input min-w-0" inputMode="numeric" aria-label={`Unidades de ${item.label}`} placeholder="Unidades" value={amounts[key]??""} onChange={(e)=>setAmounts((current)=>({...current,[key]:e.target.value}))}/><button type="button" className="secondary-button shrink-0 justify-center" disabled={Boolean(busy)||!date||!product} onClick={()=>void finished(item.key)}>{busy===key?"Registrando...":"Adicionar"}</button></div></article>;})}</div></div>
    <p className="mt-5 rounded-2xl bg-soft p-4 text-sm leading-6 text-caramel"><strong className="text-chocolate">3. Embalagem:</strong> não é baixada aqui. A NAT desconta caixinha, forminha, sacola ou conjunto de quarteto somente quando a venda é confirmada.</p>
  </section>;
}
