import { Copy, Plus, Trash2 } from "lucide-react";
import { useState, type ReactNode } from "react";
import { money, percent, preferredUsageUnit, pricingFeePercent, productCost, supplyUnitCost, type NatState, type Product, type SporadicExpense, type Supply } from "@/domain/nat";
import { BRIGADEIRO_CATALOG, BROWNIE_CATALOG, STARTER_INGREDIENTS, STARTER_PACKAGING, STARTER_SPORADIC_EXPENSES, catalogItemForProduct, type CatalogItem, type StarterSupply } from "@/domain/catalog";
import { ConfirmDialog } from "./Feedback";
import { Empty } from "./Views";

export type ProductTab = "products" | "supplies" | "expenses";
type PendingAction={title:string;text:string;label:string;run:()=>void}|null;

function PageHeading({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Base de custos</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">{title}</h1><p className="mt-2 max-w-2xl text-caramel">{text}</p></div>{action}</div>;}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-soft p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-caramel">{label}</p><p className="mt-1 font-bold">{value}</p></div>;}
function supplyCategoryLabel(category:Supply["category"]){const value=category as string;return value==="ingredient"?"Ingrediente":value==="packaging"?"Embalagem":"Outro insumo";}
function missingStarters(supplies:Supply[],starters:StarterSupply[]){const names=new Set(supplies.map((s)=>s.name.toLocaleLowerCase("pt-BR")));return starters.filter((starter)=>!names.has(starter.name.toLocaleLowerCase("pt-BR")));}

export function ProductsView({state,tab,onTab,onNewSupply,onEditSupply,onDeleteSupply,onNewProduct,onEditProduct,onDuplicateProduct,onDeleteProduct,onNewExpense,onEditExpense,onDeleteExpense}:{state:NatState;tab:ProductTab;onTab:(tab:ProductTab)=>void;onNewSupply:(preset?:StarterSupply)=>void;onEditSupply:(s:Supply)=>void;onDeleteSupply:(id:string)=>void;onNewProduct:(preset?:CatalogItem)=>void;onEditProduct:(p:Product)=>void;onDuplicateProduct:(p:Product)=>void;onDeleteProduct:(id:string)=>void;onNewExpense:(presetName?:string)=>void;onEditExpense:(expense:SporadicExpense)=>void;onDeleteExpense:(id:string)=>void}){
  const [pending,setPending]=useState<PendingAction>(null);
  const confirm=(action:Exclude<PendingAction,null>)=>setPending(action);
  return <>
    <section><PageHeading title="Produtos" text="Organize sabores, compras e gastos da produção. Ingredientes, embalagens e outros insumos podem depois ser acompanhados também no Estoque."/>
      <div className="mt-5 inline-flex max-w-full overflow-x-auto rounded-2xl bg-white p-1 shadow-sm" role="tablist" aria-label="Produtos, insumos e gastos">
        <button type="button" role="tab" aria-selected={tab==="products"} className={`tab-button whitespace-nowrap ${tab==="products"?"active":""}`} onClick={()=>onTab("products")}>Sabores</button>
        <button type="button" role="tab" aria-selected={tab==="supplies"} className={`tab-button whitespace-nowrap ${tab==="supplies"?"active":""}`} onClick={()=>onTab("supplies")}>Ingredientes e embalagens</button>
        <button type="button" role="tab" aria-selected={tab==="expenses"} className={`tab-button whitespace-nowrap ${tab==="expenses"?"active":""}`} onClick={()=>onTab("expenses")}>Gastos esporádicos</button>
      </div>
      {tab==="supplies"?<Supplies state={state} onNew={onNewSupply} onEdit={onEditSupply} onDelete={(supply)=>confirm({title:`Arquivar ${supply.name}?`,text:"O item deixa de aparecer nos cadastros. Se estiver em uma receita ativa, a NAT impedirá o arquivamento e explicará o motivo.",label:"Arquivar",run:()=>onDeleteSupply(supply.id)})}/>:tab==="expenses"?<Expenses expenses={state.expenses} onNew={onNewExpense} onEdit={onEditExpense} onDelete={(expense)=>confirm({title:`Excluir ${expense.name}?`,text:"Esse gasto sairá do resultado do mês. Esta ação deve ser usada somente para um lançamento feito por engano.",label:"Excluir",run:()=>onDeleteExpense(expense.id)})}/>:<Products state={state} onNew={onNewProduct} onEdit={onEditProduct} onDuplicate={onDuplicateProduct} onDelete={(product)=>confirm({title:`Arquivar ${product.name}?`,text:"O produto sai dos novos cadastros, mas o histórico comercial já registrado continua preservado.",label:"Arquivar",run:()=>onDeleteProduct(product.id)})}/>} 
    </section>
    {pending&&<ConfirmDialog title={pending.title} text={pending.text} confirmLabel={pending.label} danger onClose={()=>setPending(null)} onConfirm={()=>{const action=pending.run;setPending(null);action();}}/>}
  </>;
}

function StarterButtons({title,items,onNew}:{title:string;items:StarterSupply[];onNew:(preset:StarterSupply)=>void}){if(!items.length)return null;return <div className="rounded-2xl bg-soft p-4"><p className="font-bold">{title}</p><div className="mt-3 flex flex-wrap gap-2">{items.map((item)=><button key={item.name} type="button" className="rounded-full border border-nat bg-white px-3 py-2 text-xs font-bold" onClick={()=>onNew(item)}>+ {item.name}</button>)}</div></div>;}
function Supplies({state,onNew,onEdit,onDelete}:{state:NatState;onNew:(preset?:StarterSupply)=>void;onEdit:(s:Supply)=>void;onDelete:(s:Supply)=>void}){
  const ingredients=missingStarters(state.supplies,STARTER_INGREDIENTS);const packaging=missingStarters(state.supplies,STARTER_PACKAGING);
  return <div className="nat-card mt-5"><div className="flex items-center justify-between gap-4"><div><h2 className="section-title">O que você compra</h2><p className="mt-1 text-sm text-caramel">Cada compra atualiza o custo. Depois que um item entrar no controle de estoque, novas compras também somam automaticamente ao saldo.</p></div><button type="button" className="primary-button shrink-0" onClick={()=>onNew()}><Plus size={18}/><span className="hidden sm:inline">Cadastrar</span></button></div>
    <div className="mt-5 space-y-3"><StarterButtons title="Ingredientes para começar" items={ingredients} onNew={onNew}/><StarterButtons title="Embalagens da NAT" items={packaging} onNew={onNew}/></div>
    <div className="mt-5 grid gap-3 md:grid-cols-2">{state.supplies.map((supply)=><article key={supply.id} className="rounded-2xl border border-nat p-4"><div className="flex items-start gap-3"><button type="button" className="min-w-0 flex-1 text-left" onClick={()=>onEdit(supply)}><span className="rounded-full bg-rose-soft px-2.5 py-1 text-[11px] font-bold text-caramel">{supplyCategoryLabel(supply.category)}</span><p className="mt-3 text-lg font-bold">{supply.name}</p><p className="mt-1 text-sm text-caramel">{supply.packageQuantity} {supply.packageUnit==="unit"?"un":supply.packageUnit} por {money(supply.packagePrice)}</p></button><button type="button" className="icon-button" onClick={()=>onDelete(supply)} aria-label={`Arquivar ${supply.name}`}><Trash2 size={16}/></button></div><p className="mt-4 border-t border-nat pt-3 text-sm"><span className="text-caramel">Custo base: </span><strong>{money(supplyUnitCost(supply))}</strong> / {preferredUsageUnit(supply.packageUnit)==="unit"?"un":preferredUsageUnit(supply.packageUnit)}</p></article>)}{!state.supplies.length&&<div className="md:col-span-2"><Empty text="Escolha uma sugestão acima ou cadastre a primeira compra."/></div>}</div>
  </div>;
}

function Family({title,items,state,onNew,onEdit,onDuplicate}:{title:string;items:CatalogItem[];state:NatState;onNew:(preset?:CatalogItem)=>void;onEdit:(product:Product)=>void;onDuplicate:(product:Product)=>void}){return <div><div className="mb-3 flex items-center justify-between"><h3 className="font-display text-3xl">{title}</h3><span className="text-xs font-bold text-caramel">{items.filter((item)=>state.products.some((product)=>product.portfolioKey===item.key)).length}/{items.length}</span></div><div className="grid gap-3 md:grid-cols-2">{items.map((item)=>{const product=state.products.find((candidate)=>candidate.portfolioKey===item.key);const metrics=product?productCost(product,state.supplies,pricingFeePercent(state.settings)):null;return <article key={item.key} className="rounded-2xl border border-nat p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-caramel">{item.family==="brownie"?"Brownie":"Brigadeiro"}</p><p className="mt-1 text-lg font-bold">{item.flavor}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${product?"bg-rose-soft":"bg-soft text-caramel"}`}>{product?"Receita criada":"A configurar"}</span></div>{product&&<div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Custo" value={product.recipe.length?money(metrics?.unitCost??Number.NaN):"—"}/><Mini label="Venda" value={product.sellingPrice>0?money(product.sellingPrice):"—"}/><Mini label="Margem" value={product.sellingPrice>0?percent(metrics?.marginAtCurrentPrice??Number.NaN):"—"}/></div>}<div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" className="secondary-button w-full justify-center" onClick={()=>product?onEdit(product):onNew(item)}>{product?"Editar":"Configurar receita"}</button>{product&&<button type="button" className="secondary-button w-full justify-center" onClick={()=>onDuplicate(product)}><Copy size={15}/> Duplicar</button>}</div></article>;})}</div></div>;}
function Products({state,onNew,onEdit,onDuplicate,onDelete}:{state:NatState;onNew:(preset?:CatalogItem)=>void;onEdit:(p:Product)=>void;onDuplicate:(p:Product)=>void;onDelete:(p:Product)=>void}){const custom=state.products.filter((product)=>!catalogItemForProduct(product));return <div className="nat-card mt-5"><div className="flex items-center justify-between gap-4"><div><h2 className="section-title">Sabores do cardápio</h2><p className="mt-1 text-sm text-caramel">Cada sabor tem receita, custo e preço próprios.</p></div><button type="button" className="primary-button shrink-0" onClick={()=>onNew()}><Plus size={18}/><span className="hidden sm:inline">Outro produto</span></button></div><div className="mt-6 space-y-7"><Family title="Brownies" items={BROWNIE_CATALOG} state={state} onNew={onNew} onEdit={onEdit} onDuplicate={onDuplicate}/><Family title="Brigadeiros" items={BRIGADEIRO_CATALOG} state={state} onNew={onNew} onEdit={onEdit} onDuplicate={onDuplicate}/>{custom.length>0&&<div><h3 className="font-display text-3xl">Outros produtos</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{custom.map((product)=>{const metrics=productCost(product,state.supplies,pricingFeePercent(state.settings));return <article key={product.id} className="rounded-2xl border border-nat p-4"><div className="flex items-start gap-3"><button type="button" className="min-w-0 flex-1 text-left" onClick={()=>onEdit(product)}><p className="font-display text-2xl">{product.name}</p><p className="text-sm text-caramel">Rende {product.batchYield} unidades</p></button><button type="button" className="icon-button" onClick={()=>onDuplicate(product)} aria-label={`Duplicar ${product.name}`}><Copy size={16}/></button><button type="button" className="icon-button" onClick={()=>onDelete(product)} aria-label={`Arquivar ${product.name}`}><Trash2 size={16}/></button></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Custo" value={money(metrics.unitCost)}/><Mini label="Venda" value={money(product.sellingPrice)}/><Mini label="Margem" value={percent(metrics.marginAtCurrentPrice)}/></div></article>;})}</div></div>}</div></div>;}

function Expenses({expenses,onNew,onEdit,onDelete}:{expenses:SporadicExpense[];onNew:(presetName?:string)=>void;onEdit:(expense:SporadicExpense)=>void;onDelete:(expense:SporadicExpense)=>void}){const used=new Set(expenses.map((expense)=>expense.name.toLocaleLowerCase("pt-BR")));const starters=STARTER_SPORADIC_EXPENSES.filter((name)=>!used.has(name.toLocaleLowerCase("pt-BR")));const total=expenses.reduce((sum,expense)=>sum+expense.amount,0);return <div className="nat-card mt-5"><div className="flex items-center justify-between gap-4"><div><h2 className="section-title">Gastos esporádicos</h2><p className="mt-1 text-sm text-caramel">Compras pontuais reduzem o resultado do mês, mas não viram estoque automaticamente.</p></div><button type="button" className="primary-button shrink-0" onClick={()=>onNew()}><Plus size={18}/><span className="hidden sm:inline">Registrar</span></button></div>{starters.length>0&&<div className="mt-5 rounded-2xl bg-soft p-4"><p className="font-bold">Sugestões</p><div className="mt-3 flex flex-wrap gap-2">{starters.map((name)=><button key={name} type="button" className="rounded-full border border-nat bg-white px-3 py-2 text-xs font-bold" onClick={()=>onNew(name)}>+ {name}</button>)}</div></div>}<div className="mt-5 flex items-center justify-between rounded-2xl bg-rose-soft p-4"><span className="font-bold">Total registrado</span><strong className="font-display text-2xl">{money(total)}</strong></div><div className="mt-4 space-y-2">{expenses.map((expense)=><article key={expense.id} className="flex items-center gap-3 rounded-2xl border border-nat p-4"><button type="button" className="min-w-0 flex-1 text-left" onClick={()=>onEdit(expense)}><p className="font-bold">{expense.name}</p><p className="text-xs text-caramel">{new Intl.DateTimeFormat("pt-BR").format(new Date(`${expense.spentAt.slice(0,10)}T12:00:00`))}</p></button><strong>{money(expense.amount)}</strong><button type="button" className="icon-button" onClick={()=>onDelete(expense)} aria-label={`Excluir gasto ${expense.name}`}><Trash2 size={16}/></button></article>)}{!expenses.length&&<Empty text="Nenhum gasto esporádico registrado."/>}</div></div>;}
