import { money, percent, type NatState } from "@/domain/nat";
import { businessRoi, productRoiAnalytics } from "@/domain/roi";
import { HelpTip } from "./Feedback";

export function RoiOverview({state,compact=false}:{state:NatState;compact?:boolean}){
  const business=businessRoi(state);
  const products=productRoiAnalytics(state);
  return <div className="nat-card"><p className="eyebrow">Retorno sobre o investimento</p><div className="flex items-center gap-1"><h2 className="section-title">ROI da NAT</h2><HelpTip label="O que é ROI?" symbol="i">ROI significa retorno sobre o investimento. A NAT calcula retorno líquido ÷ valor investido × 100. Margem responde quanto da receita sobrou; ROI responde quanto o valor investido retornou.</HelpTip></div><p className="mt-2 text-sm leading-6 text-caramel">ROI compara o retorno líquido com o custo realmente investido. Aporte dos donos e reinvestimento da NAT são origem do dinheiro, não entram duas vezes como custo.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">ROI do mês</p><p className="mt-1 text-2xl font-bold">{percent(business.roiPercent)}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">Investimento operacional</p><p className="mt-1 text-2xl font-bold">{money(business.investedCost)}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">Retorno líquido</p><p className="mt-1 text-2xl font-bold">{money(business.netReturn)}</p></div></div>{!compact&&<div className="mt-5"><p className="font-bold">ROI por sabor</p><p className="mt-1 text-xs text-caramel">Baseado nos custos congelados das vendas já carregadas no histórico.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{products.length?products.map((row)=><div key={row.productId} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{row.name}</strong><span className="font-bold">{percent(row.roiPercent)}</span></div><p className="mt-1 text-xs text-caramel">{row.units} un · receita {money(row.revenue)} · investimento {money(row.investedCost)} · retorno {money(row.netReturn)}</p></div>):<p className="text-sm text-caramel">Ainda não há vendas suficientes para calcular ROI por sabor.</p>}</div></div>}</div>;
}
