import { money, percent } from "@/domain/nat";
import type { BusinessIntelligenceSnapshot } from "@/data/business-intelligence-repository";

function roiLabel(value:number|null){return value==null?"—":percent(value);}

export function RoiOverview({snapshot,compact=false}:{snapshot:BusinessIntelligenceSnapshot|null;compact?:boolean}){
  const business=snapshot?.businessRoi;const products=snapshot?.products??[];
  return <div className="nat-card"><p className="eyebrow">Retorno sobre o investimento</p><h2 className="section-title">ROI da NAT</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-caramel">ROI mostra, de forma simples, se o dinheiro colocado no negócio voltou com sobra. Quando fica positivo, as vendas devolveram mais do que custaram; quando fica negativo, os custos ainda ficaram acima do retorno.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">ROI do mês</p><p className="mt-1 text-2xl font-bold" data-testid="business-roi">{roiLabel(business?.roiPercent??null)}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">Total investido no mês</p><p className="mt-1 text-2xl font-bold">{business?money(business.investedCost):"—"}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">Retorno líquido</p><p className="mt-1 text-2xl font-bold">{business?money(business.netReturn):"—"}</p></div></div>{!compact&&<div className="mt-6"><p className="font-bold">ROI por sabor</p><p className="mt-1 text-sm text-caramel">Compare cada sabor pelo que já custou e pelo que já vendeu. A lista acompanha o Portfólio atual da NAT.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{products.length?products.map((row)=><div key={row.productId} className="rounded-2xl border border-nat p-4"><div className="flex items-start justify-between gap-3"><strong>{row.name}</strong><span className="shrink-0 font-bold">{roiLabel(row.roiPercent)}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-soft p-3"><p className="text-xs font-bold uppercase tracking-wider text-caramel">Custo acumulado</p><p className="mt-1 font-bold">{money(row.investedCost)}</p></div><div className="rounded-xl bg-soft p-3"><p className="text-xs font-bold uppercase tracking-wider text-caramel">Venda acumulada</p><p className="mt-1 font-bold">{money(row.billed)}</p></div></div></div>):<p className="text-sm text-caramel">Ainda não há produtos no Portfólio para comparar.</p>}</div></div>}</div>;
}
