import { money, percent } from "@/domain/nat";
import type { BusinessIntelligenceSnapshot } from "@/data/business-intelligence-repository";
import { HelpTip } from "./Feedback";

function roiLabel(value:number|null){return value==null?"—":percent(value);}

export function RoiOverview({snapshot,compact=false}:{snapshot:BusinessIntelligenceSnapshot|null;compact?:boolean}){
  const business=snapshot?.businessRoi;const products=snapshot?.products??[];
  return <div className="nat-card"><p className="eyebrow">Retorno sobre o investimento</p><div className="flex items-center gap-1"><h2 className="section-title">ROI da NAT</h2><HelpTip label="O que é ROI?" symbol="i">ROI significa retorno sobre o investimento. A NAT calcula retorno líquido ÷ valor investido × 100. Margem responde quanto da receita sobrou; ROI responde quanto o valor investido retornou.</HelpTip></div><p className="mt-2 text-sm leading-6 text-caramel">O ROI agora é calculado no Lovable Cloud. O mês usa custos variáveis, gastos extras e custos fixos; o ROI por sabor usa todo o histórico e os snapshots congelados de cada venda.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">ROI do mês</p><p className="mt-1 text-2xl font-bold" data-testid="business-roi">{roiLabel(business?.roiPercent??null)}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">Investimento operacional</p><p className="mt-1 text-2xl font-bold">{business?money(business.investedCost):"—"}</p></div><div className="rounded-2xl bg-soft p-4"><p className="text-sm font-bold text-caramel">Retorno líquido</p><p className="mt-1 text-2xl font-bold">{business?money(business.netReturn):"—"}</p></div></div>{!compact&&<div className="mt-5"><p className="font-bold">ROI por sabor</p><p className="mt-1 text-xs text-caramel">Histórico vitalício do Lovable Cloud; vendas com mais de 45 dias continuam entrando no cálculo.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{products.length?products.map((row)=><div key={row.productId} className="rounded-2xl border border-nat p-3"><div className="flex items-center justify-between gap-3"><strong>{row.name}</strong><span className="font-bold">{roiLabel(row.roiPercent)}</span></div><p className="mt-1 text-xs text-caramel">{row.units} un · faturamento {money(row.billed)} · investimento {money(row.investedCost)} · retorno {money(row.netReturn)}</p></div>):<p className="text-sm text-caramel">Ainda não há vendas válidas para calcular ROI por sabor.</p>}</div></div>}</div>;
}
