import { AlertTriangle, Plus, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { buildSaleOrder, money, paymentFeeForMethod, paymentLabel, saleChannelLabel, transactionTypeLabel, type NatState, type PaymentMethod, type PaymentStatus, type Product, type Sale, type SaleChannel, type TransactionType } from "@/domain/nat";
import { quoteSale, type SaleQuote } from "@/data/sale-quote-repository";
import { useDialogA11y } from "@/hooks/use-dialog-a11y";
import { businessDate } from "@/lib/business-time";

type DraftLine={key:string;productId:string;quantity:string};
const numeric=(value:string)=>Number(value.replace(",","."))||0;
function suggestedFor(items:DraftLine[],products:Product[]){return items.reduce((sum,line)=>sum+(products.find((p)=>p.id===line.productId)?.sellingPrice??0)*numeric(line.quantity),0);}

export function SaleOrderSheet({state,businessId,preset,onClose,onSave}:{state:NatState;businessId:string|null;preset?:Sale;onClose:()=>void;onSave:(sale:Sale)=>void}){
  const productsForType=(type:TransactionType)=>state.products.filter((product)=>product.recipe.length>0&&(type!=="sale"||product.available!==false));
  const presetType=preset?.transactionType??"sale";
  const presetLines=(preset?.items??[]).filter((item)=>state.products.some((product)=>product.id===item.productId)).map((item)=>({key:crypto.randomUUID(),productId:item.productId,quantity:String(item.quantity)}));
  const first=productsForType(presetType)[0];const initialLines=presetLines.length?presetLines:first?[{key:crypto.randomUUID(),productId:first.id,quantity:"1"}]:[];
  const saleIdRef=useRef(crypto.randomUUID());const errorRef=useRef<HTMLParagraphElement>(null);const[submitting,setSubmitting]=useState(false);const panelRef=useDialogA11y<HTMLDivElement>({onClose:()=>{if(!submitting)onClose();}});
  const initialMethod:PaymentMethod=preset?.paymentMethod&&preset.paymentMethod!=="other"?preset.paymentMethod:"pix";
  const[lines,setLines]=useState(initialLines);const[transactionType,setTransactionType]=useState<TransactionType>(presetType);const[value,setValue]=useState(String(presetType==="sale"?suggestedFor(initialLines,state.products):0));const[method,setMethod]=useState<PaymentMethod>(initialMethod);const[paymentStatus,setPaymentStatus]=useState<PaymentStatus>("paid");const[customerId,setCustomerId]=useState(preset?.customerId??"");const[date,setDate]=useState(businessDate());const[promiseDate,setPromiseDate]=useState("");const[promiseTime,setPromiseTime]=useState("");const[channel,setChannel]=useState<SaleChannel>(preset?.saleChannel??"other");const[delivery,setDelivery]=useState("0");const[discountReason,setDiscountReason]=useState("");const[belowCostOverride,setBelowCostOverride]=useState(false);const[error,setError]=useState("");const[errorTarget,setErrorTarget]=useState("");const[quote,setQuote]=useState<SaleQuote|null>(null);const[quoteLoading,setQuoteLoading]=useState(false);const[quoteError,setQuoteError]=useState("");
  const sellable=productsForType(transactionType);const customers=(state.customers??[]).filter((customer)=>customer.active);const saleValue=transactionType==="sale"?numeric(value):0;const deliveryCost=transactionType==="sale"?numeric(delivery):0;const effectiveMethod:PaymentMethod=paymentStatus==="pending"?"other":method;const paymentFee=paymentStatus==="pending"?0:paymentFeeForMethod(state.settings,method);const listTotal=useMemo(()=>suggestedFor(lines,state.products),[lines,state.products]);const authoritativeListTotal=quote?.listTotal??listTotal;const adjustment=saleValue-authoritativeListTotal;const hasAdjustment=transactionType==="sale"&&Math.abs(adjustment)>=0.005;const belowCost=Boolean(quote?.belowCost);const sameDayPromise=paymentStatus==="pending"&&promiseDate===date;

  useEffect(()=>{let cancelled=false;setQuoteError("");const items=lines.map((line)=>({productId:line.productId,quantity:numeric(line.quantity)}));const valid=Boolean(businessId&&date&&items.length&&items.every((item)=>item.productId&&item.quantity>0&&Number.isInteger(item.quantity))&&saleValue>=0&&deliveryCost>=0);if(!valid||!businessId){setQuote(null);setQuoteLoading(false);return;}setQuoteLoading(true);const timer=window.setTimeout(()=>{void quoteSale({businessId,items,totalReceived:saleValue,paymentMethod:effectiveMethod,soldAt:`${date}T12:00:00-03:00`,transactionType,deliveryCost}).then((result)=>{if(!cancelled){setQuote(result);setQuoteError("");}}).catch((cause)=>{if(!cancelled){setQuote(null);setQuoteError(cause instanceof Error?cause.message:"Não foi possível calcular esta venda.");}}).finally(()=>{if(!cancelled)setQuoteLoading(false);});},180);return()=>{cancelled=true;window.clearTimeout(timer);};},[businessId,date,deliveryCost,effectiveMethod,lines,saleValue,transactionType]);

  const fail=(message:string,target="")=>{setError(message);setErrorTarget(target);window.requestAnimationFrame(()=>{if(target)document.getElementById(target)?.focus();else errorRef.current?.focus();});};
  function updateLines(next:DraftLine[]){setLines(next);setError("");if(transactionType==="sale")setValue(String(suggestedFor(next,state.products)));}
  function addLine(){const used=new Set(lines.map((line)=>line.productId));const product=sellable.find((item)=>!used.has(item.id));if(product)updateLines([...lines,{key:crypto.randomUUID(),productId:product.id,quantity:"1"}]);}
  function changeType(next:TransactionType){const options=productsForType(next);let nextLines=lines.filter((line)=>options.some((product)=>product.id===line.productId));if(!nextLines.length&&options[0])nextLines=[{key:crypto.randomUUID(),productId:options[0].id,quantity:"1"}];setTransactionType(next);setLines(nextLines);setPaymentStatus("paid");setPromiseDate("");setPromiseTime("");setBelowCostOverride(false);setDiscountReason("");setValue(next==="sale"?String(suggestedFor(nextLines,state.products)):"0");}
  function submit(event:React.FormEvent){event.preventDefault();setError("");if(!lines.length)return fail("Adicione pelo menos um produto.");const ids=lines.map((line)=>line.productId);if(new Set(ids).size!==ids.length)return fail("O mesmo produto apareceu duas vezes.");const items=lines.map((line)=>({product:sellable.find((candidate)=>candidate.id===line.productId),quantity:numeric(line.quantity)}));const invalid=items.findIndex((item)=>!item.product||item.quantity<=0||!Number.isInteger(item.quantity));if(invalid>=0)return fail("Informe uma quantidade inteira maior que zero.",`sale-quantity-${invalid}`);if(!date)return fail("Informe a data da venda.","sale-date");if(transactionType==="sale"&&paymentStatus==="pending"){if(!customerId)return fail("Para vender fiado, selecione um cliente cadastrado.","sale-customer");if(!promiseDate)return fail("Informe a data prometida para o pagamento.","payment-promised-date");if(promiseDate<date)return fail("A data prometida não pode ser anterior à venda.","payment-promised-date");if(promiseDate===date&&!promiseTime)return fail("Para pagamento prometido no mesmo dia, informe o horário.","payment-promised-time");}if(quoteLoading||!quote)return fail(quoteError||"Aguarde o cálculo antes de salvar.");const reason=discountReason.trim();if(hasAdjustment&&reason.length<2)return fail("Explique o motivo do desconto ou acréscimo.","discount-reason");if(belowCost&&!belowCostOverride)return fail("Esta venda fica abaixo do custo. Confirme antes de continuar.","below-cost-confirm");if(belowCost&&reason.length<2)return fail("Explique por que a venda ficará abaixo do custo.","discount-reason");
    setSubmitting(true);try{const built=buildSaleOrder({items:items.map((item)=>({product:item.product!,quantity:item.quantity})),supplies:state.supplies,paymentFeePercent:paymentFee,totalReceived:saleValue,paymentMethod:effectiveMethod,soldAt:`${date}T12:00:00-03:00`,customerId:customerId||null,transactionType,saleChannel:channel,deliveryCost,discountReason:reason||"Validação autoritativa",belowCostOverride:true,paymentStatus:transactionType==="sale"?paymentStatus:"paid",paymentPromisedDate:paymentStatus==="pending"?promiseDate:null,paymentPromisedTime:paymentStatus==="pending"&&sameDayPromise?promiseTime:null});onSave({...built,id:saleIdRef.current,unitCostSnapshot:quote.totalQuantity>0?quote.totalCost/quote.totalQuantity:0,variableFeeSnapshot:quote.variableFee,contributionSnapshot:quote.contribution,discountReason:reason||null,belowCostOverride:transactionType==="sale"?belowCostOverride:false});}catch(cause){setSubmitting(false);fail(cause instanceof Error?cause.message:"Não foi possível salvar esta venda.");}}

  return <div className="fixed inset-0 z-50 flex justify-end bg-[#35150A]/35" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!submitting)onClose();}}><div ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="sale-order-title" className="h-full w-full max-w-xl overflow-y-auto bg-[#FFF9F6] p-5 pb-[max(24px,env(safe-area-inset-bottom))] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Vendas e saídas</p><h2 id="sale-order-title" className="mt-2 font-display text-4xl">Registrar venda ou saída</h2><p className="mt-2 text-base text-caramel">O valor da venda entra no faturamento. Se o cliente pagar depois, o dinheiro só entra no caixa quando você marcar como pago.</p></div><button type="button" className="icon-button" onClick={onClose} disabled={submitting} aria-label="Fechar"><X size={20}/></button></div>
  <form className="mt-7 space-y-5" onSubmit={submit} noValidate><fieldset disabled={submitting} className="contents"><div><label className="field-label" htmlFor="movement-type">O que aconteceu?</label><select id="movement-type" className="nat-input" value={transactionType} onChange={(e)=>changeType(e.target.value as TransactionType)}>{(["sale","courtesy","personal_consumption","loss"] as TransactionType[]).map((type)=><option key={type} value={type}>{transactionTypeLabel[type]}</option>)}</select></div>
  <div><div className="flex items-center justify-between gap-3"><div><p className="field-label">Produtos e quantidades</p><p className="field-help">Adicione todos os itens deste pedido.</p></div><button type="button" className="secondary-button" onClick={addLine} disabled={lines.length>=sellable.length}><Plus size={16}/> Adicionar</button></div><div className="mt-3 space-y-3">{lines.map((line,index)=><div key={line.key} className="grid grid-cols-[minmax(0,1fr)_82px_42px] gap-2 rounded-2xl bg-soft p-3"><select className="nat-input" aria-label={`Produto ${index+1}`} value={line.productId} onChange={(e)=>updateLines(lines.map((item)=>item.key===line.key?{...item,productId:e.target.value}:item))}>{sellable.map((product)=><option key={product.id} value={product.id}>{product.name}</option>)}</select><input id={`sale-quantity-${index}`} className="nat-input" inputMode="numeric" aria-label={`Quantidade do produto ${index+1}`} value={line.quantity} onChange={(e)=>updateLines(lines.map((item)=>item.key===line.key?{...item,quantity:e.target.value}:item))}/><button type="button" className="icon-button" disabled={lines.length===1} onClick={()=>updateLines(lines.filter((item)=>item.key!==line.key))} aria-label={`Remover produto ${index+1}`}><Trash2 size={16}/></button></div>)}</div></div>
  {transactionType==="sale"&&<><div><label htmlFor="sale-total" className="field-label">Valor da venda</label><input id="sale-total" className="nat-input" inputMode="decimal" value={value} onChange={(e)=>setValue(e.target.value)}/><p className="field-help">Preço de tabela: {money(authoritativeListTotal)}.</p></div><fieldset><legend className="field-label">Situação do pagamento</legend><div className="grid grid-cols-2 gap-2"><button type="button" aria-pressed={paymentStatus==="paid"} className={`choice-button ${paymentStatus==="paid"?"active":""}`} onClick={()=>setPaymentStatus("paid")}>Pago agora</button><button type="button" aria-pressed={paymentStatus==="pending"} className={`choice-button ${paymentStatus==="pending"?"active":""}`} onClick={()=>setPaymentStatus("pending")}>Vai pagar depois</button></div></fieldset>
  <div><label className="field-label" htmlFor="sale-customer">Cliente {paymentStatus==="pending"&&<span className="text-red-700">(obrigatório no fiado)</span>}</label><select id="sale-customer" className="nat-input" value={customerId} onChange={(e)=>setCustomerId(e.target.value)}><option value="">Cliente não identificado</option>{customers.map((customer)=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></div>
  {paymentStatus==="pending"&&<div className="rounded-2xl border border-nat bg-soft p-4"><p className="font-bold">Quando o cliente prometeu pagar?</p><p className="mt-1 text-sm text-caramel">Se não houver horário em uma data futura, o SLA começa às 09:00 desse dia.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><label className="field-label" htmlFor="payment-promised-date">Data prometida</label><input id="payment-promised-date" type="date" className="nat-input" min={date} value={promiseDate} onChange={(e)=>{setPromiseDate(e.target.value);if(e.target.value!==date)setPromiseTime("");}}/></div>{sameDayPromise&&<div><label className="field-label" htmlFor="payment-promised-time">Horário prometido</label><input id="payment-promised-time" type="time" className="nat-input" value={promiseTime} onChange={(e)=>setPromiseTime(e.target.value)}/></div>}</div></div>}
  {paymentStatus==="paid"&&<fieldset><legend className="field-label">Como recebeu?</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{(["pix","cash","card","other"] as PaymentMethod[]).map((item)=><button key={item} type="button" aria-pressed={method===item} className={`choice-button ${method===item?"active":""}`} onClick={()=>setMethod(item)}>{paymentLabel[item]}</button>)}</div></fieldset>}</>}
  <details className="rounded-2xl border border-nat p-4"><summary className="cursor-pointer font-bold">Mais detalhes</summary><div className="mt-4 space-y-4">{transactionType==="sale"&&<><div><label className="field-label" htmlFor="sale-channel">Onde aconteceu a venda?</label><select id="sale-channel" className="nat-input" value={channel} onChange={(e)=>setChannel(e.target.value as SaleChannel)}>{(["whatsapp","instagram","street","referral","in_person","other"] as SaleChannel[]).map((item)=><option key={item} value={item}>{saleChannelLabel[item]}</option>)}</select></div><div><label className="field-label" htmlFor="sale-delivery">Custo da entrega</label><input id="sale-delivery" className="nat-input" inputMode="decimal" value={delivery} onChange={(e)=>setDelivery(e.target.value)}/></div></>}<div><label className="field-label" htmlFor="sale-date">Data</label><input id="sale-date" type="date" className="nat-input" value={date} onChange={(e)=>setDate(e.target.value)}/></div></div></details>
  {hasAdjustment&&<div><label className="field-label" htmlFor="discount-reason">Motivo do {adjustment<0?"desconto":"acréscimo"}</label><input id="discount-reason" className="nat-input" value={discountReason} onChange={(e)=>setDiscountReason(e.target.value)} maxLength={500}/></div>}{belowCost&&<label className="flex items-start gap-3 rounded-2xl bg-rose-soft p-4"><input id="below-cost-confirm" type="checkbox" className="mt-1 h-5 w-5" checked={belowCostOverride} onChange={(e)=>setBelowCostOverride(e.target.checked)}/><span><strong>Confirmo a venda abaixo do custo</strong><span className="block text-sm text-caramel">Use apenas quando a decisão foi consciente.</span></span></label>}
  </fieldset>{quoteLoading&&<p role="status" className="rounded-xl bg-soft p-3 text-sm">Calculando...</p>}{quoteError&&<p role="alert" className="a11y-error">{quoteError}</p>}{quote&&<div className="rounded-2xl bg-soft p-4"><p className="font-bold">Resumo antes de salvar</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><span className="text-caramel">Valor da venda</span><p className="font-bold">{money(saleValue)}</p></div><div><span className="text-caramel">Resultado da venda</span><p className="font-bold">{money(quote.contribution)}</p></div></div>{paymentStatus==="pending"&&<p className="mt-3 text-sm text-caramel">Caixa agora: {money(0)} · a receber: {money(saleValue)}</p>}</div>}{error&&<p ref={errorRef} id="sale-error" tabIndex={-1} role="alert" className="a11y-error"><AlertTriangle size={16} className="inline"/> {error}</p>}<button className="primary-button w-full justify-center" type="submit" disabled={submitting||quoteLoading}>{submitting?"Salvando...":transactionType==="sale"?"Registrar venda":"Registrar saída"}</button></form></div></div>;
}
