import { Ban, CheckCircle2, Clock3, Plus, ShoppingBag, TriangleAlert, X } from "lucide-react";
import { useState } from "react";
import { dashboardNumbers, money, paymentLabel, paymentPromiseLabel, receivableStage, saleChannelLabel, saleValue, transactionTypeLabel, type NatState, type Sale } from "@/domain/nat";
import { useDialogA11y } from "@/hooks/use-dialog-a11y";
import { useSubmitGuard } from "@/hooks/use-submit-guard";
import { Empty, Metric } from "./Views";

function saleLabel(sale:Sale){return sale.items.length>1?`Pedido com ${sale.items.length} produtos`:sale.items[0]?.productName??sale.productName;}
function CancelSaleDialog({sale,onClose,onConfirm}:{sale:Sale;onClose:()=>void;onConfirm:(reason:string)=>void}){const[reason,setReason]=useState("Cliente desistiu");const[error,setError]=useState("");const{submitting,begin,reset}=useSubmitGuard();const panelRef=useDialogA11y<HTMLDivElement>({onClose:()=>{if(!submitting)onClose();}});function submit(e:React.FormEvent){e.preventDefault();if(reason.trim().length<3){setError("Explique o motivo do cancelamento.");return;}if(!begin())return;try{onConfirm(reason.trim());}catch(cause){reset();setError(cause instanceof Error?cause.message:"Não foi possível cancelar.");}}return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#35150A]/35 sm:items-center sm:p-6"><div ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="cancel-sale-title" className="w-full rounded-t-[28px] bg-[#FFF9F6] p-5 sm:max-w-md sm:rounded-[28px]"><div className="flex justify-between gap-3"><div><p className="eyebrow">Ação financeira</p><h2 id="cancel-sale-title" className="font-display text-3xl">Cancelar venda ou saída</h2></div><button className="icon-button" type="button" onClick={onClose} disabled={submitting} aria-label="Fechar"><X size={19}/></button></div><form className="mt-5 space-y-4" onSubmit={submit}><label className="field-label" htmlFor="cancel-sale-reason">Motivo do cancelamento</label><textarea id="cancel-sale-reason" className="nat-input min-h-24" value={reason} onChange={(e)=>setReason(e.target.value)}/>{error&&<p role="alert" className="a11y-error">{error}</p>}<button className="min-h-11 w-full rounded-xl bg-red-700 px-4 py-3 font-bold text-white" type="submit" disabled={submitting}><Ban size={17} className="inline"/> {submitting?"Cancelando...":"Cancelar movimento"}</button></form></div></div>;}

function PaymentBadge({sale}:{sale:Sale}){if((sale.transactionType??"sale")!=="sale"||sale.paymentStatus!=="pending")return null;const stage=receivableStage(sale);const label=stage==="critical"?"Atrasado crítico":stage==="overdue"?"Em atraso":"Pagamento pendente";return <span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${stage==="critical"?"bg-red-100 text-red-800":stage==="overdue"?"bg-amber-100 text-amber-800":"bg-soft text-caramel"}`}>{label}</span>;}

export function SalesHistoryView({state,onNew,onCancel,onMarkPaid}:{state:NatState;onNew:()=>void;onCancel:(id:string,reason:string)=>void;onMarkPaid:(sale:Sale)=>void|Promise<void>}){
  const numbers=dashboardNumbers(state);const[saleToCancel,setSaleToCancel]=useState<Sale|null>(null);const[paying,setPaying]=useState<string|null>(null);const customers=new Map((state.customers??[]).map((c)=>[c.id,c.name]));
  return <><section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Operação</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Vendas e saídas</h1><p className="mt-2 max-w-2xl text-caramel">Faturamento representa o valor vendido. Pagamentos pendentes ficam separados do dinheiro que já entrou no caixa.</p></div><button type="button" className="primary-button" onClick={onNew}><Plus size={18}/> Registrar venda ou saída</button></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Faturamento do mês" value={money(numbers.revenue)} hint="inclui vendas a receber"/><Metric label="A receber" value={money(numbers.receivables)} hint="vendas ainda não quitadas"/><Metric label="Dinheiro recebido" value={money(numbers.receivedCash)} hint="caixa vindo das vendas"/><Metric label="Unidades vendidas" value={String(numbers.units)} hint="somente vendas"/></div>
  <div className="nat-card mt-5"><h2 className="section-title">Histórico</h2><div className="mt-4 space-y-3">{state.sales.map((sale)=>{const cancelled=sale.status==="cancelled";const type=sale.transactionType??"sale";const customer=sale.customerId?customers.get(sale.customerId):null;const pending=type==="sale"&&!cancelled&&sale.paymentStatus==="pending";const promise=paymentPromiseLabel(sale);return <article key={sale.id} className={`rounded-2xl border p-4 ${cancelled?"border-dashed border-nat bg-soft/60":"border-nat"}`}><div className="flex flex-wrap items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-rose-soft"><ShoppingBag size={18}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{saleLabel(sale)}</p><span className="rounded-full bg-soft px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-caramel">{transactionTypeLabel[type]}</span><PaymentBadge sale={sale}/>{cancelled&&<span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-caramel">Cancelada</span>}</div><p className="text-xs text-caramel">{new Intl.DateTimeFormat("pt-BR").format(new Date(sale.soldAt))} • {sale.quantity} un{customer?` • ${customer}`:" • cliente não identificado"}{type==="sale"?` • ${paymentLabel[sale.paymentMethod]} • ${saleChannelLabel[sale.saleChannel??"other"]}`:""}</p>{pending&&<p className="mt-2 flex items-center gap-1 text-sm text-caramel"><Clock3 size={14}/> Prometido: {promise??"data não informada"}</p>}</div><div className="text-right"><p className={`font-bold ${cancelled?"line-through text-caramel":""}`}>{type==="sale"?money(saleValue(sale)):"R$ 0,00"}</p>{pending?<p className="text-xs font-bold text-amber-800">a receber</p>:!cancelled&&<p className="text-xs text-caramel">impacto {money(sale.contributionSnapshot)}</p>}</div></div>
  {!cancelled&&<div className="mt-3 flex flex-wrap justify-end gap-2 border-t border-nat pt-3">{pending&&<button type="button" className="primary-button" disabled={paying===sale.id} onClick={()=>{setPaying(sale.id);void Promise.resolve(onMarkPaid(sale)).finally(()=>setPaying(null));}}><CheckCircle2 size={16}/> {paying===sale.id?"Quitando...":"Marcar como pago"}</button>}<button type="button" className="secondary-button" onClick={()=>setSaleToCancel(sale)}><Ban size={16}/> Cancelar</button></div>}
  {sale.items.length>1&&<div className="mt-3 space-y-1 border-t border-nat pt-3">{sale.items.map((item)=><div key={item.id??item.productId} className="flex justify-between gap-3 text-sm"><span className="truncate text-caramel">{item.quantity} × {item.productName}</span><span className="font-bold">{type==="sale"?money(item.unitPriceSnapshot*item.quantity):"—"}</span></div>)}</div>}{receivableStage(sale)==="critical"&&<p className="mt-3 flex items-center gap-2 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800"><TriangleAlert size={16}/> Este cliente está marcado como atrasado crítico até a quitação.</p>}{cancelled&&sale.cancelReason&&<p className="mt-3 border-t border-nat pt-3 text-xs text-caramel">Motivo: {sale.cancelReason}</p>}</article>;})}{!state.sales.length&&<div className="rounded-2xl border border-dashed border-nat p-6 text-center"><Empty text="Nenhuma venda ou saída registrada ainda."/><button type="button" className="primary-button mt-4" onClick={onNew}><Plus size={16}/> Registrar primeira venda</button></div>}</div></div></section>{saleToCancel&&<CancelSaleDialog sale={saleToCancel} onClose={()=>setSaleToCancel(null)} onConfirm={(reason)=>{onCancel(saleToCancel.id,reason);setSaleToCancel(null);}}/>}</>;
}
