import { AlertTriangle, CircleDollarSign, Plus, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { buildSaleOrder, money, paymentFeeForMethod, paymentLabel, saleChannelLabel, transactionTypeLabel, type NatState, type PaymentMethod, type Sale, type SaleChannel, type TransactionType } from "@/domain/nat";
import { supabase } from "@/integrations/supabase/client";
import { useDialogA11y } from "@/hooks/use-dialog-a11y";

type DraftLine = { key:string; productId:string; quantity:string };
type SaleQuote={listTotal:number;totalCost:number;totalQuantity:number;variableFee:number;deliveryCost:number;contribution:number;marginPercent:number;belowCost:boolean};

function quoteFrom(value:unknown):SaleQuote{
  const row=(value&&typeof value==="object"?value:{}) as Record<string,unknown>;
  return {listTotal:Number(row.listTotal??0),totalCost:Number(row.totalCost??0),totalQuantity:Number(row.totalQuantity??0),variableFee:Number(row.variableFee??0),deliveryCost:Number(row.deliveryCost??0),contribution:Number(row.contribution??0),marginPercent:Number(row.marginPercent??0),belowCost:row.belowCost===true};
}

export function SaleOrderSheet({state,businessId,onClose,onSave}:{state:NatState;businessId:string|null;onClose:()=>void;onSave:(sale:Sale)=>void}){
  const initialProduct=state.products.find((product)=>product.available!==false&&product.recipe.length>0);const panelRef=useDialogA11y<HTMLDivElement>({onClose});
  const saleIdRef=useRef(crypto.randomUUID());const submittingRef=useRef(false);const [submitting,setSubmitting]=useState(false);
  const [lines,setLines]=useState<DraftLine[]>(initialProduct?[{key:crypto.randomUUID(),productId:initialProduct.id,quantity:"1"}]:[]);const [total,setTotal]=useState(initialProduct?String(initialProduct.sellingPrice):"");const [method,setMethod]=useState<PaymentMethod>("pix");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [customerId,setCustomerId]=useState("");const [transactionType,setTransactionType]=useState<TransactionType>("sale");const [channel,setChannel]=useState<SaleChannel>("other");const [delivery,setDelivery]=useState("0");const [discountReason,setDiscountReason]=useState("");const [belowCostOverride,setBelowCostOverride]=useState(false);const [error,setError]=useState("");const [quote,setQuote]=useState<SaleQuote|null>(null);const [quoteLoading,setQuoteLoading]=useState(false);const [quoteError,setQuoteError]=useState("");
  const productsForType=(type:TransactionType)=>state.products.filter((product)=>product.recipe.length>0&&(type!=="sale"||product.available!==false));
  const sellable=productsForType(transactionType);const customers=(state.customers??[]).filter((customer)=>customer.active);const paymentFee=paymentFeeForMethod(state.settings,method);
  const listTotal=useMemo(()=>lines.reduce((sum,line)=>{const product=state.products.find((candidate)=>candidate.id===line.productId);const quantity=Number(line.quantity.replace(",","."))||0;return sum+(product?.sellingPrice??0)*quantity;},0),[lines,state.products]);
  const received=transactionType==="sale"?(Number(total.replace(",","."))||0):0;const deliveryCost=transactionType==="sale"?(Number(delivery.replace(",","."))||0):0;const authoritativeListTotal=quote?.listTotal??listTotal;const adjustment=received-authoritativeListTotal;const hasAdjustment=transactionType==="sale"&&Math.abs(adjustment)>=0.005;const belowCost=Boolean(quote?.belowCost);const previewMargin=quote?.marginPercent??0;

  useEffect(()=>{
    let cancelled=false;setQuoteError("");
    const items=lines.map((line)=>({productId:line.productId,quantity:Number(line.quantity.replace(",","."))||0}));
    const valid=Boolean(businessId&&date&&items.length&&items.every((item)=>item.productId&&item.quantity>0&&Number.isInteger(item.quantity)&&state.products.some((product)=>product.id===item.productId&&product.recipe.length>0&&(transactionType!=="sale"||product.available!==false)))&&received>=0&&deliveryCost>=0);
    if(!valid){setQuote(null);setQuoteLoading(false);return;}
    setQuoteLoading(true);
    const timer=window.setTimeout(()=>{void (async()=>{
      const result=await supabase.rpc("quote_sale_v1" as never,{p_business_id:businessId,p_items:items,p_total_received:received,p_payment_method:method,p_sold_at:`${date}T12:00:00.000Z`,p_transaction_type:transactionType,p_delivery_cost:deliveryCost} as never);
      if(cancelled)return;
      if(result.error){setQuote(null);setQuoteError(result.error.message||"Não foi possível calcular esta movimentação.");setQuoteLoading(false);return;}
      setQuote(quoteFrom(result.data));setQuoteLoading(false);
    })();},180);
    return()=>{cancelled=true;window.clearTimeout(timer);};
  },[businessId,date,deliveryCost,lines,method,received,state.products,transactionType]);

  function suggestedTotal(next:DraftLine[]){return next.reduce((sum,line)=>{const product=state.products.find((candidate)=>candidate.id===line.productId);const quantity=Number(line.quantity.replace(",","."))||0;return sum+(product?.sellingPrice??0)*quantity;},0);}function updateLines(next:DraftLine[]){setError("");setLines(next);if(transactionType==="sale")setTotal(String(suggestedTotal(next)));}function addLine(){const used=new Set(lines.map((line)=>line.productId));const nextProduct=sellable.find((product)=>!used.has(product.id));if(nextProduct)updateLines([...lines,{key:crypto.randomUUID(),productId:nextProduct.id,quantity:"1"}]);}
  function changeTransactionType(next:TransactionType){const options=productsForType(next);let nextLines=lines.filter((line)=>options.some((product)=>product.id===line.productId));if(!nextLines.length&&options[0])nextLines=[{key:crypto.randomUUID(),productId:options[0].id,quantity:"1"}];setTransactionType(next);setLines(nextLines);setError("");setBelowCostOverride(false);setDiscountReason("");if(next!=="sale"){setTotal("0");setDelivery("0");}else setTotal(String(suggestedTotal(nextLines)));}
  function submit(event:React.FormEvent){event.preventDefault();if(submittingRef.current)return;setError("");if(!lines.length){setError("Adicione pelo menos um produto.");return;}const ids=lines.map((line)=>line.productId);if(new Set(ids).size!==ids.length){setError("O mesmo produto não pode aparecer duas vezes.");return;}const items=lines.map((line)=>({product:sellable.find((candidate)=>candidate.id===line.productId),quantity:Number(line.quantity.replace(",","."))||0}));if(items.some((item)=>!item.product||item.quantity<=0||!Number.isInteger(item.quantity))){setError("Use quantidades inteiras de brigadeiros e revise os produtos.");return;}if(received<0||deliveryCost<0||!date){setError("Revise valor, entrega e data.");return;}if(quoteLoading||!quote){setError(quoteError||"Aguarde o cálculo seguro desta movimentação antes de salvar.");return;}const reason=discountReason.trim();if(hasAdjustment&&reason.length<2){setError("Informe o motivo do desconto ou acréscimo com pelo menos 2 caracteres.");return;}if(belowCost&&(!belowCostOverride||reason.length<2)){setError("Para vender abaixo do custo, confirme conscientemente e informe um motivo com pelo menos 2 caracteres.");return;}submittingRef.current=true;setSubmitting(true);try{const optimisticReason=reason||"Validação autoritativa";const built=buildSaleOrder({items:items.map((item)=>({product:item.product!,quantity:item.quantity})),supplies:state.supplies,paymentFeePercent:paymentFee,totalReceived:received,paymentMethod:method,soldAt:`${date}T12:00:00.000Z`,customerId:customerId||null,transactionType,saleChannel:channel,deliveryCost,discountReason:optimisticReason,belowCostOverride:true});onSave({...built,id:saleIdRef.current,unitCostSnapshot:quote.totalQuantity>0?quote.totalCost/quote.totalQuantity:0,variableFeeSnapshot:quote.variableFee,contributionSnapshot:quote.contribution,discountReason:reason||null,belowCostOverride:transactionType==="sale"?belowCostOverride:false});}catch(cause){submittingRef.current=false;setSubmitting(false);setError(cause instanceof Error?cause.message:"Revise os dados antes de salvar.");}}
  return <div className="fixed inset-0 z-50 flex justify-end bg-[#35150A]/35 backdrop-blur-[2px]" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!submitting)onClose();}}><div ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="sale-order-title" className="h-full w-full max-w-xl overflow-y-auto bg-[#FFF9F6] p-5 pb-[max(24px,env(safe-area-inset-bottom))] pt-[max(20px,env(safe-area-inset-top))] shadow-2xl sm:p-7">
    <div className="flex items-start justify-between gap-4"><div><p className="eyebrow">NAT Gestão</p><h2 id="sale-order-title" className="mt-2 font-display text-4xl">Registrar movimento</h2><p className="mt-2 text-sm leading-6 text-caramel">A NAT calcula o impacto usando o mesmo custo histórico e de estoque que será gravado no banco.</p></div><button type="button" className="icon-button" onClick={onClose} disabled={submitting} aria-label="Fechar"><X size={20}/></button></div>
    <div className="mt-7">{sellable.length===0?<div className="rounded-2xl border border-dashed border-nat p-8 text-center text-sm text-caramel">{transactionType==="sale"?"Nenhum sabor disponível com receita completa.":"Nenhum produto ativo com receita completa."}</div>:<form className="space-y-5" onSubmit={submit}>
      <div><label className="field-label" htmlFor="movement-type">Tipo</label><select id="movement-type" className="nat-input" value={transactionType} onChange={(e)=>changeTransactionType(e.target.value as TransactionType)} disabled={submitting}>{(["sale","courtesy","personal_consumption","loss"] as TransactionType[]).map((type)=><option key={type} value={type}>{transactionTypeLabel[type]}</option>)}</select>{transactionType!=="sale"&&<p className="field-help">Mantém custo e quantidade, mas não entra em faturamento ou recompra. Produtos pausados continuam disponíveis para registrar a saída correta do estoque.</p>}</div>
      <div><label className="field-label" htmlFor="sale-customer">Cliente</label><select id="sale-customer" className="nat-input" value={customerId} onChange={(e)=>setCustomerId(e.target.value)} disabled={submitting}><option value="">Cliente não identificado</option>{customers.map((customer)=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></div>
      {transactionType==="sale"&&<div><label className="field-label" htmlFor="sale-channel">Canal desta venda</label><select id="sale-channel" className="nat-input" value={channel} onChange={(e)=>setChannel(e.target.value as SaleChannel)} disabled={submitting}>{(["whatsapp","instagram","street","referral","in_person","other"] as SaleChannel[]).map((value)=><option key={value} value={value}>{saleChannelLabel[value]}</option>)}</select><p className="field-help">A origem do cliente continua separada; aqui registramos por onde esta compra aconteceu.</p></div>}
      <div><div className="flex items-center justify-between gap-3"><div><p className="field-label">Produtos</p><p className="field-help">Adicione todos os sabores do pedido.</p></div><button type="button" className="secondary-button shrink-0" onClick={addLine} disabled={submitting||lines.length>=sellable.length}><Plus size={16}/> Adicionar</button></div><div className="mt-3 space-y-3">{lines.map((line,index)=>{const usedByOthers=new Set(lines.filter((candidate)=>candidate.key!==line.key).map((candidate)=>candidate.productId));return <div key={line.key} className="grid grid-cols-[minmax(0,1fr)_82px_42px] gap-2 rounded-2xl bg-soft p-3"><select className="nat-input" aria-label={`Produto ${index+1}`} value={line.productId} disabled={submitting} onChange={(event)=>updateLines(lines.map((candidate)=>candidate.key===line.key?{...candidate,productId:event.target.value}:candidate))}>{sellable.filter((product)=>!usedByOthers.has(product.id)||product.id===line.productId).map((product)=><option key={product.id} value={product.id}>{product.name}</option>)}</select><input className="nat-input" inputMode="numeric" aria-label={`Quantidade ${index+1}`} value={line.quantity} disabled={submitting} onChange={(event)=>updateLines(lines.map((candidate)=>candidate.key===line.key?{...candidate,quantity:event.target.value}:candidate))}/><button type="button" className="icon-button" disabled={submitting||lines.length===1} onClick={()=>updateLines(lines.filter((candidate)=>candidate.key!==line.key))} aria-label="Remover produto"><Trash2 size={16}/></button></div>;})}</div></div>
      {transactionType==="sale"&&<><div className="rounded-2xl bg-rose-soft p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-bold">Preço de tabela</span><strong className="font-display text-2xl">{money(authoritativeListTotal)}</strong></div></div><div><label htmlFor="sale-total" className="field-label">Valor realmente recebido</label><input id="sale-total" className="nat-input" inputMode="decimal" value={total} disabled={submitting} onChange={(event)=>setTotal(event.target.value)}/>{hasAdjustment&&<p className="mt-2 text-sm text-caramel">{adjustment<0?"Desconto":"Acréscimo"}: <strong>{money(Math.abs(adjustment))}</strong></p>}</div><div><label htmlFor="sale-delivery" className="field-label">Custo de entrega desta venda</label><input id="sale-delivery" className="nat-input" inputMode="decimal" value={delivery} disabled={submitting} onChange={(event)=>setDelivery(event.target.value)}/><p className="field-help">Ex.: motoboy. Esse valor reduz o resultado desta venda, sem mudar o custo da receita.</p></div>{hasAdjustment&&<div><label htmlFor="discount-reason" className="field-label">Motivo do ajuste</label><input id="discount-reason" className="nat-input" value={discountReason} minLength={2} maxLength={500} disabled={submitting} onChange={(event)=>setDiscountReason(event.target.value)} placeholder="Ex.: promoção de lançamento"/><p className="field-help">Use pelo menos 2 caracteres.</p></div>}<fieldset disabled={submitting}><legend className="field-label">Como recebeu?</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{(["pix","cash","card","other"] as PaymentMethod[]).map((item)=><button key={item} type="button" aria-pressed={method===item} className={`choice-button ${method===item?"active":""}`} onClick={()=>setMethod(item)}>{paymentLabel[item]}</button>)}</div>{paymentFee>0&&<p className="field-help">Taxa configurada para {paymentLabel[method]}: {paymentFee}%.</p>}</fieldset></>}
      <div><label htmlFor="sale-date" className="field-label">Data</label><input id="sale-date" type="date" className="nat-input" value={date} disabled={submitting} onChange={(event)=>setDate(event.target.value)} required/></div>
      {quoteLoading&&<p role="status" className="rounded-xl bg-soft p-3 text-sm text-caramel">Calculando custo e margem no banco...</p>}{quoteError&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{quoteError}</p>}{quote&&<div className={`rounded-2xl p-4 ${belowCost?"border border-red-200 bg-red-50":"bg-rose-soft"}`}><div className="flex items-start gap-3">{belowCost&&<AlertTriangle className="mt-1 shrink-0 text-red-700" size={20}/>}<div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wider text-caramel">Impacto desta movimentação</p><p className={`mt-1 font-display text-3xl ${belowCost?"text-red-700":""}`}>{money(quote.contribution)}</p><p className="mt-1 text-sm text-caramel">Margem real: {new Intl.NumberFormat("pt-BR",{maximumFractionDigits:1}).format(previewMargin)}% · Entrega: {money(quote.deliveryCost)} · Taxa: {money(quote.variableFee)}</p>{belowCost&&<label className="mt-4 flex items-start gap-3 rounded-xl bg-white p-3 text-sm font-bold"><input type="checkbox" className="mt-1" checked={belowCostOverride} disabled={submitting} onChange={(e)=>setBelowCostOverride(e.target.checked)}/><span>Confirmo que quero registrar esta venda mesmo ficando abaixo do custo.</span></label>}</div></div></div>}
      {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="primary-button w-full justify-center" type="submit" disabled={submitting||quoteLoading||!quote}><CircleDollarSign size={18}/> {submitting?"Salvando...":quoteLoading?"Calculando...":"Salvar"}</button>
    </form>}</div>
  </div></div>;
}