import { createHmac } from "node:crypto";
import { expect, test, type Page } from "@playwright/test";

const email="operations@example.test";
const password=["NAT","RLS","e2e","2026!"].join("-");
test.describe.configure({retries:0});
function decodeBase32(value:string){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";const normalized=value.toUpperCase().replace(/=+$/g,"").replace(/\s+/g,"");let bits="";for(const char of normalized){const index=alphabet.indexOf(char);if(index<0)throw new Error("Invalid base32 secret");bits+=index.toString(2).padStart(5,"0");}const bytes:number[]=[];for(let index=0;index+8<=bits.length;index+=8)bytes.push(Number.parseInt(bits.slice(index,index+8),2));return Buffer.from(bytes);}
function totp(secret:string,now=Date.now()){const counter=Math.floor(now/1000/30);const buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const digest=createHmac("sha1",decodeBase32(secret)).update(buffer).digest();const offset=digest[digest.length-1]&0x0f;const code=((digest[offset]&0x7f)<<24)|((digest[offset+1]&0xff)<<16)|((digest[offset+2]&0xff)<<8)|(digest[offset+3]&0xff);return String(code%1_000_000).padStart(6,"0");}
async function login(page:Page){await page.goto("/login",{waitUntil:"domcontentloaded"});await expect(page.getByRole("heading",{name:"Bem-vinda de volta"})).toBeVisible({timeout:30_000});await page.getByLabel("E-mail").fill(email);await page.getByLabel("Senha").fill(password);await page.getByRole("button",{name:"Entrar"}).click();await expect(page.getByRole("heading",{name:"Ative a proteção extra"})).toBeVisible({timeout:30_000});const secret=(await page.locator("p.break-all").textContent())?.trim();expect(secret).toBeTruthy();await page.getByLabel("Código de segurança").fill(totp(secret!));await page.getByRole("button",{name:"Ativar e entrar"}).click();await page.waitForURL(/\/dashboard/,{timeout:30_000});}
async function waitForSaved(page:Page,message:string|RegExp){await expect(page.getByText(message)).toBeVisible({timeout:20_000});}
function tomorrow(date:string){const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+1);return value.toISOString().slice(0,10);}

test("fluxos operacionais e fiado persistem após reload",async({page})=>{
  test.setTimeout(300_000);await login(page);
  await page.goto("/dashboard?view=sales");await expect(page.getByRole("heading",{name:"Vendas e saídas"})).toBeVisible({timeout:30_000});await page.getByRole("button",{name:"Registrar venda ou saída"}).click();let saleDialog=page.getByRole("dialog",{name:"Registrar venda ou saída"});await saleDialog.getByLabel("Produto 1",{exact:true}).selectOption({label:"Produto E2E Venda"});await saleDialog.getByLabel("Quantidade do produto 1",{exact:true}).fill("2");await expect(saleDialog.getByText("Resumo antes de salvar")).toBeVisible({timeout:20_000});await saleDialog.getByRole("button",{name:"Registrar venda"}).click();await expect(saleDialog).toBeHidden({timeout:30_000});await expect(page.getByText(/Venda registrada:/)).toBeVisible();await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText("Produto E2E Venda",{exact:true})).toBeVisible({timeout:20_000});await page.getByRole("button",{name:/Cancelar/}).first().click();const cancel=page.getByRole("dialog",{name:"Cancelar venda ou saída"});await cancel.getByLabel("Motivo do cancelamento").fill("Validação E2E de cancelamento");await cancel.getByRole("button",{name:"Cancelar movimento"}).click();await waitForSaved(page,"Venda ou saída cancelada e mantida no histórico.");

  await page.goto("/dashboard?view=customers");await expect(page.getByRole("heading",{name:"Fichas de clientes"})).toBeVisible({timeout:30_000});await page.getByRole("button",{name:"Nova ficha"}).click();let customerDialog=page.getByRole("dialog",{name:"Novo cliente"});await customerDialog.getByLabel("Nome").fill("Cliente E2E");await customerDialog.getByLabel("Origem").fill("WhatsApp");await customerDialog.getByRole("button",{name:"Salvar ficha"}).click();await expect(customerDialog.getByRole("alert")).toContainText("telefone");await customerDialog.getByLabel("Telefone").fill("11999999999");await customerDialog.getByRole("button",{name:"Salvar ficha"}).click();await expect(customerDialog).toBeHidden({timeout:30_000});await waitForSaved(page,"Cliente Cliente E2E salvo.");

  await page.goto("/dashboard?view=sales");await page.getByRole("button",{name:"Registrar venda ou saída"}).click();saleDialog=page.getByRole("dialog",{name:"Registrar venda ou saída"});await saleDialog.getByLabel("Produto 1",{exact:true}).selectOption({label:"Produto E2E Venda"});await saleDialog.getByRole("button",{name:"Vai pagar depois"}).click();const saleDate=await saleDialog.locator("#sale-date").inputValue();await saleDialog.getByLabel("Data prometida").fill(saleDate);await expect(saleDialog.getByLabel("Horário prometido")).toBeVisible();await expect(saleDialog.getByText("Resumo antes de salvar")).toBeVisible({timeout:20_000});await saleDialog.getByRole("button",{name:"Registrar venda"}).click();await expect(saleDialog.getByRole("alert")).toContainText("cliente cadastrado");await saleDialog.getByLabel(/Cliente/).selectOption({label:"Cliente E2E"});await saleDialog.getByRole("button",{name:"Registrar venda"}).click();await expect(saleDialog.getByRole("alert")).toContainText("horário");await saleDialog.getByLabel("Horário prometido").fill("23:00");await saleDialog.getByRole("button",{name:"Registrar venda"}).click();await expect(saleDialog).toBeHidden({timeout:30_000});await waitForSaved(page,/pagamento pendente/);await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText("Pagamento pendente",{exact:true})).toBeVisible({timeout:30_000});await page.getByRole("button",{name:"Marcar como pago"}).click();await expect(page.getByRole("heading",{name:"Vendas e saídas"})).toBeVisible({timeout:30_000});await expect(page.getByRole("button",{name:"Marcar como pago"})).toHaveCount(0,{timeout:30_000});

  await page.getByRole("button",{name:"Registrar venda ou saída"}).click();saleDialog=page.getByRole("dialog",{name:"Registrar venda ou saída"});await saleDialog.getByLabel("Produto 1",{exact:true}).selectOption({label:"Produto E2E Venda"});await saleDialog.getByRole("button",{name:"Vai pagar depois"}).click();await saleDialog.getByLabel(/Cliente/).selectOption({label:"Cliente E2E"});const secondSaleDate=await saleDialog.locator("#sale-date").inputValue();await saleDialog.getByLabel("Data prometida").fill(tomorrow(secondSaleDate));await expect(saleDialog.getByLabel("Horário prometido")).toHaveCount(0);await expect(saleDialog.getByText("Resumo antes de salvar")).toBeVisible({timeout:20_000});await saleDialog.getByRole("button",{name:"Registrar venda"}).click();await expect(saleDialog).toBeHidden({timeout:30_000});await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText("Pagamento pendente",{exact:true})).toBeVisible({timeout:30_000});

  await page.goto("/dashboard?view=customers");await page.getByRole("button",{name:/Cliente E2E/}).click();customerDialog=page.getByRole("dialog",{name:"Cliente E2E"});await expect(customerDialog.getByText("Comportamento de pagamento")).toBeVisible();await expect(customerDialog.getByText("Pagamento combinado",{exact:true})).toBeVisible();await expect(customerDialog.getByText("Histórico de compras")).toBeVisible();await customerDialog.getByRole("button",{name:"Fechar"}).click();

  await page.goto("/dashboard?view=products");await expect(page.getByRole("heading",{name:"Produtos e compras"})).toBeVisible({timeout:30_000});await page.getByRole("tab",{name:"Compras e insumos"}).click();await page.getByRole("button",{name:"Registrar nova compra"}).click();const supplyDialog=page.getByRole("dialog",{name:"Registrar compra"});await supplyDialog.getByLabel("O que você comprou?").fill("Insumo E2E");await supplyDialog.getByLabel("Quanto veio?").fill("100");await supplyDialog.getByLabel("Unidade").selectOption("g");await supplyDialog.getByLabel("Valor pago em reais").fill("10,00");await supplyDialog.getByRole("button",{name:"Salvar compra"}).click();await waitForSaved(page,"Compra de Insumo E2E salva.");await page.reload({waitUntil:"domcontentloaded"});await page.getByRole("tab",{name:"Compras e insumos"}).click();await expect(page.getByText("Insumo E2E",{exact:true})).toBeVisible({timeout:20_000});
  await page.getByRole("tab",{name:"Gastos extras"}).click();await page.getByRole("button",{name:"Registrar novo gasto"}).click();const expenseDialog=page.getByRole("dialog",{name:"Registrar gasto extra"});await expenseDialog.getByLabel("O que foi pago?").fill("Gasto E2E");await expenseDialog.getByLabel("Valor pago").fill("7,50");await expenseDialog.getByRole("button",{name:"Salvar gasto"}).click();await waitForSaved(page,"Gasto “Gasto E2E” salvo.");
  await page.goto("/dashboard?view=calendar");await expect(page.locator("h1",{hasText:"Agenda"})).toBeVisible({timeout:30_000});await page.getByRole("button",{name:"Novo compromisso"}).click();const calendarDialog=page.getByRole("dialog",{name:"Novo compromisso"});await calendarDialog.getByLabel("Título").fill("Compromisso E2E");await calendarDialog.getByLabel("Receber lembrete",{exact:false}).uncheck();await calendarDialog.getByRole("button",{name:"Adicionar à agenda"}).click();await page.reload({waitUntil:"domcontentloaded"});await expect(page.getByText("Compromisso E2E",{exact:true})).toBeVisible({timeout:20_000});
});
