import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useNatStore } from "@/hooks/use-nat-store";
import { useInventory } from "@/hooks/use-inventory";
import { useCalendar } from "@/hooks/use-calendar";
import { dashboardNumbers, id, money, type Customer, type OwnerCashMovement, type Product, type Sale, type Settings, type SporadicExpense, type Supply } from "@/domain/nat";
import type { CatalogItem, StarterSupply } from "@/domain/catalog";
import { AppShell, Brand, type NatView } from "@/components/nat/AppShell";
import { HomeView, PricingView } from "@/components/nat/Views";
import { HomeOperations } from "@/components/nat/HomeOperations";
import { IntegrationHealthPanel } from "@/components/nat/IntegrationHealthPanel";
import { GlobalSearchSheet } from "@/components/nat/GlobalSearchSheet";
import { ProductsView, type ProductTab } from "@/components/nat/ProductsView";
import { SalesHistoryView } from "@/components/nat/SalesHistoryView";
import { SaleOrderSheet } from "@/components/nat/SaleOrderSheet";
import { CustomersView } from "@/components/nat/CustomersView";
import { IntelligenceWorkbench } from "@/components/nat/IntelligenceWorkbench";
import { PortfolioHierarchyView } from "@/components/nat/PortfolioHierarchyView";
import { BrandGuideView } from "@/components/nat/BrandGuideView";
import { CalendarView } from "@/components/nat/CalendarView";
import { InventoryView } from "@/components/nat/InventoryView";
import { StatusToast, type AppNotice } from "@/components/nat/Feedback";
import { SupplySheet } from "@/components/nat/SupplySheet";
import { SettingsSheet } from "@/components/nat/Sheets";
import { ProductEditorSheet } from "@/components/nat/ProductEditorSheet";
import { ExpenseEditorSheet } from "@/components/nat/ExpenseEditorSheet";
import { OwnerCashMovementSheet } from "@/components/nat/OwnerCashMovementSheet";
import { installGlobalDiagnostics, recordDiagnostic } from "@/lib/telemetry";

type Sheet=|{type:"sale";preset?:Sale}|{type:"supply";value?:Supply;preset?:StarterSupply}|{type:"product";value?:Product;preset?:CatalogItem}|{type:"expense";value?:SporadicExpense;presetName?:string}|{type:"ownerCash";value?:OwnerCashMovement}|{type:"settings"}|{type:"search"}|null;

export function NatApp({view,onView}:{view:NatView;onView:(view:NatView)=>void}){
  const{state,update,setProductAvailability,refresh,ensureFullHistory,historyLoaded,ready,loadError,syncNotice,clearSyncNotice,syncRevision,businessId}=useNatStore();const inventory=useInventory(businessId,syncRevision);const homeCalendar=useCalendar(view==="home");const[productTab,setProductTab]=useState<ProductTab>("products");const[sheet,setSheet]=useState<Sheet>(null);const[localNotice,setLocalNotice]=useState<AppNotice>(null);const dedupeRef=useRef(new Map<string,number>());const numbers=useMemo(()=>dashboardNumbers(state),[state]);
  useEffect(()=>installGlobalDiagnostics(),[]);useEffect(()=>{if(loadError)recordDiagnostic(`Falha ao carregar dados: ${loadError}`);},[loadError]);useEffect(()=>{if(!ready||historyLoaded||!["sales","customers","intelligence"].includes(view))return;void ensureFullHistory().catch((error)=>{recordDiagnostic(`Falha ao carregar histórico completo: ${error instanceof Error?error.message:"erro desconhecido"}`);setLocalNotice({tone:"error",message:"Não foi possível carregar todo o histórico. Os dados recentes continuam disponíveis."});});},[ensureFullHistory,historyLoaded,ready,view]);
  if(!ready)return <div className="min-h-screen grid place-items-center bg-cream"><div className="space-y-4 text-center"><Brand/><p className="text-sm text-caramel" role="status">Carregando dados protegidos...</p></div></div>;if(loadError)return <div className="min-h-screen grid place-items-center bg-cream p-5"><div className="nat-card max-w-md text-center"><div className="mx-auto w-fit"><Brand/></div><h1 className="mt-6 font-display text-3xl">Não conseguimos abrir seus dados</h1><p className="mt-2 text-sm leading-6 text-caramel">{loadError}</p><button type="button" className="primary-button mt-5 w-full justify-center" onClick={refresh}>Tentar novamente</button></div></div>;
  const acceptOnce=(key:string)=>{const now=Date.now();const previous=dedupeRef.current.get(key)??0;if(now-previous<1600)return false;dedupeRef.current.set(key,now);return true;};const homeState={...state,sales:state.sales.filter((sale)=>sale.status!=="cancelled")};const openProducts=(tab:ProductTab)=>{setProductTab(tab);onView("products");};const logout=()=>void supabase.auth.signOut().finally(()=>{window.location.href="/";});const notice=localNotice??inventory.notice??syncNotice;const dismissNotice=()=>{if(localNotice)setLocalNotice(null);else if(inventory.notice)inventory.clearNotice();else clearSyncNotice();};
  const saveCustomer=(customer:Customer)=>{if(!acceptOnce(`customer:${customer.id}:${customer.updatedAt}`))return;update((current)=>({...current,customers:(current.customers??[]).some((item)=>item.id===customer.id)?(current.customers??[]).map((item)=>item.id===customer.id?customer:item):[...(current.customers??[]),customer]}),{message:`Cliente ${customer.name} salvo.`});};const saveOwnerCash=(movement:OwnerCashMovement)=>{if(!acceptOnce(`cash:${movement.id}`))return;update((current)=>({...current,ownerCashMovements:(current.ownerCashMovements??[]).some((item)=>item.id===movement.id)?(current.ownerCashMovements??[]).map((item)=>item.id===movement.id?movement:item):[movement,...(current.ownerCashMovements??[])]}),{message:"Movimento de caixa salvo."});};
  const deleteSupply=(supplyId:string)=>{const supply=state.supplies.find((item)=>item.id===supplyId);if(!supply)return;const used=state.products.some((product)=>product.recipe.some((item)=>item.supplyId===supplyId));if(used){setLocalNotice({tone:"error",message:"Esse item está em uma receita ativa. Retire-o do produto antes de arquivar."});return;}update((current)=>({...current,supplies:current.supplies.filter((item)=>item.id!==supplyId)}),{message:`${supply.name} arquivado.`,actionLabel:"Desfazer",onAction:()=>update((current)=>({...current,supplies:[...current.supplies,supply]}),{message:`${supply.name} restaurado.`})});};
  const deleteProduct=(productId:string)=>{const product=state.products.find((item)=>item.id===productId);if(!product)return;update((current)=>({...current,products:current.products.filter((item)=>item.id!==productId)}),{message:`${product.name} arquivado.`,actionLabel:"Desfazer",onAction:()=>update((current)=>({...current,products:[...current.products,product]}),{message:`${product.name} restaurado.`})});};
  const deleteExpense=(expenseId:string)=>{const expense=state.expenses.find((item)=>item.id===expenseId);if(!expense)return;update((current)=>({...current,expenses:current.expenses.filter((item)=>item.id!==expenseId)}),{message:`Gasto “${expense.name}” excluído.`,actionLabel:"Desfazer",onAction:()=>update((current)=>({...current,expenses:[expense,...current.expenses]}),{message:`Gasto “${expense.name}” restaurado.`})});};
  return <AppShell view={view} onView={onView} onSale={()=>setSheet({type:"sale"})} onSearch={()=>setSheet({type:"search"})} onSettings={()=>setSheet({type:"settings"})} onLogout={logout}><StatusToast notice={notice} onDismiss={dismissNotice}/>
    {view==="home"&&<div className="space-y-6"><HomeOperations state={homeState} events={homeCalendar.events} inventory={inventory.snapshot} onSale={()=>setSheet({type:"sale"})} onRepeatSale={(sale)=>setSheet({type:"sale",preset:sale})} onSearch={()=>setSheet({type:"search"})} onSupplies={()=>openProducts("supplies")} onProducts={()=>openProducts("products")} onPricing={()=>onView("pricing")} onCalendar={()=>onView("calendar")} onInventory={()=>onView("inventory")} onCustomers={()=>onView("customers")}/><details className="nat-card"><summary className="cursor-pointer font-bold">Financeiro detalhado <span className="font-normal text-caramel">(opcional)</span></summary><div className="mt-5"><HomeView state={homeState} numbers={numbers} onSale={()=>setSheet({type:"sale"})} onPricing={()=>onView("pricing")} onCashMovement={()=>setSheet({type:"ownerCash"})}/></div></details><details className="nat-card"><summary className="cursor-pointer text-sm font-bold text-caramel">Saúde técnica e integrações</summary><div className="mt-4"><IntegrationHealthPanel businessId={businessId}/></div></details></div>}
    {view==="sales"&&<SalesHistoryView state={state} onNew={()=>setSheet({type:"sale"})} onCancel={(saleId,reason)=>{if(!acceptOnce(`cancel-sale:${saleId}`))return;update((current)=>({...current,sales:current.sales.map((sale)=>sale.id===saleId?{...sale,status:"cancelled",cancelReason:reason,cancelledAt:new Date().toISOString()}:sale)}),{message:"Venda ou saída cancelada e mantida no histórico."});}}/>}{view==="customers"&&<CustomersView state={state} onSave={saveCustomer}/>} {view==="intelligence"&&<IntelligenceWorkbench state={state} inventory={inventory.snapshot} businessId={businessId}/>} {view==="calendar"&&<CalendarView/>}{view==="inventory"&&<InventoryView state={state} snapshot={inventory.snapshot} loading={inventory.loading} error={inventory.error} onRetry={inventory.reload} onSetBalance={inventory.setBalance} onProduction={inventory.registerProduction}/>} {view==="portfolio"&&<PortfolioHierarchyView state={state} onConfigure={(preset)=>setSheet({type:"product",preset})} onEdit={(value)=>setSheet({type:"product",value})} onAvailability={(product,available)=>setProductAvailability(product.id,available)} onPricing={()=>onView("pricing")}/>} 
    {view==="products"&&<ProductsView state={state} tab={productTab} onTab={setProductTab} onNewSupply={(preset)=>setSheet({type:"supply",preset})} onEditSupply={(value)=>setSheet({type:"supply",value})} onDeleteSupply={deleteSupply} onNewProduct={(preset)=>setSheet({type:"product",preset})} onEditProduct={(value)=>setSheet({type:"product",value})} onDuplicateProduct={(product)=>{const copy={...product,id:id("product"),name:`${product.name} (cópia)`,portfolioKey:null,available:true};if(!acceptOnce(`duplicate:${product.id}`))return;update((current)=>({...current,products:[...current.products,copy]}),{message:`Cópia de ${product.name} criada.`,actionLabel:"Editar cópia",onAction:()=>setSheet({type:"product",value:copy})});}} onDeleteProduct={deleteProduct} onNewExpense={(presetName)=>setSheet({type:"expense",presetName})} onEditExpense={(value)=>setSheet({type:"expense",value})} onDeleteExpense={deleteExpense}/>} {view==="pricing"&&<PricingView state={state} onProducts={()=>openProducts("products")}/>} {view==="identity"&&<BrandGuideView/>}
    {sheet?.type==="sale"&&<SaleOrderSheet state={state} businessId={businessId} preset={sheet.preset} onClose={()=>setSheet(null)} onSave={(sale)=>{if(!acceptOnce(`sale:${sale.id}`))return;update((current)=>({...current,sales:[sale,...current.sales]}),{message:(sale.transactionType??"sale")==="sale"?`Venda registrada: ${money(sale.totalReceived)}.`:"Saída registrada.",actionLabel:"Ver histórico",onAction:()=>onView("sales")});setSheet(null);}}/>}
    {sheet?.type==="supply"&&<SupplySheet value={sheet.value} preset={sheet.preset} recentSupplies={state.supplies} onClose={()=>setSheet(null)} onSave={(supply)=>{const fingerprint=`supply:${supply.name}:${supply.packageQuantity}:${supply.packagePrice}:${supply.purchasedAt}`;if(!acceptOnce(fingerprint))return;const isNew=!state.supplies.some((item)=>item.id===supply.id);update((current)=>({...current,supplies:current.supplies.some((item)=>item.id===supply.id)?current.supplies.map((item)=>item.id===supply.id?supply:item):[...current.supplies,supply]}),{message:`Compra de ${supply.name} salva.`,actionLabel:isNew?"Usar em uma receita":undefined,onAction:isNew?()=>openProducts("products"):undefined});setSheet(null);}}/>}
    {sheet?.type==="product"&&<ProductEditorSheet state={state} value={sheet.value} preset={sheet.preset} onClose={()=>setSheet(null)} onSave={(product)=>{const fingerprint=`product:${product.id}:${product.name}:${product.batchYield}:${product.sellingPrice}:${product.recipe.length}`;if(!acceptOnce(fingerprint))return;update((current)=>({...current,products:current.products.some((item)=>item.id===product.id)?current.products.map((item)=>item.id===product.id?{...product,available:item.available}:item):[...current.products,{...product,available:true}]}),{message:`Produto ${product.name} salvo.`,actionLabel:"Conferir preço",onAction:()=>onView("pricing")});setSheet(null);}}/>}
    {sheet?.type==="expense"&&<ExpenseEditorSheet value={sheet.value} presetName={sheet.presetName} onClose={()=>setSheet(null)} onSave={(expense)=>{const fingerprint=`expense:${expense.id}:${expense.name}:${expense.amount}:${expense.spentAt}`;if(!acceptOnce(fingerprint))return;update((current)=>({...current,expenses:current.expenses.some((item)=>item.id===expense.id)?current.expenses.map((item)=>item.id===expense.id?expense:item):[expense,...current.expenses]}),{message:`Gasto “${expense.name}” salvo.`});setSheet(null);}}/>}
    {sheet?.type==="ownerCash"&&<OwnerCashMovementSheet value={sheet.value} onClose={()=>setSheet(null)} onSave={(movement)=>{saveOwnerCash(movement);setSheet(null);}}/>}{sheet?.type==="settings"&&<SettingsSheet value={state.settings} onClose={()=>setSheet(null)} onSave={(settings:Settings)=>{update((current)=>({...current,settings}),{message:"Configurações salvas."});setSheet(null);}} onRefresh={refresh}/>} {sheet?.type==="search"&&<GlobalSearchSheet state={state} onClose={()=>setSheet(null)} onView={onView} onSale={()=>setSheet({type:"sale"})} onSupply={()=>setSheet({type:"supply"})}/>} 
  </AppShell>;
}
