-- Privacy/LGPD hardening for the Lovable Cloud PostgreSQL backend.
begin;

create table if not exists public.customer_marketing_consents (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  customer_id uuid not null,
  status text not null check (status in ('granted','revoked','expired')),
  source text not null,
  notice_version text not null,
  actor_user_id uuid,
  occurred_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists customer_marketing_consents_lookup_idx on public.customer_marketing_consents(business_id,customer_id,occurred_at desc,id desc);
alter table public.customer_marketing_consents enable row level security;
alter table public.customer_marketing_consents force row level security;
drop policy if exists customer_marketing_consents_select_member on public.customer_marketing_consents;
create policy customer_marketing_consents_select_member on public.customer_marketing_consents for select to authenticated using (private.is_business_member(business_id));
revoke all on public.customer_marketing_consents from anon;
grant select on public.customer_marketing_consents to authenticated;

create table if not exists public.privacy_request_log (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  customer_id uuid,
  request_type text not null check (request_type in ('erasure','retention_erasure','consent_expiry')),
  result text not null check (result in ('completed','skipped','failed')),
  reason text,
  actor_user_id uuid,
  created_at timestamptz not null default now()
);
create index if not exists privacy_request_log_business_created_idx on public.privacy_request_log(business_id,created_at desc);
alter table public.privacy_request_log enable row level security;
alter table public.privacy_request_log force row level security;
drop policy if exists privacy_request_log_select_member on public.privacy_request_log;
create policy privacy_request_log_select_member on public.privacy_request_log for select to authenticated using (private.is_business_member(business_id));
revoke all on public.privacy_request_log from anon;
grant select on public.privacy_request_log to authenticated;

create or replace function private.customer_audit_payload(p_row jsonb)
returns jsonb language sql immutable set search_path='' as $$
  select case when p_row is null then null else jsonb_strip_nulls(jsonb_build_object(
    'id',p_row->'id','business_id',p_row->'business_id','active',p_row->'active','created_at',p_row->'created_at','updated_at',p_row->'updated_at'
  )) end;
$$;

create or replace function private.audit_row_change()
returns trigger language plpgsql security definer set search_path='' as $$
declare
  v_before jsonb; v_after jsonb; v_row_source jsonb; v_business_id uuid; v_entity_id uuid; v_audit_source text; v_request_text text; v_request_id uuid; v_change_reason text; v_actor_type text; v_app_version text;
begin
  if tg_op='INSERT' then v_after:=to_jsonb(new);v_row_source:=v_after;
  elsif tg_op='UPDATE' then v_before:=to_jsonb(old);v_after:=to_jsonb(new);v_row_source:=v_after;
  else v_before:=to_jsonb(old);v_row_source:=v_before;end if;
  if tg_table_name='customers' then v_before:=private.customer_audit_payload(v_before);v_after:=private.customer_audit_payload(v_after);end if;
  v_entity_id:=nullif(coalesce(v_row_source->>'id',v_row_source->>'user_id',v_row_source->>'business_id'),'')::uuid;
  if tg_table_name='businesses' then v_business_id:=case when tg_op='DELETE' then null else nullif(v_row_source->>'id','')::uuid end; else v_business_id:=nullif(v_row_source->>'business_id','')::uuid; end if;
  v_audit_source:=nullif(left(btrim(coalesce(current_setting('app.audit_source',true),'')),40),'');
  if v_audit_source is null then v_audit_source:=case when auth.uid() is null then 'system' else 'application' end;end if;
  v_request_text:=nullif(btrim(coalesce(current_setting('app.audit_request_id',true),'')),'');
  if v_request_text is not null then begin v_request_id:=v_request_text::uuid;exception when invalid_text_representation then v_request_id:=null;end;end if;
  v_change_reason:=nullif(left(btrim(coalesce(current_setting('app.audit_reason',true),'')),500),'');
  v_app_version:=nullif(left(btrim(coalesce(current_setting('app.app_version',true),'')),80),'');
  v_actor_type:=nullif(btrim(coalesce(current_setting('app.audit_actor_type',true),'')),'');
  if v_actor_type is null or v_actor_type not in ('user','system','service') then v_actor_type:=case when auth.uid() is null then 'system' else 'user' end;end if;
  insert into public.audit_log(business_id,actor_user_id,action,entity_table,entity_id,before_data,after_data,source,request_id,change_reason,actor_type,app_version)
  values(v_business_id,auth.uid(),tg_op,tg_table_name,v_entity_id,v_before,v_after,v_audit_source,v_request_id,v_change_reason,v_actor_type,v_app_version);
  return coalesce(new,old);
end;$$;

update public.audit_log set before_data=private.customer_audit_payload(before_data),after_data=private.customer_audit_payload(after_data) where entity_table='customers';

insert into public.customer_marketing_consents(business_id,customer_id,status,source,notice_version,actor_user_id,occurred_at,expires_at)
select c.business_id,c.id,case when c.marketing_consent then 'granted' else 'revoked' end,'legacy_state','legacy-unknown',null,c.updated_at,case when c.marketing_consent then c.updated_at+interval '24 months' else null end
from public.customers c
where not exists(select 1 from public.customer_marketing_consents m where m.business_id=c.business_id and m.customer_id=c.id);

create or replace function public.save_customer(p_business_id uuid,p_id uuid,p_name text,p_phone text default null,p_instagram text default null,p_source text default null,p_marketing_consent boolean default false,p_notes text default null,p_active boolean default true)
returns void language plpgsql security definer set search_path='' as $$
declare v_previous_consent boolean;v_exists boolean;v_notes text:=nullif(btrim(coalesce(p_notes,'')),'');
begin
  if not private.is_business_member(p_business_id) then raise exception 'Acesso negado.' using errcode='42501';end if;
  if p_id is null or char_length(btrim(coalesce(p_name,''))) not between 1 and 160 then raise exception 'Dados do cliente inválidos.' using errcode='22023';end if;
  if v_notes is not null and char_length(v_notes)>500 then raise exception 'Observações devem ter no máximo 500 caracteres.' using errcode='22023';end if;
  if v_notes is not null and (v_notes ~ '([0-9]{3}[.][0-9]{3}[.][0-9]{3}-[0-9]{2})|([0-9]{2}[.][0-9]{3}[.][0-9]{3}/[0-9]{4}-[0-9]{2})|(^|[^0-9])[0-9]{11}([^0-9]|$)|(^|[^0-9])[0-9]{14}([^0-9]|$)') then raise exception 'Não registre CPF/CNPJ nas observações.' using errcode='22023';end if;
  select true,marketing_consent into v_exists,v_previous_consent from public.customers where id=p_id and business_id=p_business_id;
  insert into public.customers(id,business_id,name,phone,instagram,source,marketing_consent,notes,active)
  values(p_id,p_business_id,btrim(p_name),nullif(btrim(coalesce(p_phone,'')),''),nullif(btrim(coalesce(p_instagram,'')),''),nullif(btrim(coalesce(p_source,'')),''),coalesce(p_marketing_consent,false),v_notes,coalesce(p_active,true))
  on conflict(id) do update set name=excluded.name,phone=excluded.phone,instagram=excluded.instagram,source=excluded.source,marketing_consent=excluded.marketing_consent,notes=excluded.notes,active=excluded.active,updated_at=now() where public.customers.business_id=p_business_id;
  if not exists(select 1 from public.customers c where c.id=p_id and c.business_id=p_business_id) then raise exception 'O identificador do cliente pertence a outra empresa.' using errcode='42501';end if;
  if not coalesce(v_exists,false) or coalesce(v_previous_consent,false) is distinct from coalesce(p_marketing_consent,false) then
    insert into public.customer_marketing_consents(business_id,customer_id,status,source,notice_version,actor_user_id,occurred_at,expires_at)
    values(p_business_id,p_id,case when coalesce(p_marketing_consent,false) then 'granted' else 'revoked' end,'customer_editor','privacy-2026-09',auth.uid(),now(),case when coalesce(p_marketing_consent,false) then now()+interval '24 months' else null end);
  end if;
end;$$;

create or replace function public.get_customers_snapshot(p_business_id uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
  if not private.is_business_member(p_business_id) then raise exception 'Acesso negado.' using errcode='42501';end if;
  return coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'phone',c.phone,'instagram',c.instagram,'source',c.source,'marketingConsent',c.marketing_consent,'notes',c.notes,'active',c.active,'createdAt',c.created_at,'updatedAt',c.updated_at,'consentStatus',cm.status,'consentGrantedAt',case when cm.status='granted' then cm.occurred_at else null end,'consentExpiresAt',case when cm.status='granted' then cm.expires_at else null end,'consentNoticeVersion',cm.notice_version) order by c.name)
  from public.customers c left join lateral(select m.status,m.occurred_at,m.expires_at,m.notice_version from public.customer_marketing_consents m where m.business_id=c.business_id and m.customer_id=c.id order by m.occurred_at desc,m.id desc limit 1) cm on true where c.business_id=p_business_id),'[]'::jsonb);
end;$$;

create or replace function public.erase_customer_privacy_v1(p_business_id uuid,p_customer_id uuid,p_reason text default 'Solicitação de privacidade')
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_exists boolean;v_sales bigint;
begin
  if not private.is_business_member(p_business_id) then raise exception 'Acesso negado.' using errcode='42501';end if;
  select exists(select 1 from public.customers where id=p_customer_id and business_id=p_business_id) into v_exists;if not v_exists then raise exception 'Cliente não encontrado.' using errcode='P0002';end if;
  perform set_config('app.audit_reason','privacy_erasure',true);select count(*) into v_sales from public.sales where business_id=p_business_id and customer_id=p_customer_id;
  update public.sales set customer_id=null,updated_at=now() where business_id=p_business_id and customer_id=p_customer_id;
  delete from public.customers where business_id=p_business_id and id=p_customer_id;
  insert into public.privacy_request_log(business_id,customer_id,request_type,result,reason,actor_user_id) values(p_business_id,p_customer_id,'erasure','completed',left(coalesce(nullif(btrim(p_reason),''),'Solicitação de privacidade'),200),auth.uid());
  return jsonb_build_object('customerId',p_customer_id,'detachedSales',v_sales,'result','completed');
end;$$;
revoke all on function public.erase_customer_privacy_v1(uuid,uuid,text) from public,anon;
grant execute on function public.erase_customer_privacy_v1(uuid,uuid,text) to authenticated;

create or replace function private.cleanup_privacy_retention_v1()
returns void language plpgsql security definer set search_path='' as $$
declare r record;
begin
  update public.customers c set marketing_consent=false,updated_at=now() where c.marketing_consent=true and exists(select 1 from lateral(select m.status,m.expires_at from public.customer_marketing_consents m where m.business_id=c.business_id and m.customer_id=c.id order by m.occurred_at desc,m.id desc limit 1) latest where latest.status='granted' and latest.expires_at is not null and latest.expires_at<=now());
  insert into public.customer_marketing_consents(business_id,customer_id,status,source,notice_version,actor_user_id,occurred_at,expires_at)
  select c.business_id,c.id,'expired','retention_job','privacy-2026-09',null,now(),null from public.customers c where c.marketing_consent=false and exists(select 1 from public.customer_marketing_consents m where m.business_id=c.business_id and m.customer_id=c.id and m.status='granted' and m.expires_at is not null and m.expires_at<=now()) and not exists(select 1 from public.customer_marketing_consents newer where newer.business_id=c.business_id and newer.customer_id=c.id and newer.status='expired' and newer.occurred_at>=now()-interval '1 day');
  for r in select c.business_id,c.id from public.customers c left join lateral(select max(s.sold_at) last_sale from public.sales s where s.business_id=c.business_id and s.customer_id=c.id and s.status<>'cancelled') ls on true left join lateral(select m.status,m.expires_at from public.customer_marketing_consents m where m.business_id=c.business_id and m.customer_id=c.id order by m.occurred_at desc,m.id desc limit 1) cm on true where greatest(c.created_at,coalesce(ls.last_sale,c.created_at))<now()-interval '24 months' and not(cm.status='granted' and cm.expires_at>now()) loop
    perform set_config('app.audit_reason','privacy_retention',true);update public.sales set customer_id=null,updated_at=now() where business_id=r.business_id and customer_id=r.id;delete from public.customers where business_id=r.business_id and id=r.id;insert into public.privacy_request_log(business_id,customer_id,request_type,result,reason,actor_user_id) values(r.business_id,r.id,'retention_erasure','completed','24 meses sem relacionamento comercial ativo e sem consentimento de marketing válido',null);
  end loop;
  delete from public.privacy_request_log where created_at<now()-interval '5 years';
end;$$;

create or replace function private.cleanup_nat_operational_logs()
returns void language plpgsql security definer set search_path='' as $$
begin
  delete from public.mutation_requests where created_at<now()-interval '7 days';
  delete from public.ai_generation_log where created_at<now()-interval '90 days';
  delete from public.notification_delivery_log where created_at<now()-interval '90 days';
  perform private.cleanup_privacy_retention_v1();
end;$$;

commit;