-- NAT Gestão normalized schema and security baseline.
-- Mirrors the production database hardening applied on 2026-09-09.
begin;
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;
drop table if exists public.board_items cascade;
drop table if exists public.boards cascade;
drop function if exists public.update_updated_at_column() cascade;

create table if not exists public.businesses(id uuid primary key default gen_random_uuid(), name text not null check(char_length(btrim(name)) between 1 and 120), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.business_members(business_id uuid not null references public.businesses(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member' check(role in('admin','member')), created_at timestamptz not null default now(), primary key(business_id,user_id));
create table if not exists public.supplies(id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null check(char_length(btrim(name)) between 1 and 160), category text not null check(category in('ingredient','packaging')), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,id));
create table if not exists public.supply_purchases(id uuid primary key default gen_random_uuid(), business_id uuid not null, supply_id uuid not null, package_quantity numeric(14,4) not null check(package_quantity>0), package_unit text not null check(package_unit in('g','kg','ml','l','unit')), package_price numeric(14,2) not null check(package_price>=0), purchased_at date not null default current_date, created_at timestamptz not null default now(), unique(business_id,id), foreign key(business_id,supply_id) references public.supplies(business_id,id) on delete cascade);
create table if not exists public.products(id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null check(char_length(btrim(name)) between 1 and 160), batch_yield numeric(14,4) not null check(batch_yield>0), selling_price numeric(14,2) not null default 0 check(selling_price>=0), loss_percent numeric(7,3) not null default 0 check(loss_percent between 0 and 100), production_cost_per_batch numeric(14,2) not null default 0 check(production_cost_per_batch>=0), minimum_margin_percent numeric(7,3) not null default 35 check(minimum_margin_percent>=0 and minimum_margin_percent<95), target_margin_percent numeric(7,3) not null default 50 check(target_margin_percent>=0 and target_margin_percent<95), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(business_id,id));
create table if not exists public.recipe_items(id uuid primary key default gen_random_uuid(), business_id uuid not null, product_id uuid not null, supply_id uuid not null, quantity numeric(14,4) not null check(quantity>0), unit text not null check(unit in('g','kg','ml','l','unit')), created_at timestamptz not null default now(), unique(business_id,id), foreign key(business_id,product_id) references public.products(business_id,id) on delete cascade, foreign key(business_id,supply_id) references public.supplies(business_id,id) on delete restrict);
create table if not exists public.sales(id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, sold_at timestamptz not null default now(), total_received numeric(14,2) not null check(total_received>=0), payment_method text not null check(payment_method in('pix','cash','card','other')), variable_fee_snapshot numeric(14,2) not null default 0 check(variable_fee_snapshot>=0), contribution_snapshot numeric(14,2) not null, created_at timestamptz not null default now(), unique(business_id,id));
create table if not exists public.sale_items(id uuid primary key default gen_random_uuid(), business_id uuid not null, sale_id uuid not null, product_id uuid not null, product_name_snapshot text not null, quantity numeric(14,4) not null check(quantity>0), unit_cost_snapshot numeric(14,4) not null check(unit_cost_snapshot>=0), unit_price_snapshot numeric(14,4) not null check(unit_price_snapshot>=0), created_at timestamptz not null default now(), unique(business_id,id), foreign key(business_id,sale_id) references public.sales(business_id,id) on delete cascade, foreign key(business_id,product_id) references public.products(business_id,id) on delete restrict);
create table if not exists public.business_settings(business_id uuid primary key references public.businesses(id) on delete cascade, owner_name text not null default 'NAT', monthly_fixed_costs numeric(14,2) not null default 0 check(monthly_fixed_costs>=0), payment_fee_percent numeric(7,3) not null default 0 check(payment_fee_percent between 0 and 100), default_minimum_margin_percent numeric(7,3) not null default 35, default_target_margin_percent numeric(7,3) not null default 50, updated_at timestamptz not null default now());
create table if not exists public.audit_log(id bigint generated always as identity primary key, business_id uuid not null references public.businesses(id) on delete cascade, actor_user_id uuid references auth.users(id) on delete set null, action text not null check(action in('INSERT','UPDATE','DELETE')), entity_table text not null, entity_id uuid, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
create table if not exists private.allowed_auth_emails(email text primary key, created_at timestamptz not null default now(), check(email=lower(btrim(email)) and position('@' in email)>1));

create or replace function private.is_business_member(p_business_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select coalesce(auth.jwt()->>'aal','aal1')='aal2' and exists(select 1 from public.business_members bm where bm.business_id=p_business_id and bm.user_id=auth.uid()) $$;
create or replace function private.is_business_admin(p_business_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select coalesce(auth.jwt()->>'aal','aal1')='aal2' and exists(select 1 from public.business_members bm where bm.business_id=p_business_id and bm.user_id=auth.uid() and bm.role='admin') $$;
create or replace function private.set_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at:=now(); return new; end $$;
create or replace function private.enforce_allowed_auth_email() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.email is null or not exists(select 1 from private.allowed_auth_emails a where a.email=lower(btrim(new.email))) then raise exception 'Cadastro não autorizado para este e-mail.' using errcode='42501'; end if; return new; end $$;
create or replace function private.prevent_last_admin_loss() returns trigger language plpgsql security definer set search_path='' as $$ declare n integer; begin if old.role='admin' and (tg_op='DELETE' or new.role<>'admin') then select count(*) into n from public.business_members bm where bm.business_id=old.business_id and bm.user_id<>old.user_id and bm.role='admin'; if n=0 then raise exception 'A empresa precisa manter pelo menos um administrador.' using errcode='23514'; end if; end if; return coalesce(new,old); end $$;
create or replace function private.audit_row_change() returns trigger language plpgsql security definer set search_path='' as $$ declare b jsonb; a jsonb; s jsonb; bid uuid; eid uuid; begin if tg_op='INSERT' then a:=to_jsonb(new); s:=a; elsif tg_op='UPDATE' then b:=to_jsonb(old); a:=to_jsonb(new); s:=a; else b:=to_jsonb(old); s:=b; end if; bid:=nullif(s->>'business_id','')::uuid; eid:=nullif(coalesce(s->>'id',s->>'user_id',s->>'business_id'),'')::uuid; insert into public.audit_log(business_id,actor_user_id,action,entity_table,entity_id,before_data,after_data) values(bid,auth.uid(),tg_op,tg_table_name,eid,b,a); return coalesce(new,old); end $$;

create or replace function public.bootstrap_nat_business(p_name text default 'NAT',p_owner_name text default 'NAT') returns uuid language plpgsql security definer set search_path='' as $$ declare u uuid:=auth.uid(); b uuid; begin if u is null or coalesce(auth.jwt()->>'aal','aal1')<>'aal2' then raise exception 'MFA required' using errcode='42501'; end if; select business_id into b from public.business_members where user_id=u order by created_at limit 1; if b is not null then return b; end if; insert into public.businesses(name) values(left(coalesce(nullif(btrim(p_name),''),'NAT'),120)) returning id into b; insert into public.business_members values(b,u,'admin',now()); insert into public.business_settings(business_id,owner_name) values(b,left(coalesce(nullif(btrim(p_owner_name),''),'NAT'),120)); return b; end $$;
create or replace function public.save_supply(p_business_id uuid,p_id uuid,p_name text,p_category text,p_package_quantity numeric,p_package_unit text,p_package_price numeric,p_purchased_at date) returns void language plpgsql security invoker set search_path='' as $$ declare r record; begin insert into public.supplies(id,business_id,name,category,active) values(p_id,p_business_id,p_name,p_category,true) on conflict(id) do update set business_id=excluded.business_id,name=excluded.name,category=excluded.category,active=true; select package_quantity,package_unit,package_price,purchased_at into r from public.supply_purchases where business_id=p_business_id and supply_id=p_id order by purchased_at desc,created_at desc limit 1; if r is null or r.package_quantity is distinct from p_package_quantity or r.package_unit is distinct from p_package_unit or r.package_price is distinct from p_package_price or r.purchased_at is distinct from p_purchased_at then insert into public.supply_purchases(business_id,supply_id,package_quantity,package_unit,package_price,purchased_at) values(p_business_id,p_id,p_package_quantity,p_package_unit,p_package_price,p_purchased_at); end if; end $$;
create or replace function public.delete_supply(p_business_id uuid,p_id uuid) returns void language sql security invoker set search_path='' as $$ update public.supplies set active=false where business_id=p_business_id and id=p_id $$;
create or replace function public.save_product(p_business_id uuid,p_id uuid,p_name text,p_batch_yield numeric,p_selling_price numeric,p_loss_percent numeric,p_production_cost_per_batch numeric,p_minimum_margin_percent numeric,p_target_margin_percent numeric,p_recipe jsonb) returns void language plpgsql security invoker set search_path='' as $$ begin insert into public.products(id,business_id,name,batch_yield,selling_price,loss_percent,production_cost_per_batch,minimum_margin_percent,target_margin_percent,active) values(p_id,p_business_id,p_name,p_batch_yield,p_selling_price,p_loss_percent,p_production_cost_per_batch,p_minimum_margin_percent,p_target_margin_percent,true) on conflict(id) do update set business_id=excluded.business_id,name=excluded.name,batch_yield=excluded.batch_yield,selling_price=excluded.selling_price,loss_percent=excluded.loss_percent,production_cost_per_batch=excluded.production_cost_per_batch,minimum_margin_percent=excluded.minimum_margin_percent,target_margin_percent=excluded.target_margin_percent,active=true; delete from public.recipe_items where business_id=p_business_id and product_id=p_id; insert into public.recipe_items(id,business_id,product_id,supply_id,quantity,unit) select coalesce(nullif(x->>'id','')::uuid,gen_random_uuid()),p_business_id,p_id,(x->>'supplyId')::uuid,(x->>'quantity')::numeric,x->>'unit' from jsonb_array_elements(coalesce(p_recipe,'[]'::jsonb)) x; end $$;
create or replace function public.archive_product(p_business_id uuid,p_id uuid) returns void language sql security invoker set search_path='' as $$ update public.products set active=false where business_id=p_business_id and id=p_id $$;
create or replace function public.save_sale(p_business_id uuid,p_id uuid,p_product_id uuid,p_product_name text,p_quantity numeric,p_total_received numeric,p_payment_method text,p_sold_at timestamptz,p_unit_cost_snapshot numeric,p_variable_fee_snapshot numeric,p_contribution_snapshot numeric) returns void language plpgsql security invoker set search_path='' as $$ begin insert into public.sales(id,business_id,sold_at,total_received,payment_method,variable_fee_snapshot,contribution_snapshot) values(p_id,p_business_id,p_sold_at,p_total_received,p_payment_method,p_variable_fee_snapshot,p_contribution_snapshot); insert into public.sale_items(business_id,sale_id,product_id,product_name_snapshot,quantity,unit_cost_snapshot,unit_price_snapshot) values(p_business_id,p_id,p_product_id,p_product_name,p_quantity,p_unit_cost_snapshot,case when p_quantity>0 then p_total_received/p_quantity else 0 end); end $$;
create or replace function public.delete_sale(p_business_id uuid,p_id uuid) returns void language sql security invoker set search_path='' as $$ delete from public.sales where business_id=p_business_id and id=p_id $$;
create or replace function public.save_business_settings(p_business_id uuid,p_owner_name text,p_monthly_fixed_costs numeric,p_payment_fee_percent numeric,p_default_minimum_margin_percent numeric,p_default_target_margin_percent numeric) returns void language plpgsql security invoker set search_path='' as $$ begin insert into public.business_settings(business_id,owner_name,monthly_fixed_costs,payment_fee_percent,default_minimum_margin_percent,default_target_margin_percent) values(p_business_id,p_owner_name,p_monthly_fixed_costs,p_payment_fee_percent,p_default_minimum_margin_percent,p_default_target_margin_percent) on conflict(business_id) do update set owner_name=excluded.owner_name,monthly_fixed_costs=excluded.monthly_fixed_costs,payment_fee_percent=excluded.payment_fee_percent,default_minimum_margin_percent=excluded.default_minimum_margin_percent,default_target_margin_percent=excluded.default_target_margin_percent; end $$;

alter table public.businesses enable row level security; alter table public.business_members enable row level security; alter table public.supplies enable row level security; alter table public.supply_purchases enable row level security; alter table public.products enable row level security; alter table public.recipe_items enable row level security; alter table public.sales enable row level security; alter table public.sale_items enable row level security; alter table public.business_settings enable row level security; alter table public.audit_log enable row level security;

do $$ declare t text; begin foreach t in array array['supplies','supply_purchases','products','recipe_items','sales','sale_items'] loop execute format('drop policy if exists %I_select on public.%I',t,t); execute format('create policy %I_select on public.%I for select to authenticated using (private.is_business_member(business_id))',t,t); execute format('drop policy if exists %I_insert on public.%I',t,t); execute format('create policy %I_insert on public.%I for insert to authenticated with check (private.is_business_member(business_id))',t,t); execute format('drop policy if exists %I_update on public.%I',t,t); execute format('create policy %I_update on public.%I for update to authenticated using (private.is_business_member(business_id)) with check (private.is_business_member(business_id))',t,t); execute format('drop policy if exists %I_delete on public.%I',t,t); execute format('create policy %I_delete on public.%I for delete to authenticated using (private.is_business_member(business_id))',t,t); end loop; end $$;
drop policy if exists businesses_select on public.businesses; create policy businesses_select on public.businesses for select to authenticated using(private.is_business_member(id));
drop policy if exists businesses_update on public.businesses; create policy businesses_update on public.businesses for update to authenticated using(private.is_business_admin(id)) with check(private.is_business_admin(id));
drop policy if exists business_members_select on public.business_members; create policy business_members_select on public.business_members for select to authenticated using(private.is_business_member(business_id));
drop policy if exists business_members_insert on public.business_members; create policy business_members_insert on public.business_members for insert to authenticated with check(private.is_business_admin(business_id));
drop policy if exists business_members_update on public.business_members; create policy business_members_update on public.business_members for update to authenticated using(private.is_business_admin(business_id)) with check(private.is_business_admin(business_id));
drop policy if exists business_members_delete on public.business_members; create policy business_members_delete on public.business_members for delete to authenticated using(private.is_business_admin(business_id) and user_id<>auth.uid());
drop policy if exists business_settings_select on public.business_settings; create policy business_settings_select on public.business_settings for select to authenticated using(private.is_business_member(business_id));
drop policy if exists business_settings_update on public.business_settings; create policy business_settings_update on public.business_settings for update to authenticated using(private.is_business_admin(business_id)) with check(private.is_business_admin(business_id));
drop policy if exists audit_log_select on public.audit_log; create policy audit_log_select on public.audit_log for select to authenticated using(private.is_business_admin(business_id));

revoke all on all tables in schema public from anon,authenticated; revoke all on all sequences in schema public from anon,authenticated; revoke all on private.allowed_auth_emails from public,anon,authenticated; revoke all on all functions in schema private from public,anon,authenticated; revoke create on schema public from public; grant usage on schema public,private to authenticated; grant execute on function private.is_business_member(uuid),private.is_business_admin(uuid) to authenticated;
grant select,update on public.businesses to authenticated; grant select,insert,update,delete on public.business_members,public.supplies,public.supply_purchases,public.products,public.recipe_items,public.sales,public.sale_items to authenticated; grant select,update on public.business_settings to authenticated; grant select on public.audit_log to authenticated;
revoke all on function public.bootstrap_nat_business(text,text),public.save_supply(uuid,uuid,text,text,numeric,text,numeric,date),public.delete_supply(uuid,uuid),public.save_product(uuid,uuid,text,numeric,numeric,numeric,numeric,numeric,numeric,jsonb),public.archive_product(uuid,uuid),public.save_sale(uuid,uuid,uuid,text,numeric,numeric,text,timestamptz,numeric,numeric,numeric),public.delete_sale(uuid,uuid),public.save_business_settings(uuid,text,numeric,numeric,numeric,numeric) from public,anon;
grant execute on function public.bootstrap_nat_business(text,text),public.save_supply(uuid,uuid,text,text,numeric,text,numeric,date),public.delete_supply(uuid,uuid),public.save_product(uuid,uuid,text,numeric,numeric,numeric,numeric,numeric,numeric,jsonb),public.archive_product(uuid,uuid),public.save_sale(uuid,uuid,uuid,text,numeric,numeric,text,timestamptz,numeric,numeric,numeric),public.delete_sale(uuid,uuid),public.save_business_settings(uuid,text,numeric,numeric,numeric,numeric) to authenticated;
alter default privileges in schema public revoke all on tables from anon,authenticated; alter default privileges in schema public revoke all on sequences from anon,authenticated;

-- Triggers.
drop trigger if exists businesses_touch_updated_at on public.businesses; create trigger businesses_touch_updated_at before update on public.businesses for each row execute function private.set_updated_at();
drop trigger if exists supplies_touch_updated_at on public.supplies; create trigger supplies_touch_updated_at before update on public.supplies for each row execute function private.set_updated_at();
drop trigger if exists products_touch_updated_at on public.products; create trigger products_touch_updated_at before update on public.products for each row execute function private.set_updated_at();
drop trigger if exists business_members_keep_admin on public.business_members; create trigger business_members_keep_admin before update of role or delete on public.business_members for each row execute function private.prevent_last_admin_loss();
drop trigger if exists nat_allowlisted_signup_only on auth.users; create trigger nat_allowlisted_signup_only before insert on auth.users for each row execute function private.enforce_allowed_auth_email();
do $$ declare t text; begin foreach t in array array['business_members','supplies','supply_purchases','products','recipe_items','sales','sale_items','business_settings'] loop execute format('drop trigger if exists %I_audit on public.%I',t,t); execute format('create trigger %I_audit after insert or update or delete on public.%I for each row execute function private.audit_row_change()',t,t); end loop; end $$;
commit;
